# Generated by Django 4.2.22 on 2026-02-27 16:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome oficial do parceiro (e.g., "Paack", "Amazon Logistics")', max_length=200, unique=True, verbose_name='Nome do Parceiro')),
                ('nif', models.CharField(help_text='Número de Identificação Fiscal português', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='NIF deve ter 9 dígitos, opcionalmente precedidos por "PT"', regex='^(PT)?\\d{9}$')], verbose_name='NIF')),
                ('contact_email', models.EmailField(help_text='Email principal para comunicações operacionais', max_length=254, verbose_name='Email de Contacto')),
                ('contact_phone', models.CharField(blank=True, help_text='Telefone de suporte operacional', max_length=20, verbose_name='Telefone de Contacto')),
                ('api_credentials', models.JSONField(blank=True, default=dict, help_text='Credenciais de API (api_key, api_secret, etc.). Será encriptado em produção.', verbose_name='Credenciais API')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, não serão feitas novas importações de pedidos', verbose_name='Ativo')),
                ('default_delivery_time_days', models.IntegerField(default=2, help_text='Prazo padrão para entregas sem data específica', verbose_name='Prazo de Entrega Padrão (dias)')),
                ('auto_assign_orders', models.BooleanField(default=True, help_text='Se ativo, pedidos serão automaticamente atribuídos a motoristas disponíveis', verbose_name='Auto-Atribuir Pedidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('notes', models.TextField(blank=True, help_text='Notas internas sobre o parceiro', verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('API', 'API REST/JSON'), ('SFTP', 'SFTP (CSV/XML)'), ('EMAIL', 'Email (anexos)'), ('WEBHOOK', 'Webhook'), ('MANUAL', 'Manual')], default='API', max_length=20, verbose_name='Tipo de Integração')),
                ('endpoint_url', models.URLField(blank=True, help_text='URL base da API do parceiro', max_length=500, verbose_name='URL do Endpoint')),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='Configuração de autenticação (type: bearer/basic/oauth, tokens, etc.)', verbose_name='Configuração de Autenticação')),
                ('sync_frequency_minutes', models.IntegerField(default=15, help_text='Intervalo entre importações automáticas de pedidos', verbose_name='Frequência de Sincronização (minutos)')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('last_sync_status', models.CharField(blank=True, choices=[('SUCCESS', 'Sucesso'), ('ERROR', 'Erro'), ('PARTIAL', 'Parcial')], max_length=20, verbose_name='Status da Última Sincronização')),
                ('last_sync_message', models.TextField(blank=True, verbose_name='Mensagem da Última Sincronização')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, não fará sincronizações automáticas', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='core.partner', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Integração de Parceiro',
                'verbose_name_plural': 'Integrações de Parceiros',
                'ordering': ['partner__name', '-is_active'],
            },
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['is_active', 'name'], name='core_partne_is_acti_7f5f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['nif'], name='core_partne_nif_8c3e42_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerintegration',
            index=models.Index(fields=['partner', 'is_active'], name='core_partne_partner_c72e43_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerintegration',
            index=models.Index(fields=['last_sync_at'], name='core_partne_last_sy_05a7f7_idx'),
        ),
    ]
