# Generated by Django 4.2.22 on 2026-02-28 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('IMPORT_ORDERS', 'Importação de Pedidos'), ('EXPORT_ORDERS', 'Exportação de Pedidos'), ('IMPORT_DRIVERS', 'Importação de Motoristas'), ('EXPORT_DRIVERS', 'Exportação de Motoristas'), ('UPDATE_STATUS', 'Atualização de Status'), ('HEALTH_CHECK', 'Verificação de Saúde')], default='IMPORT_ORDERS', max_length=30, verbose_name='Operação')),
                ('status', models.CharField(choices=[('STARTED', 'Iniciado'), ('SUCCESS', 'Sucesso'), ('ERROR', 'Erro'), ('PARTIAL', 'Parcial'), ('TIMEOUT', 'Timeout')], db_index=True, default='STARTED', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Iniciado Em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído Em')),
                ('records_processed', models.IntegerField(default=0, help_text='Total de registros processados (sucesso + erro)', verbose_name='Registros Processados')),
                ('records_created', models.IntegerField(default=0, verbose_name='Registros Criados')),
                ('records_updated', models.IntegerField(default=0, verbose_name='Registros Atualizados')),
                ('records_failed', models.IntegerField(default=0, verbose_name='Registros Falhados')),
                ('message', models.TextField(blank=True, help_text='Mensagem de status ou resumo da operação', verbose_name='Mensagem')),
                ('error_details', models.TextField(blank=True, help_text='Stack trace ou detalhes técnicos do erro', verbose_name='Detalhes do Erro')),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Parâmetros enviados na requisição (para debug)', verbose_name='Dados da Requisição')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Amostra da resposta recebida (primeiros registros)', verbose_name='Dados da Resposta')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='core.partnerintegration', verbose_name='Integração')),
            ],
            options={
                'verbose_name': 'Log de Sincronização',
                'verbose_name_plural': 'Logs de Sincronização',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['integration', 'status'], name='core_synclo_integra_c55b9c_idx'), models.Index(fields=['started_at', 'status'], name='core_synclo_started_fbbef6_idx'), models.Index(fields=['operation', 'status'], name='core_synclo_operati_29049a_idx')],
            },
        ),
    ]
