# Generated by Django 4.2.22 on 2026-03-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_synclog"),
    ]

    operations = [
        migrations.AddField(
            model_name="synclog",
            name="is_from_cache",
            field=models.BooleanField(
                default=False,
                help_text="Se True, dados foram processados do cache ao invés da API",
                verbose_name="Do Cache",
            ),
        ),
    ]
