# Generated by Django 4.2.22 on 2026-04-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_synclog_is_from_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='bonus_performance_enabled',
            field=models.BooleanField(default=False, help_text='Se ativo, aplica bónus quando taxa de sucesso ≥ limiar configurado.', verbose_name='Bónus por Performance'),
        ),
        migrations.AddField(
            model_name='partner',
            name='bonus_sunday_holiday_enabled',
            field=models.BooleanField(default=False, help_text='Se ativo, aplica bónus adicional em entregas ao domingo ou feriado.', verbose_name='Bónus Domingo/Feriado'),
        ),
        migrations.AddField(
            model_name='partner',
            name='bonus_volume_enabled',
            field=models.BooleanField(default=False, help_text='Se ativo, aplica bónus quando volume ultrapassa limiar configurado.', verbose_name='Bónus por Volume'),
        ),
        migrations.AddField(
            model_name='partner',
            name='irs_retention_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentagem de retenção na fonte (ex: 25 ou 11.5).', max_digits=5, verbose_name='Retenção IRS (%)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='price_per_package',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Preço base que o parceiro paga por pacote entregue.', max_digits=8, verbose_name='Valor por Pacote (€)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='vat_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se definido, substitui a taxa padrão do regime.', max_digits=5, null=True, verbose_name='Taxa IVA (override, %)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='vat_regime',
            field=models.CharField(choices=[('normal', 'Regime Normal (23%)'), ('isento', 'Isento (art. 53º)'), ('simplificado', 'Simplificado')], default='normal', max_length=20, verbose_name='Regime de IVA'),
        ),
    ]
