# Generated by Django 4.2.22 on 2026-04-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_partner_bonus_performance_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='driver_default_price_per_package',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Default global pago ao motorista por pacote entregue. Cascata: Driver.price_per_package > EmpresaParceira.driver_default > Partner.driver_default.', max_digits=8, null=True, verbose_name='Valor por Pacote ao Driver (default) (€)'),
        ),
    ]
