# Generated by Django 4.2.22 on 2026-02-26 21:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'NIF deve conter exatamente 9 digitos')], verbose_name='NIF')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('niss', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'NISS deve conter 11 digitos')], verbose_name='NISS')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('nacionalidade', models.CharField(default='Portugal', max_length=100)),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{9,15}$', 'Telefone invalido')], verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('endereco_residencia', models.TextField(blank=True, verbose_name='Endereco Completo')),
                ('codigo_postal', models.CharField(blank=True, max_length=8, verbose_name='Codigo Postal')),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('tipo_vinculo', models.CharField(choices=[('DIRETO', 'Direto - Recibos Verdes'), ('PARCEIRO', 'Parceiro - Frota')], default='DIRETO', max_length=10, verbose_name='Tipo de Vinculo')),
                ('nome_frota', models.CharField(blank=True, max_length=200, verbose_name='Nome da Frota (se Parceiro)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente - Aguardando documentos'), ('EM_ANALISE', 'Em Analise - Documentos enviados'), ('ATIVO', 'Ativo - Aprovado'), ('BLOQUEADO', 'Bloqueado - Documentos expirados'), ('IRREGULAR', 'Irregular - Problemas no cadastro')], default='PENDENTE', max_length=15, verbose_name='Status do Cadastro')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo no Sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovacao')),
                ('approved_by', models.CharField(blank=True, max_length=100, verbose_name='Aprovado por')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes Internas')),
            ],
            options={
                'verbose_name': 'Perfil de Motorista',
                'verbose_name_plural': 'Perfis de Motoristas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]+$', 'Matricula invalida')], verbose_name='Matricula')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('tipo_veiculo', models.CharField(choices=[('MOTA', 'Mota'), ('LIGEIRO', 'Ligeiro de Mercadorias'), ('CARRINHA_35T', 'Carrinha ate 3.5t'), ('CARRINHA_GRANDE', 'Carrinha acima 3.5t'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo de Veiculo')),
                ('ano', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('cor', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Veiculo Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='drivers_app.driverprofile', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Veiculo',
                'verbose_name_plural': 'Veiculos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DUA', 'DUA - Documento Unico Automovel'), ('IPO', 'Folha da Inspecao (IPO)'), ('SEGURO', 'Certificado de Seguro (Carta Verde)'), ('OUTRO', 'Outro Documento')], max_length=20, verbose_name='Tipo de Documento')),
                ('arquivo', models.FileField(upload_to='vehicle_documents/%Y/%m/', verbose_name='Arquivo')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_documents', to='drivers_app.vehicle', verbose_name='Veiculo')),
            ],
            options={
                'verbose_name': 'Documento do Veiculo',
                'verbose_name_plural': 'Documentos dos Veiculos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cartao de Cidadao'), ('TR', 'Titulo de Residencia'), ('PP', 'Passaporte'), ('MI', 'Manifestacao de Interesse'), ('CNH_FRENTE', 'Carta de Conducao - Frente'), ('CNH_VERSO', 'Carta de Conducao - Verso'), ('ADR', 'Certificado ADR'), ('RC', 'Registo Criminal'), ('DECLARACAO_ATIVIDADE', 'Declaracao de Inicio de Atividade'), ('OUTRO', 'Outro Documento')], max_length=30, verbose_name='Tipo de Documento')),
                ('arquivo', models.FileField(upload_to='driver_documents/%Y/%m/', verbose_name='Arquivo')),
                ('data_validade', models.DateField(blank=True, help_text='Sistema alerta 30 dias antes do vencimento', null=True, verbose_name='Data de Validade')),
                ('categoria_cnh', models.CharField(blank=True, help_text='Ex: B, C, D', max_length=10, verbose_name='Categoria CNH')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers_app.driverprofile', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Documento do Motorista',
                'verbose_name_plural': 'Documentos dos Motoristas',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
