# Generated by Django 4.2.22 on 2026-04-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='importado_auto',
            field=models.BooleanField(default=False, help_text='Driver criado por importação de planilha — dados pessoais pendentes de atualização', verbose_name='Importado Automaticamente'),
        ),
    ]
