# Generated by Django 4.2.22 on 2026-04-13 16:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0002_driverprofile_importado_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao_por_pacote', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='Valor em € pago por cada pacote entregue pelo motorista indicado.', max_digits=8, verbose_name='Comissão por pacote (€)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to='drivers_app.driverprofile', verbose_name='Motorista indicado')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_given', to='drivers_app.driverprofile', verbose_name='Quem indicou')),
            ],
            options={
                'verbose_name': 'Indicação',
                'verbose_name_plural': 'Indicações',
                'ordering': ['-created_at'],
            },
        ),
    ]
