# Generated by Django 4.2.22 on 2026-04-13 20:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0003_driverreferral'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('nif', models.CharField(blank=True, help_text='Número de Identificação Fiscal (ex: PT123456789)', max_length=20, verbose_name='NIF')),
                ('morada', models.TextField(blank=True, verbose_name='Morada')),
                ('codigo_postal', models.CharField(blank=True, max_length=8, verbose_name='Código Postal')),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('contacto_nome', models.CharField(blank=True, max_length=150, verbose_name='Nome do Contacto')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('taxa_iva', models.DecimalField(decimal_places=2, default=Decimal('23.00'), max_digits=5, verbose_name='Taxa IVA (%)')),
                ('ativo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa Parceira',
                'verbose_name_plural': 'Empresas Parceiras',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='empresa_parceira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motoristas', to='drivers_app.empresaparceira', verbose_name='Empresa Parceira'),
        ),
    ]
