# Generated by Django 4.2.22 on 2026-04-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0006_empresa_parceira_lancamento_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaparceiralancamento',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='empresa_lancamentos/comprovativos/%Y/%m/', verbose_name='Comprovante de Pagamento'),
        ),
        migrations.AddField(
            model_name='empresaparceiralancamento',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AddField(
            model_name='empresaparceiralancamento',
            name='referencia_pagamento',
            field=models.CharField(blank=True, help_text='MB WAY, Transferência, etc.', max_length=200, verbose_name='Referência de Pagamento'),
        ),
    ]
