# Generated by Django 4.2.22 on 2026-04-15 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers_app', '0007_add_payment_fields_to_lancamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pacote', models.CharField(db_index=True, max_length=100, verbose_name='Nº Pacote / Tracking')),
                ('tipo', models.CharField(choices=[('ENTREGA_FALSA', 'Entrega Falsa'), ('ITEM_FALTANDO', 'Item Faltando'), ('PACOTE_DANIFICADO', 'Pacote Danificado'), ('ENTREGA_ATRASADA', 'Entrega Atrasada'), ('OUTRO', 'Outro')], db_index=True, default='ENTREGA_FALSA', max_length=30, verbose_name='Tipo de Reclamação')),
                ('descricao', models.TextField(help_text='Descrição detalhada da reclamação do cliente.', verbose_name='Relato do Cliente')),
                ('nome_cliente', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('telefone_cliente', models.CharField(max_length=30, verbose_name='Telefone do Cliente')),
                ('email_cliente', models.CharField(blank=True, max_length=200, verbose_name='Email do Cliente')),
                ('morada', models.TextField(help_text='Rua, nº, andar, etc.', verbose_name='Morada')),
                ('codigo_postal', models.CharField(max_length=20, verbose_name='Código Postal')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('NOTIFICADO', 'Motorista Notificado'), ('RESPONDIDO', 'Resposta Recebida'), ('FECHADO', 'Fechado'), ('CANCELADO', 'Cancelado')], db_index=True, default='ABERTO', max_length=20, verbose_name='Status')),
                ('data_notificacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Notificação ao Motorista')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resposta do Motorista')),
                ('data_fecho', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fecho')),
                ('resposta_driver', models.TextField(blank=True, verbose_name='Resposta do Motorista')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaints', to='drivers_app.driverprofile', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Reclamação de Cliente',
                'verbose_name_plural': 'Reclamações de Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerComplaintAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECLAMACAO', 'Print da Reclamação'), ('RESPOSTA_DRIVER', 'Resposta do Motorista'), ('OUTRO', 'Outro')], default='RECLAMACAO', max_length=20, verbose_name='Tipo')),
                ('ficheiro', models.FileField(upload_to='complaints/%Y/%m/', verbose_name='Ficheiro')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='drivers_app.customercomplaint')),
            ],
        ),
    ]
