# Generated by Django 4.2.22 on 2026-04-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0011_add_taxa_iva_to_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='advance_monthly_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Limite acumulado de adiantamentos por mês. Vazio = sem limite.', max_digits=8, null=True, verbose_name='Limite Mensal de Adiantamentos (€)'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='bonus_performance_enabled',
            field=models.BooleanField(default=True, help_text='Override: permite desligar bónus de performance neste motorista.', verbose_name='Aplicar Bónus Performance'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='caucao_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentagem retida até o motorista atingir o nº configurado de entregas sem claim.', max_digits=5, verbose_name='Retenção de Caução (%)'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='caucao_threshold_deliveries',
            field=models.PositiveIntegerField(default=0, help_text='Nº de entregas consecutivas sem claim para libertar caução.', verbose_name='Entregas para Libertar Caução'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='irs_retention_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Override do IRS. 0 = usar do Parceiro.', max_digits=5, verbose_name='Retenção IRS (%)'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='price_per_package',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valor que o motorista recebe por pacote entregue. Se vazio, usa o preço configurado no Parceiro.', max_digits=8, null=True, verbose_name='Valor por Pacote (€)'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vat_regime',
            field=models.CharField(choices=[('normal', 'Regime Normal'), ('isento', 'Isento (art. 53º)'), ('simplificado', 'Simplificado')], default='isento', max_length=20, verbose_name='Regime de IVA'),
        ),
    ]
