# Generated by Django 4.2.22 on 2026-04-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0012_driverprofile_advance_monthly_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='apelido',
            field=models.CharField(blank=True, db_index=True, help_text="Apelido usado nas plataformas dos parceiros (ex: 'Helena_Duarte_MRB_LF'). Útil para encontrar rápido em relatórios.", max_length=100, verbose_name='Apelido / Alias'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='courier_id_cainiao',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador único Cainiao deste motorista (não muda). Usado para fazer match na importação Driver Statistic.', max_length=50, verbose_name='Courier ID Cainiao'),
        ),
    ]
