# Generated by Django 4.2.22 on 2026-04-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0013_driverprofile_apelido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaparceira',
            name='driver_default_price_per_package',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Default pago aos motoristas desta frota por pacote entregue. Sobrepõe o default do parceiro mas é sobreposto pelo Driver.price_per_package.', max_digits=8, null=True, verbose_name='Valor por Pacote ao Driver (default da frota) (€)'),
        ),
    ]
