# Generated by Django 4.2.22 on 2026-04-25 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0014_empresaparceira_driver_default_price_per_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetAutoEmitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Activo')),
                ('period_type', models.CharField(choices=[('monthly', 'Mensal (mês anterior completo)'), ('weekly', 'Semanal (semana anterior, segunda a domingo)')], default='monthly', max_length=10, verbose_name='Tipo de período')),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='Para período mensal — dia em que dispara (1-28)', verbose_name='Dia do mês para emitir')),
                ('weekday', models.PositiveSmallIntegerField(default=0, help_text='Para período semanal — 0=Seg, 1=Ter,…, 6=Dom. Cobre semana anterior.', verbose_name='Dia da semana para emitir')),
                ('auto_send_whatsapp', models.BooleanField(default=False, verbose_name='Enviar WhatsApp automaticamente após emitir')),
                ('last_emitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_emitted_period_from', models.DateField(blank=True, null=True)),
                ('last_emitted_period_to', models.DateField(blank=True, null=True)),
                ('last_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_emit_config', to='drivers_app.empresaparceira')),
            ],
            options={
                'verbose_name': 'Configuração Auto-emit',
                'verbose_name_plural': 'Configurações Auto-emit',
            },
        ),
    ]
