# Generated by Django 4.2.22 on 2026-04-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0015_fleetautoemitconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='daily_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Capacidade-alvo de pacotes/dia. Usada no planeamento automático. Se vazio, calcula via média histórica (últimos 14 dias entregues).', null=True, verbose_name='Capacidade Diária (pacotes)'),
        ),
    ]
