# Generated by Django 4.2.22 on 2026-05-04 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers_app', '0016_driverprofile_daily_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfileChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('telefone', 'Telefone'), ('email', 'Email'), ('endereco_residencia', 'Endereço'), ('codigo_postal', 'Código Postal'), ('cidade', 'Cidade'), ('nacionalidade', 'Nacionalidade')], db_index=True, max_length=50, verbose_name='Campo')),
                ('old_value', models.TextField(blank=True, verbose_name='Valor anterior')),
                ('new_value', models.TextField(blank=True, verbose_name='Novo valor')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado pelo motorista')], db_index=True, default='pending', max_length=15, verbose_name='Estado')),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Motivo de rejeição ou observações da aprovação.', verbose_name='Notas da revisão')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='drivers_app.driverprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Alteração de Perfil',
                'verbose_name_plural': 'Pedidos de Alteração de Perfil',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', '-requested_at'], name='drivers_app_status_094da6_idx'), models.Index(fields=['driver', '-requested_at'], name='drivers_app_driver__91f4d8_idx')],
            },
        ),
    ]
