# Generated by Django 4.2.22 on 2026-05-05 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers_app', '0017_add_profile_change_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverMergeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_driver_repr', models.CharField(help_text='Snapshot textual do driver source antes do delete.', max_length=200, verbose_name='Source (apagado)')),
                ('source_driver_id', models.IntegerField(db_index=True, verbose_name='Source ID original')),
                ('transferred_counts', models.JSONField(default=dict, help_text="Ex: {'pre_invoices': 3, 'access': 2, 'mappings': 5}", verbose_name='Quantidades transferidas')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('merged_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('merged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_merges_performed', to=settings.AUTH_USER_MODEL)),
                ('target_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merges_received', to='drivers_app.driverprofile', verbose_name='Driver target (que recebeu os dados)')),
            ],
            options={
                'verbose_name': 'Auditoria de Unificação',
                'verbose_name_plural': 'Auditorias de Unificação',
                'ordering': ['-merged_at'],
            },
        ),
    ]
