# Generated by Django 4.2.22 on 2026-05-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0018_drivermergeaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAutoEmitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Activo')),
                ('period_type', models.CharField(choices=[('monthly', 'Mensal (mês anterior completo)'), ('biweekly', 'Quinzenal (15 dias anteriores)'), ('weekly', 'Semanal (semana anterior, segunda a domingo)')], default='monthly', max_length=10, verbose_name='Tipo de período')),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='Para mensal/quinzenal — 1-28', verbose_name='Dia do mês para emitir')),
                ('weekday', models.PositiveSmallIntegerField(default=0, help_text='Para semanal — 0=Seg, 6=Dom', verbose_name='Dia da semana para emitir')),
                ('auto_approve', models.BooleanField(default=False, help_text='Se desligado, fica em CALCULADO para revisão manual.', verbose_name='Auto-aprovar (passar a APROVADO)')),
                ('auto_send_whatsapp', models.BooleanField(default=False, verbose_name='Enviar WhatsApp ao motorista após emitir')),
                ('last_emitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_emitted_period_from', models.DateField(blank=True, null=True)),
                ('last_emitted_period_to', models.DateField(blank=True, null=True)),
                ('last_pf_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_emit_config', to='drivers_app.driverprofile')),
            ],
            options={
                'verbose_name': 'Auto-emit (Motorista)',
                'verbose_name_plural': 'Auto-emit (Motoristas)',
            },
        ),
    ]
