# Generated by Django 4.2.22 on 2026-02-27 16:45

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Data do Turno')),
                ('start_time', models.TimeField(default=datetime.time(9, 0), help_text='Hora de início do turno', verbose_name='Hora de Início')),
                ('end_time', models.TimeField(default=datetime.time(18, 0), help_text='Hora prevista de fim do turno', verbose_name='Hora de Fim')),
                ('actual_start_time', models.DateTimeField(blank=True, help_text='Hora em que motorista iniciou turno (check-in)', null=True, verbose_name='Início Real')),
                ('actual_end_time', models.DateTimeField(blank=True, help_text='Hora em que motorista finalizou turno (check-out)', null=True, verbose_name='Fim Real')),
                ('total_deliveries', models.IntegerField(default=0, help_text='Número total de entregas atribuídas', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de Entregas')),
                ('successful_deliveries', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Entregas Bem-Sucedidas')),
                ('failed_deliveries', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Entregas Falhadas')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendado'), ('IN_PROGRESS', 'Em Progresso'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], db_index=True, default='SCHEDULED', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('whatsapp_notification_sent', models.BooleanField(default=False, verbose_name='Notificação WhatsApp Enviada')),
                ('whatsapp_notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Notificação Enviada em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_postal_zones', models.ManyToManyField(help_text='Zonas onde o motorista deve fazer entregas neste turno', related_name='driver_shifts', to='pricing.postalzone', verbose_name='Zonas Postais Atribuídas')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='drivers_app.driverprofile', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Turno de Motorista',
                'verbose_name_plural': 'Turnos de Motoristas',
                'ordering': ['-date', 'start_time'],
                'indexes': [models.Index(fields=['driver', '-date'], name='route_alloc_driver__e135a8_idx'), models.Index(fields=['date', 'status'], name='route_alloc_date_eaafca_idx'), models.Index(fields=['-date'], name='route_alloc_date_ad3ac0_idx')],
                'unique_together': {('driver', 'date')},
            },
        ),
    ]
