# Generated by Django 4.2.22 on 2026-02-27 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('drivers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(db_index=True, help_text='Data para a qual se prevê o volume', verbose_name='Data da Previsão')),
                ('predicted_volume', models.IntegerField(help_text='Número de pedidos previstos', verbose_name='Volume Previsto')),
                ('confidence_level', models.DecimalField(decimal_places=2, help_text='Confiança estatística da previsão', max_digits=5, verbose_name='Nível de Confiança (%)')),
                ('lower_bound', models.IntegerField(help_text='Menor volume esperado (intervalo de confiança)', verbose_name='Limite Inferior')),
                ('upper_bound', models.IntegerField(help_text='Maior volume esperado (intervalo de confiança)', verbose_name='Limite Superior')),
                ('method', models.CharField(choices=[('MA7', 'Média Móvel 7 dias'), ('MA30', 'Média Móvel 30 dias'), ('EMA', 'Média Móvel Exponencial'), ('TREND', 'Análise de Tendência'), ('SEASONAL', 'Sazonalidade')], default='MA7', max_length=20, verbose_name='Método')),
                ('historical_days', models.IntegerField(default=30, help_text='Número de dias usados no cálculo', verbose_name='Dias Históricos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('actual_volume', models.IntegerField(blank=True, help_text='Volume real após o dia passar', null=True, verbose_name='Volume Real')),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='Quão próxima foi a previsão do real', max_digits=5, null=True, verbose_name='Acurácia (%)')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_forecasts', to='core.partner', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Previsão de Volume',
                'verbose_name_plural': 'Previsões de Volume',
                'db_table': 'analytics_volume_forecast',
                'ordering': ['-forecast_date', 'partner'],
                'indexes': [models.Index(fields=['partner', '-forecast_date'], name='analytics_v_partner_b4b2b2_idx'), models.Index(fields=['-forecast_date', 'method'], name='analytics_v_forecas_681d77_idx')],
                'unique_together': {('partner', 'forecast_date', 'method')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_SUCCESS', 'Taxa de Sucesso Baixa'), ('HIGH_FAILURES', 'Muitas Falhas'), ('DELAYED_DELIVERIES', 'Entregas Atrasadas'), ('LOW_DRIVER_COUNT', 'Poucos Motoristas Ativos'), ('VOLUME_SPIKE', 'Pico de Volume Inesperado'), ('REVENUE_DROP', 'Queda de Receita')], db_index=True, max_length=30, verbose_name='Tipo de Alerta')),
                ('severity', models.CharField(choices=[('INFO', 'Informativo'), ('WARNING', 'Aviso'), ('CRITICAL', 'Crítico')], default='WARNING', max_length=10, verbose_name='Severidade')),
                ('date', models.DateField(db_index=True, verbose_name='Data')),
                ('description', models.TextField(help_text='Descrição detalhada do alerta', verbose_name='Descrição')),
                ('metric_value', models.DecimalField(decimal_places=2, help_text='Valor que disparou o alerta', max_digits=10, verbose_name='Valor da Métrica')),
                ('threshold_value', models.DecimalField(decimal_places=2, help_text='Valor do threshold configurado', max_digits=10, verbose_name='Threshold')),
                ('is_acknowledged', models.BooleanField(default=False, help_text='Se o alerta foi visto por um gestor', verbose_name='Reconhecido')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconhecido em')),
                ('acknowledged_by', models.CharField(blank=True, max_length=100, verbose_name='Reconhecido por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_alerts', to='core.partner', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Alerta de Performance',
                'verbose_name_plural': 'Alertas de Performance',
                'db_table': 'analytics_performance_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partner', '-created_at'], name='analytics_p_partner_cdb8a6_idx'), models.Index(fields=['-created_at', 'severity'], name='analytics_p_created_00a88d_idx'), models.Index(fields=['is_acknowledged', '-created_at'], name='analytics_p_is_ackn_77828e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, help_text='Primeiro dia do mês (YYYY-MM-01)', verbose_name='Mês')),
                ('total_deliveries', models.IntegerField(default=0, verbose_name='Total de Entregas')),
                ('successful_deliveries', models.IntegerField(default=0, verbose_name='Entregas Bem-Sucedidas')),
                ('failed_deliveries', models.IntegerField(default=0, verbose_name='Entregas Falhadas')),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa de Sucesso (%)')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ganhos Totais')),
                ('total_bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bónus Totais')),
                ('total_penalties', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Penalidades Totais')),
                ('days_worked', models.IntegerField(default=0, verbose_name='Dias Trabalhados')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas Totais')),
                ('average_deliveries_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Média Entregas/Dia')),
                ('rank_in_team', models.IntegerField(blank=True, help_text='Posição entre todos os motoristas', null=True, verbose_name='Posição no Ranking')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Calculado em')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_history', to='drivers_app.driverprofile')),
            ],
            options={
                'verbose_name': 'Performance de Motorista',
                'verbose_name_plural': 'Performance de Motoristas',
                'db_table': 'analytics_driver_performance',
                'ordering': ['-month', 'driver'],
                'indexes': [models.Index(fields=['driver', '-month'], name='analytics_d_driver__cc8714_idx'), models.Index(fields=['-month', '-success_rate'], name='analytics_d_month_bad05b_idx')],
                'unique_together': {('driver', 'month')},
            },
        ),
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Data')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Total de Pedidos')),
                ('delivered_orders', models.IntegerField(default=0, verbose_name='Pedidos Entregues')),
                ('failed_orders', models.IntegerField(default=0, verbose_name='Pedidos Falhados')),
                ('pending_orders', models.IntegerField(default=0, verbose_name='Pedidos Pendentes')),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa de Sucesso (%)')),
                ('average_delivery_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tempo Médio de Entrega (horas)')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Receita Total')),
                ('total_bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de Bónus')),
                ('total_penalties', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de Penalidades')),
                ('active_drivers_count', models.IntegerField(default=0, verbose_name='Motoristas Ativos')),
                ('active_vehicles_count', models.IntegerField(default=0, verbose_name='Veículos Ativos')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Calculado em')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='core.partner', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Métrica Diária',
                'verbose_name_plural': 'Métricas Diárias',
                'db_table': 'analytics_daily_metrics',
                'ordering': ['-date', 'partner'],
                'indexes': [models.Index(fields=['partner', '-date'], name='analytics_d_partner_2b8f85_idx'), models.Index(fields=['-date', 'success_rate'], name='analytics_d_date_ceb03e_idx')],
                'unique_together': {('partner', 'date')},
            },
        ),
    ]
