# Generated by Django 4.2.22 on 2026-02-27 16:45

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome descritivo da zona (e.g., "Lisboa Centro", "Grande Porto")', max_length=100, verbose_name='Nome da Zona')),
                ('code', models.CharField(help_text='Código único da zona (e.g., "LIS-CENTRO", "PORTO-NORTE")', max_length=20, unique=True, verbose_name='Código')),
                ('postal_code_pattern', models.CharField(help_text='Padrão regex para match de códigos postais (e.g., "^11\\d{2}" para Lisboa)', max_length=200, verbose_name='Padrão de Códigos Postais')),
                ('region', models.CharField(blank=True, choices=[('NORTE', 'Norte'), ('CENTRO', 'Centro'), ('LISBOA', 'Lisboa e Vale do Tejo'), ('ALENTEJO', 'Alentejo'), ('ALGARVE', 'Algarve'), ('MADEIRA', 'Madeira'), ('ACORES', 'Açores')], max_length=100, verbose_name='Região')),
                ('center_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude do centro da zona', max_digits=9, null=True, verbose_name='Latitude Central')),
                ('center_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude do centro da zona', max_digits=9, null=True, verbose_name='Longitude Central')),
                ('is_urban', models.BooleanField(default=True, help_text='Se zona é urbana (vs. rural)', verbose_name='Zona Urbana')),
                ('average_delivery_time_hours', models.IntegerField(default=24, help_text='Tempo médio estimado para entrega nesta zona', verbose_name='Tempo Médio de Entrega (horas)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zona Postal',
                'verbose_name_plural': 'Zonas Postais',
                'ordering': ['region', 'name'],
                'indexes': [models.Index(fields=['code'], name='pricing_pos_code_48a6da_idx'), models.Index(fields=['region', 'is_active'], name='pricing_pos_region_73344f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Preço base por entrega (€)', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Base')),
                ('success_bonus', models.DecimalField(decimal_places=2, default=0, help_text='Bónus adicional por entrega bem-sucedida (€)', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bónus por Entrega')),
                ('failure_penalty', models.DecimalField(decimal_places=2, default=0, help_text='Dedução por falha na entrega (€)', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Penalização por Falha')),
                ('late_delivery_penalty', models.DecimalField(decimal_places=2, default=0, help_text='Dedução por entrega atrasada (€)', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Penalização por Atraso')),
                ('weekend_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicador para entregas em fim de semana (1.0 = sem alteração)', max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Multiplicador Fim de Semana')),
                ('express_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplicador para entregas expressas', max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Multiplicador Expresso')),
                ('valid_from', models.DateField(db_index=True, default=datetime.date.today, help_text='Data a partir da qual esta tarifa é aplicável', verbose_name='Válido Desde')),
                ('valid_until', models.DateField(blank=True, db_index=True, help_text='Data até à qual esta tarifa é aplicável (deixar vazio = sem limite)', null=True, verbose_name='Válido Até')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='core.partner', verbose_name='Parceiro')),
                ('postal_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='pricing.postalzone', verbose_name='Zona Postal')),
            ],
            options={
                'verbose_name': 'Tarifa de Parceiro',
                'verbose_name_plural': 'Tarifas de Parceiros',
                'ordering': ['partner', 'postal_zone', '-valid_from'],
                'indexes': [models.Index(fields=['partner', 'postal_zone', 'is_active'], name='pricing_par_partner_744714_idx'), models.Index(fields=['valid_from', 'valid_until'], name='pricing_par_valid_f_7c8389_idx')],
                'unique_together': {('partner', 'postal_zone', 'valid_from')},
            },
        ),
    ]
