# Generated by Django 4.2.22 on 2026-04-24 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnertariff',
            name='valid_until',
            field=models.DateField(blank=True, db_index=True, help_text='Data limite (vazio = sem limite)', null=True, verbose_name='Válido Até'),
        ),
        migrations.AlterField(
            model_name='partnertariff',
            name='weekend_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicador fim de semana (1.0 = sem alteração)', max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Multiplicador Fim de Semana'),
        ),
        migrations.AlterField(
            model_name='postalzone',
            name='name',
            field=models.CharField(help_text='Nome descritivo (e.g., "Lisboa Centro")', max_length=100, verbose_name='Nome da Zona'),
        ),
        migrations.AlterField(
            model_name='postalzone',
            name='postal_code_pattern',
            field=models.CharField(help_text='Padrão regex (e.g., "^11\\d{2}" para Lisboa)', max_length=200, verbose_name='Padrão de Códigos Postais'),
        ),
    ]
