# Generated by Django 4.2.22 on 2026-05-04 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers_app', '0017_add_profile_change_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Termo de Adesão, NDA, Contrato de Prestação de Serviços', max_length=200, verbose_name='Nome')),
                ('version', models.CharField(default='1.0', help_text='Ex: 1.0, 2024-Q1, etc.', max_length=20, verbose_name='Versão')),
                ('scope', models.CharField(choices=[('all', 'Todos os motoristas'), ('independent', 'Apenas independentes'), ('fleet', 'Apenas frotas (subcontratados)')], default='all', max_length=15, verbose_name='Aplicabilidade')),
                ('content', models.TextField(help_text='Aceita HTML básico ou Markdown. Será mostrado ao motorista antes da assinatura.', verbose_name='Conteúdo (HTML/Markdown)')),
                ('is_active', models.BooleanField(default=True, help_text='Quando inactivo, novos motoristas não recebem este contrato. Os já assinados continuam válidos.', verbose_name='Activo')),
                ('effective_from', models.DateField(default=django.utils.timezone.now, verbose_name='Vigente desde')),
                ('expires_at', models.DateField(blank=True, help_text='Opcional. Após esta data, motoristas devem re-assinar versão nova.', null=True, verbose_name='Vigente até')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contract_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo de Contrato',
                'verbose_name_plural': 'Modelos de Contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_snapshot', models.TextField(help_text='Cópia do template para preservar conteúdo mesmo se o template mudar.', verbose_name='Conteúdo no momento da assinatura')),
                ('signed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da assinatura')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('signature_text', models.CharField(default='Li e aceito os termos.', max_length=200, verbose_name='Frase de aceitação')),
                ('content_hash', models.CharField(blank=True, help_text='Garante que o conteúdo não foi modificado depois da assinatura.', max_length=64, verbose_name='Hash SHA-256 do conteúdo')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/signed/', verbose_name='PDF assinado')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='drivers_app.driverprofile')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_contracts', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signed_contracts', to='contracts.contracttemplate')),
            ],
            options={
                'verbose_name': 'Contrato Assinado',
                'verbose_name_plural': 'Contratos Assinados',
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['driver', '-signed_at'], name='contracts_d_driver__84955d_idx'), models.Index(fields=['template', '-signed_at'], name='contracts_d_templat_c999cc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='drivercontract',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('driver', 'template'), name='unique_active_contract_per_driver_template'),
        ),
        migrations.AddIndex(
            model_name='contracttemplate',
            index=models.Index(fields=['is_active', 'scope'], name='contracts_c_is_acti_292d6f_idx'),
        ),
    ]
