# Generated by Django 4.2.22 on 2025-09-06 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordersmanager_paack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_type', models.CharField(choices=[('ADD', 'Adição'), ('SUB', 'Subtração')], max_length=3, verbose_name='Tipo de Correção')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_corrections', to=settings.AUTH_USER_MODEL)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_corrections', to='ordersmanager_paack.dispatch')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_corrections', to='ordersmanager_paack.driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_corrections', to='ordersmanager_paack.order')),
            ],
            options={
                'verbose_name': 'Correção Manual',
                'verbose_name_plural': 'Correções Manuais',
                'ordering': ['-created_at'],
            },
        ),
    ]
