# Generated by Django 4.2.22 on 2025-09-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manualorders_paack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualcorrection',
            name='status',
            field=models.CharField(choices=[('delivered', 'Entregue'), ('on_course', 'Em Rota'), ('picked_up', 'Coletado'), ('reached_picked_up', 'Chegou ao Ponto de Coleta'), ('return_in_progress', 'Retorno em Andamento'), ('undelivered', 'Não Entregue')], default='delivered', max_length=20, verbose_name='Status'),
        ),
    ]
