# Generated by Django 4.2.22 on 2025-09-17 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordersmanager_paack', '0002_alter_order_client_address'),
        ('manualorders_paack', '0002_manualcorrection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualcorrection',
            name='correction_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data para qual a correção se aplica', verbose_name='Data da Correção'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualcorrection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se False, a correção foi desfeita', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='manualcorrection',
            name='original_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='original_manual_corrections', to='ordersmanager_paack.driver'),
        ),
        migrations.AddField(
            model_name='manualcorrection',
            name='original_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Status Original'),
        ),
        migrations.AddField(
            model_name='manualcorrection',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade de entregas adicionadas/removidas', verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='manualcorrection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='correction_type',
            field=models.CharField(choices=[('ADD', 'Adição'), ('SUB', 'Subtração'), ('EDIT', 'Edição')], max_length=4, verbose_name='Tipo de Correção'),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='status',
            field=models.CharField(choices=[('delivered', 'Entregue'), ('on_course', 'Em Rota'), ('picked_up', 'Coletado'), ('reached_picked_up', 'Chegou ao Ponto de Coleta'), ('return_in_progress', 'Retorno em Andamento'), ('undelivered', 'Não Entregue'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='delivered', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='manualcorrection',
            index=models.Index(fields=['correction_date', 'driver'], name='manualorder_correct_0bb050_idx'),
        ),
        migrations.AddIndex(
            model_name='manualcorrection',
            index=models.Index(fields=['created_at', 'correction_type'], name='manualorder_created_1cf63c_idx'),
        ),
        migrations.AddIndex(
            model_name='manualcorrection',
            index=models.Index(fields=['is_active', 'correction_date'], name='manualorder_is_acti_1e2a86_idx'),
        ),
    ]
