# Generated by Django 4.2.22 on 2026-02-26 19:41

from django.db import migrations, models
import system_config.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_admin_email',
            field=system_config.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True, verbose_name='Typebot Admin Email'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_admin_password',
            field=system_config.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True, verbose_name='Typebot Admin Password'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_builder_url',
            field=system_config.fields.EncryptedCharField(blank=True, default='http://localhost:8081', max_length=512, max_plain_length=255, null=True, verbose_name='Typebot Builder URL'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_database_url',
            field=system_config.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True, verbose_name='Typebot Database URL'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_default_workspace_plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('unlimited', 'Unlimited')], default='free', max_length=32, verbose_name='Typebot Default Workspace Plan'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_disable_signup',
            field=models.BooleanField(default=True, verbose_name='Typebot Disable Signup'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_enabled',
            field=models.BooleanField(default=False, verbose_name='Typebot Ativado'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_encryption_secret',
            field=system_config.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True, verbose_name='Typebot Encryption Secret'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_google_client_id',
            field=system_config.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True, verbose_name='Typebot Google Client ID'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_google_client_secret',
            field=system_config.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True, verbose_name='Typebot Google Client Secret'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_s3_access_key',
            field=system_config.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True, verbose_name='Typebot S3 Access Key'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_s3_bucket',
            field=system_config.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True, verbose_name='Typebot S3 Bucket'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_s3_endpoint',
            field=system_config.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True, verbose_name='Typebot S3 Endpoint'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_s3_secret_key',
            field=system_config.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True, verbose_name='Typebot S3 Secret Key'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_smtp_from',
            field=system_config.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True, verbose_name='Typebot SMTP From'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_smtp_host',
            field=system_config.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True, verbose_name='Typebot SMTP Host'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_smtp_password',
            field=system_config.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True, verbose_name='Typebot SMTP Password'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_smtp_port',
            field=models.IntegerField(blank=True, default=587, null=True, verbose_name='Typebot SMTP Port'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_smtp_username',
            field=system_config.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True, verbose_name='Typebot SMTP Username'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_viewer_url',
            field=system_config.fields.EncryptedCharField(blank=True, default='http://localhost:8082', max_length=512, max_plain_length=255, null=True, verbose_name='Typebot Viewer URL'),
        ),
    ]
