# Generated by Django 4.2.22 on 2026-02-26 20:27

from django.db import migrations
import system_config.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0002_systemconfiguration_typebot_admin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='typebot_api_key',
            field=system_config.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True, verbose_name='Typebot API Key'),
        ),
    ]
