# Generated by Django 4.2.22 on 2026-02-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0003_systemconfiguration_typebot_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_alerts_check_days',
            field=models.IntegerField(default=1, help_text='Quantos dias de métricas analisar (default: 1 = hoje)', verbose_name='Dias de Análise (Alertas)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_alerts_enabled',
            field=models.BooleanField(default=False, help_text='Ativa o job que verifica thresholds de performance', verbose_name='Verificação de Alertas Ativada'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_alerts_last_run',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Última Execução (Alertas)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_alerts_last_status',
            field=models.CharField(blank=True, choices=[('success', 'Sucesso'), ('failed', 'Falhou'), ('running', 'Em Execução')], editable=False, max_length=20, null=True, verbose_name='Status Última Execução (Alertas)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_alerts_schedule',
            field=models.CharField(default='06:00,12:00,18:00', help_text='Múltiplos horários separados por vírgula. Ex: 06:00,12:00,18:00', max_length=50, verbose_name='Horários de Execução (Alertas)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_alerts_send_notifications',
            field=models.BooleanField(default=True, help_text='Se True, envia notificações quando alertas são criados', verbose_name='Enviar Notificações'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_forecasts_best_only',
            field=models.BooleanField(default=True, help_text='Se True, mantém apenas o forecast com maior confiança por data', verbose_name='Manter Apenas Melhor Previsão'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_forecasts_days_ahead',
            field=models.IntegerField(default=7, help_text='Quantos dias prever no futuro (default: 7)', verbose_name='Dias de Previsão'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_forecasts_enabled',
            field=models.BooleanField(default=False, help_text='Ativa o job que gera previsões de volume', verbose_name='Geração de Forecasts Ativada'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_forecasts_last_run',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Última Execução (Forecasts)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_forecasts_last_status',
            field=models.CharField(blank=True, choices=[('success', 'Sucesso'), ('failed', 'Falhou'), ('running', 'Em Execução')], editable=False, max_length=20, null=True, verbose_name='Status Última Execução (Forecasts)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_forecasts_method',
            field=models.CharField(choices=[('MA7', 'Média Móvel 7 dias'), ('MA30', 'Média Móvel 30 dias'), ('EMA', 'Exponential Moving Average'), ('TREND', 'Análise de Tendências'), ('SEASONAL', 'Padrões Sazonais'), ('ALL', 'Todos os Métodos')], default='ALL', help_text='Método estatístico para previsão', max_length=10, verbose_name='Método de Forecasting'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_forecasts_schedule',
            field=models.CharField(default='02:00', help_text='Formato HH:MM (24h). Exemplo: 02:00 para 2h da manhã', max_length=5, verbose_name='Horário de Execução (Forecasts)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_metrics_backfill_days',
            field=models.IntegerField(default=1, help_text='Quantos dias recalcular em cada execução (default: 1 = apenas ontem)', verbose_name='Dias de Backfill (Métricas)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_metrics_enabled',
            field=models.BooleanField(default=False, help_text='Ativa o job que calcula métricas agregadas diariamente', verbose_name='Cálculo de Métricas Diárias Ativado'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_metrics_last_run',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Última Execução (Métricas)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_metrics_last_status',
            field=models.CharField(blank=True, choices=[('success', 'Sucesso'), ('failed', 'Falhou'), ('running', 'Em Execução')], editable=False, max_length=20, null=True, verbose_name='Status Última Execução (Métricas)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cron_metrics_schedule',
            field=models.CharField(default='01:00', help_text='Formato HH:MM (24h). Exemplo: 01:00 para 1h da manhã', max_length=5, verbose_name='Horário de Execução (Métricas)'),
        ),
        migrations.CreateModel(
            name='CronJobExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('metrics', 'Cálculo de Métricas Diárias'), ('forecasts', 'Geração de Forecasts'), ('alerts', 'Verificação de Alertas')], db_index=True, max_length=20, verbose_name='Tipo de Job')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Iniciado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('duration_seconds', models.FloatField(blank=True, editable=False, null=True, verbose_name='Duração (segundos)')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('failed', 'Falhou'), ('running', 'Em Execução')], default='running', max_length=20, verbose_name='Status')),
                ('records_created', models.IntegerField(default=0, verbose_name='Registros Criados')),
                ('records_updated', models.IntegerField(default=0, verbose_name='Registros Atualizados')),
                ('records_skipped', models.IntegerField(default=0, verbose_name='Registros Ignorados')),
                ('errors_count', models.IntegerField(default=0, verbose_name='Erros')),
                ('output_log', models.TextField(blank=True, verbose_name='Log de Saída')),
                ('error_log', models.TextField(blank=True, verbose_name='Log de Erros')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parâmetros')),
                ('triggered_by', models.CharField(default='cron', help_text='cron, manual, api, etc.', max_length=50, verbose_name='Iniciado por')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='Hostname')),
            ],
            options={
                'verbose_name': 'Execução de Cron Job',
                'verbose_name_plural': 'Execuções de Cron Jobs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job_type', '-started_at'], name='system_conf_job_typ_aad6fa_idx'), models.Index(fields=['status', '-started_at'], name='system_conf_status_a7d3ac_idx')],
            },
        ),
    ]
