# Generated by Django 4.2.22 on 2026-04-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0004_systemconfiguration_cron_alerts_check_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='company_email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='company_localidade',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Localidade (Código Postal + Cidade)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='company_morada',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Morada'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='company_nif',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='company_telefone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone'),
        ),
    ]
