# Generated by Django 4.2.22 on 2026-05-05 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_config', '0005_add_company_contact_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Apenas uma entrada por dia. Aglomera todas as alterações.', unique=True, verbose_name='Data')),
                ('version', models.CharField(help_text='Ex: beta-05-05.3. Auto-gerada por defeito.', max_length=40, verbose_name='Versão actual')),
                ('version_history', models.JSONField(blank=True, default=list, help_text='Lista de versões emitidas neste dia.', verbose_name='Histórico de versões')),
                ('content', models.TextField(help_text='Markdown ou texto livre. Lista as alterações deste dia.', verbose_name='Conteúdo do changelog')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changelog_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Changelog',
                'verbose_name_plural': 'Changelog',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemVersionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_version', models.CharField(blank=True, max_length=40, verbose_name='Versão deployada')),
                ('deployed_commit_hash', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Commit deployado (SHA)')),
                ('deployed_at', models.DateTimeField(blank=True, null=True, verbose_name='Deployado em')),
                ('github_repo_url', models.CharField(blank=True, help_text='Ex: https://github.com/owner/repo', max_length=300, verbose_name='URL do repositório GitHub')),
                ('github_branch', models.CharField(default='main', max_length=80, verbose_name='Branch')),
                ('github_token', models.CharField(blank=True, max_length=200, verbose_name='GitHub Token (opcional, para repos privados)')),
                ('last_check_at', models.DateTimeField(blank=True, null=True, verbose_name='Última verificação')),
                ('last_check_result', models.JSONField(blank=True, default=dict, verbose_name='Último resultado')),
            ],
            options={
                'verbose_name': 'Estado da Versão',
                'verbose_name_plural': 'Estado da Versão',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('category', models.CharField(choices=[('UI', 'Interface / Usabilidade'), ('FEATURE', 'Nova funcionalidade'), ('PERFORMANCE', 'Performance'), ('BUG', 'Bug / Defeito'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='Categoria')),
                ('submitter_name', models.CharField(blank=True, help_text='Preenchido quando o autor não está autenticado.', max_length=120, verbose_name='Nome do autor')),
                ('status', models.CharField(choices=[('NEW', 'Nova'), ('REVIEWING', 'Em análise'), ('PLANNED', 'Planeada'), ('DONE', 'Implementada'), ('REJECTED', 'Rejeitada')], db_index=True, default='NEW', max_length=20, verbose_name='Estado')),
                ('admin_response', models.TextField(blank=True, verbose_name='Resposta do admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('related_changelog', models.ForeignKey(blank=True, help_text='Versão na qual a sugestão foi implementada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions_addressed', to='system_config.changelogentry')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sugestão',
                'verbose_name_plural': 'Sugestões',
                'ordering': ['-created_at'],
            },
        ),
    ]
