# Generated by Django 4.2.22 on 2026-05-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0006_changelogentry_systemversionstate_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelogentry',
            name='publish_error',
            field=models.TextField(blank=True, verbose_name='Último erro de publicação'),
        ),
        migrations.AddField(
            model_name='changelogentry',
            name='publish_status',
            field=models.CharField(choices=[('PENDING', 'Por publicar'), ('PUBLISHED', 'Publicado'), ('FAILED', 'Falhou')], default='PENDING', max_length=20, verbose_name='Estado de publicação'),
        ),
        migrations.AddField(
            model_name='changelogentry',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publicado no GitHub em'),
        ),
        migrations.AddField(
            model_name='changelogentry',
            name='published_commit_sha',
            field=models.CharField(blank=True, max_length=40, verbose_name='SHA do commit publicado'),
        ),
        migrations.AlterField(
            model_name='systemversionstate',
            name='github_repo_url',
            field=models.CharField(blank=True, default='https://github.com/kaled182/leguas', help_text='Ex: https://github.com/kaled182/leguas', max_length=300, verbose_name='URL do repositório GitHub'),
        ),
    ]
