# Generated by Django 4.2.22 on 2026-05-07 21:39

from django.db import migrations, models
import system_config.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0007_changelogentry_publish_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='ocr_anthropic_api_key',
            field=system_config.fields.EncryptedCharField(blank=True, help_text='API key para Claude Vision (formato sk-ant-...).', max_length=512, max_plain_length=255, null=True, verbose_name='Anthropic API Key'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='ocr_anthropic_model',
            field=models.CharField(blank=True, default='claude-sonnet-4-6', help_text='ID do modelo (ex: claude-sonnet-4-6, claude-opus-4-7).', max_length=80, null=True, verbose_name='Modelo Claude'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='ocr_gemini_api_key',
            field=system_config.fields.EncryptedCharField(blank=True, help_text='API key do Google AI Studio (free tier 1500 req/dia).', max_length=512, max_plain_length=255, null=True, verbose_name='Gemini API Key'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='ocr_gemini_model',
            field=models.CharField(blank=True, default='gemini-2.0-flash-exp', help_text='ID do modelo (ex: gemini-2.0-flash-exp, gemini-1.5-pro).', max_length=80, null=True, verbose_name='Modelo Gemini'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='ocr_provider',
            field=models.CharField(blank=True, choices=[('', '— Usar variável de ambiente —'), ('gemini', 'Google Gemini (free tier)'), ('anthropic', 'Anthropic Claude (pago)')], default='', max_length=20, null=True, verbose_name='Provedor OCR / IA'),
        ),
    ]
