# Generated by Django 4.2.22 on 2026-05-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0008_ocr_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='ocr_gemini_model',
            field=models.CharField(blank=True, default='gemini-2.5-flash', help_text='ID do modelo (ex: gemini-2.5-flash, gemini-2.0-flash, gemini-1.5-pro).', max_length=80, null=True, verbose_name='Modelo Gemini'),
        ),
    ]
