# Generated by Django 4.2.22 on 2026-09-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0011_systemconfiguration_reliable_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='reliable_claims_sync_enabled',
            field=models.BooleanField(default=False, verbose_name='Descontos pelo julgamento da Cainiao (ReliableMaps)'),
        ),
    ]
