# Generated by Django 4.2.22 on 2026-02-27 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(help_text='Matrícula do veículo (e.g., AA-00-BB)', max_length=20, unique=True, verbose_name='Matrícula')),
                ('brand', models.CharField(help_text='Marca do veículo (e.g., Renault, Peugeot)', max_length=50, verbose_name='Marca')),
                ('model', models.CharField(help_text='Modelo do veículo (e.g., Kangoo, Partner)', max_length=100, verbose_name='Modelo')),
                ('year', models.IntegerField(help_text='Ano de fabrico', verbose_name='Ano')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Carro'), ('VAN', 'Carrinha'), ('MOTORCYCLE', 'Mota'), ('BICYCLE', 'Bicicleta'), ('TRUCK', 'Camião')], default='VAN', max_length=20, verbose_name='Tipo de Veículo')),
                ('owner', models.CharField(blank=True, help_text='Nome do proprietário (empresa ou pessoa física)', max_length=200, verbose_name='Proprietário')),
                ('is_company_owned', models.BooleanField(default=True, help_text='Se não, é veículo de motorista', verbose_name='Pertence à Empresa')),
                ('max_load_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Carga Máxima (kg)')),
                ('fuel_type', models.CharField(blank=True, choices=[('GASOLINE', 'Gasolina'), ('DIESEL', 'Gasóleo'), ('ELECTRIC', 'Elétrico'), ('HYBRID', 'Híbrido')], max_length=20, verbose_name='Tipo de Combustível')),
                ('inspection_expiry', models.DateField(blank=True, db_index=True, help_text='Data de validade da inspeção periódica obrigatória', null=True, verbose_name='Validade da Inspeção')),
                ('insurance_expiry', models.DateField(blank=True, db_index=True, help_text='Data de validade do seguro', null=True, verbose_name='Validade do Seguro')),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, verbose_name='Número da Apólice')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('MAINTENANCE', 'Em Manutenção'), ('INACTIVE', 'Inativo'), ('SOLD', 'Vendido')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('current_odometer_km', models.IntegerField(default=0, help_text='Quilometragem atual do veículo', verbose_name='Quilómetros Atuais')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventiva'), ('CORRECTIVE', 'Corretiva'), ('INSPECTION', 'Inspeção'), ('TIRE_CHANGE', 'Mudança de Pneus'), ('OIL_CHANGE', 'Mudança de Óleo'), ('BRAKE_SERVICE', 'Travões'), ('OTHER', 'Outro')], max_length=20, verbose_name='Tipo de Manutenção')),
                ('description', models.TextField(help_text='Descrição detalhada do serviço realizado', verbose_name='Descrição')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Data Agendada')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('workshop', models.CharField(blank=True, help_text='Nome da oficina/prestador de serviço', max_length=200, verbose_name='Oficina')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Número da Fatura')),
                ('odometer_at_service', models.IntegerField(blank=True, null=True, verbose_name='Quilómetros no Serviço')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fleet_management.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Manutenção de Veículo',
                'verbose_name_plural': 'Manutenções de Veículos',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('FINE', 'Multa'), ('ACCIDENT', 'Acidente'), ('DAMAGE', 'Dano'), ('THEFT', 'Roubo'), ('OTHER', 'Outro')], max_length=20, verbose_name='Tipo de Incidente')),
                ('description', models.TextField(verbose_name='Descrição do Incidente')),
                ('incident_date', models.DateField(db_index=True, verbose_name='Data do Incidente')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, help_text='Valor da multa ou custo do dano', max_digits=10, verbose_name='Valor')),
                ('driver_responsible', models.BooleanField(default=False, help_text='Se sim, valor será deduzido do settlement', verbose_name='Motorista Responsável')),
                ('claim_amount', models.DecimalField(decimal_places=2, default=0, help_text='Valor a ser deduzido do motorista', max_digits=10, verbose_name='Valor a Reclamar')),
                ('photos', models.JSONField(blank=True, default=list, help_text='URLs de fotos do incidente', verbose_name='Fotos')),
                ('police_report_number', models.CharField(blank=True, help_text='Número de participação policial (se aplicável)', max_length=100, verbose_name='Número de Participação')),
                ('resolved', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de Resolução')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, help_text='Motorista responsável (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_incidents', to='drivers_app.driverprofile', verbose_name='Motorista')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='fleet_management.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Incidente de Veículo',
                'verbose_name_plural': 'Incidentes de Veículos',
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Data')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Fim')),
                ('odometer_start', models.IntegerField(blank=True, help_text='Quilometragem no início do turno', null=True, verbose_name='Quilómetros Iniciais')),
                ('odometer_end', models.IntegerField(blank=True, help_text='Quilometragem no fim do turno', null=True, verbose_name='Quilómetros Finais')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='drivers_app.driverprofile', verbose_name='Motorista')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fleet_management.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Atribuição de Veículo',
                'verbose_name_plural': 'Atribuições de Veículos',
                'ordering': ['-date', 'vehicle'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status', 'vehicle_type'], name='fleet_manag_status_836a03_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['inspection_expiry'], name='fleet_manag_inspect_32f3ba_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['insurance_expiry'], name='fleet_manag_insuran_16329e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemaintenance',
            index=models.Index(fields=['vehicle', '-scheduled_date'], name='fleet_manag_vehicle_431d25_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemaintenance',
            index=models.Index(fields=['is_completed', '-scheduled_date'], name='fleet_manag_is_comp_9669f4_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleincident',
            index=models.Index(fields=['vehicle', '-incident_date'], name='fleet_manag_vehicle_a83180_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleincident',
            index=models.Index(fields=['driver', '-incident_date'], name='fleet_manag_driver__cb3207_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleincident',
            index=models.Index(fields=['resolved', '-incident_date'], name='fleet_manag_resolve_689bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['driver', '-date'], name='fleet_manag_driver__7ac551_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['vehicle', '-date'], name='fleet_manag_vehicle_7f77dd_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['date'], name='fleet_manag_date_bb1a80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleassignment',
            unique_together={('vehicle', 'date')},
        ),
    ]
