# Generated by Django 4.2.22 on 2025-06-09 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordersmanager_paack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('nif', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, help_text='Motorista do sistema de pedidos', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_accesses', to='ordersmanager_paack.driver')),
                ('user', models.ForeignKey(help_text='Gestor responsável', on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Access',
                'verbose_name_plural': 'Driver Accesses',
            },
        ),
    ]
