# Generated by Django 4.2.22 on 2025-06-11 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordersmanager_paack', '0001_initial'),
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driveraccess',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Acesso de Motorista', 'verbose_name_plural': 'Acessos de Motoristas'},
        ),
        migrations.AlterField(
            model_name='driveraccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='driveraccess',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Motorista do sistema de pedidos', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_accesses', to='ordersmanager_paack.driver', verbose_name='Motorista'),
        ),
        migrations.AlterField(
            model_name='driveraccess',
            name='email',
            field=models.EmailField(help_text='Email único para login', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='driveraccess',
            name='first_name',
            field=models.CharField(help_text='Nome do motorista', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='driveraccess',
            name='last_name',
            field=models.CharField(help_text='Sobrenome do motorista', max_length=100, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='driveraccess',
            name='nif',
            field=models.CharField(help_text='Número de identificação fiscal', max_length=20, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='driveraccess',
            name='password',
            field=models.CharField(help_text='Hash da senha para autenticação', max_length=128, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='driveraccess',
            name='phone',
            field=models.CharField(help_text='Número de telefone do motorista', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='driveraccess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='driveraccess',
            name='user',
            field=models.ForeignKey(help_text='Gestor responsável por este motorista', on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL, verbose_name='Gestor Responsável'),
        ),
    ]
