# Generated by Django 4.2.22 on 2025-06-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_alter_driveraccess_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveraccess',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Foto do motorista', null=True, upload_to='media/drivers/profile_pictures/', verbose_name='Foto de Perfil'),
        ),
    ]
