# Generated by Django 4.2.22 on 2025-06-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_driveraccess_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveraccess',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/profile_pictures/'),
        ),
    ]
