# Generated by Django 4.2.22 on 2026-05-04 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0016_driverprofile_daily_capacity'),
        ('ordersmanager_paack', '0002_alter_order_client_address'),
        ('customauth', '0004_alter_driveraccess_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveraccess',
            name='driver_profile',
            field=models.OneToOneField(blank=True, help_text='Liga ao DriverProfile que dá acesso ao portal moderno.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', to='drivers_app.driverprofile', verbose_name='Perfil do Motorista'),
        ),
        migrations.AddField(
            model_name='driveraccess',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desactivar bloqueia o login sem apagar a conta.', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='driveraccess',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último login'),
        ),
        migrations.AddField(
            model_name='driveraccess',
            name='username',
            field=models.CharField(blank=True, help_text='Username único de login (default: email).', max_length=100, null=True, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='driveraccess',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Motorista do sistema de pedidos Paack — legacy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_accesses', to='ordersmanager_paack.driver', verbose_name='Motorista (Paack legacy)'),
        ),
    ]
