# Generated by Django 4.2.22 on 2026-05-08 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0019_driverautoemitconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customauth', '0005_driveraccess_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username único de login.', max_length=100, unique=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Password (hash)')),
                ('is_active', models.BooleanField(default=True, help_text='Desactivar bloqueia o login sem apagar a conta.', verbose_name='Activo')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_empresa_accesses', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='drivers_app.empresaparceira')),
            ],
            options={
                'verbose_name': 'Acesso de Frota',
                'verbose_name_plural': 'Acessos de Frota',
                'ordering': ['empresa__nome'],
            },
        ),
    ]
