from django.urls import path

from . import (
    cainiao_views, forecast_plan_views, holiday_views, plan_api,
    views, views_cash_entries, views_shareholder,
    views_cainiao_billing,
)

urlpatterns = [
    # relatórios/fechos (legacy)
    path("summary", views.summary, name="settlements-summary"),
    path("drivers-rank", views.drivers_rank, name="settlements-drivers-rank"),
    path("runs", views.runs_list, name="settlements-runs"),
    path("payouts", views.payouts, name="settlements-payouts"),
    path("payouts.csv", views.payouts_csv, name="settlements-payouts-csv"),
    # planos
    path("plans", plan_api.plans_list, name="plans-list"),
    path("plans/conflicts", plan_api.plans_conflicts, name="plans-conflicts"),
    path("plans/create", plan_api.plan_create, name="plans-create"),
    path("plans/<int:plan_id>", plan_api.plan_detail, name="plans-detail"),
    path("plans/<int:plan_id>/update", plan_api.plan_update, name="plans-update"),
    path("plans/<int:plan_id>/clone", plan_api.plan_clone, name="plans-clone"),
    path("plans/<int:plan_id>/delete", plan_api.plan_delete, name="plans-delete"),
    path("plans/preview", plan_api.plan_preview, name="plans-preview"),
    # Financial System (Fase 6)
    path("financial/", views.financial_dashboard, name="financial-dashboard"),
    # Calendário / Feriados
    path("calendar/", holiday_views.holiday_list, name="holiday-list"),
    path("calendar/create/", holiday_views.holiday_create, name="holiday-create"),
    path("calendar/<int:holiday_id>/update/", holiday_views.holiday_update, name="holiday-update"),
    path("calendar/<int:holiday_id>/delete/", holiday_views.holiday_delete, name="holiday-delete"),
    path("calendar/import-preset/", holiday_views.holiday_import_preset, name="holiday-import-preset"),
    path("calendar/check/", holiday_views.holiday_check, name="holiday-check"),
    # Invoices
    path("invoices/", views.invoice_list, name="invoice-list"),
    path(
        "invoices/<int:invoice_id>/",
        views.invoice_detail,
        name="invoice-detail",
    ),
    path(
        "invoices/<int:invoice_id>/pdf/",
        views.invoice_download_pdf,
        name="invoice-pdf",
    ),
    # Importação Cainiao Billing (XLSX)
    path(
        "invoices/cainiao/upload/",
        views_cainiao_billing.cainiao_billing_upload,
        name="cainiao-billing-upload",
    ),
    path(
        "invoices/cainiao/<int:import_id>/",
        views_cainiao_billing.cainiao_billing_detail,
        name="cainiao-billing-detail",
    ),
    path(
        "invoices/cainiao/<int:import_id>/delete/",
        views_cainiao_billing.cainiao_billing_delete,
        name="cainiao-billing-delete",
    ),
    path(
        "invoices/cainiao/<int:import_id>/reresolve/",
        views_cainiao_billing.cainiao_billing_reresolve,
        name="cainiao-billing-reresolve",
    ),
    path(
        "invoices/cainiao/<int:import_id>/create-overrides/",
        views_cainiao_billing.cainiao_billing_create_overrides,
        name="cainiao-billing-create-overrides",
    ),
    path(
        "invoices/cainiao/<int:import_id>/claims/<int:line_id>/assign/",
        views_cainiao_billing.cainiao_billing_assign_claim,
        name="cainiao-billing-assign-claim",
    ),
    path(
        "invoices/cainiao/<int:import_id>/claims/bulk/",
        views_cainiao_billing.cainiao_billing_assign_claims_bulk,
        name="cainiao-billing-assign-claims-bulk",
    ),
    # Settlements (Liquidações de Motoristas — vista global de PFs)
    path("settlements/", views.settlement_list, name="settlement-list"),
    # Claims
    path("claims/", views.claim_list, name="claim-list"),
    path("claims/<int:claim_id>/", views.claim_detail, name="claim-detail"),

    # Pré-Faturas — Gestão / Backoffice
    path(
        "pre-invoices/",
        views.pre_invoice_admin_list,
        name="pre-invoice-admin-list",
    ),
    path(
        "pre-invoices/<int:pre_invoice_id>/status/",
        views.pre_invoice_change_status,
        name="pre-invoice-change-status",
    ),
    path(
        "pre-invoices/empresa-lancamento/<int:lancamento_id>/status/",
        views.empresa_lancamento_change_status,
        name="empresa-lancamento-change-status",
    ),
    path(
        "pre-invoices/bulk-status/",
        views.pre_invoice_bulk_status,
        name="pre-invoice-bulk-status",
    ),
    # Pré-Faturas de Motorista (API JSON)
    path(
        "pre-invoices/driver/<int:driver_id>/",
        views.driver_pre_invoices_api,
        name="pre-invoices-driver",
    ),
    path(
        "drivers/<int:driver_id>/fleet-invoice-lines/",
        views.driver_fleet_invoice_lines_api,
        name="driver-fleet-invoice-lines",
    ),
    # Relatório de entregas + preview de pré-fatura
    path(
        "drivers/<int:driver_id>/delivery-report/",
        views.driver_delivery_report,
        name="driver-delivery-report",
    ),
    # Transferências de atribuição (waybill ↔ driver)
    path(
        "drivers/<int:driver_id>/day-waybills/",
        views.driver_day_waybills,
        name="driver-day-waybills",
    ),
    path(
        "transfers/create/",
        views.waybill_transfer_create,
        name="waybill-transfer-create",
    ),
    path(
        "transfers/<int:override_id>/delete/",
        views.waybill_transfer_delete,
        name="waybill-transfer-delete",
    ),
    path(
        "drivers/dropdown/",
        views.drivers_dropdown,
        name="drivers-dropdown",
    ),
    # Overrides de preço por waybill
    path(
        "price-overrides/create/",
        views.package_price_override_create,
        name="price-override-create",
    ),
    path(
        "price-overrides/<int:override_id>/delete/",
        views.package_price_override_delete,
        name="price-override-delete",
    ),
    # Histórico completo de uma waybill (vida do pacote)
    path(
        "waybill/<str:waybill>/history/",
        views.waybill_history,
        name="waybill-history",
    ),
    # Pacotes Not Arrived
    path(
        "cainiao/not-arrived/",
        cainiao_views.cainiao_not_arrived,
        name="cainiao-not-arrived",
    ),
    path(
        "cainiao/not-arrived/xlsx/",
        cainiao_views.cainiao_not_arrived_xlsx,
        name="cainiao-not-arrived-xlsx",
    ),
    path(
        "cainiao/not-arrived/scan-xlsx/",
        cainiao_views.cainiao_not_arrived_scan_xlsx,
        name="cainiao-not-arrived-scan-xlsx",
    ),
    path(
        "cainiao/not-arrived/whatsapp-driver/",
        cainiao_views.cainiao_whatsapp_driver_stuck,
        name="cainiao-whatsapp-driver-stuck",
    ),
    path(
        "cainiao/not-arrived/bulk-resolve/",
        cainiao_views.waybill_bulk_resolve,
        name="waybill-bulk-resolve",
    ),
    path(
        "cainiao/forecast-orphans/",
        cainiao_views.cainiao_forecast_orphans,
        name="cainiao-forecast-orphans",
    ),
    path(
        "cainiao/resolutions/",
        cainiao_views.cainiao_resolutions_list,
        name="cainiao-resolutions-list",
    ),
    path(
        "cainiao/diagnose/<str:waybill>/",
        cainiao_views.cainiao_waybill_diagnose,
        name="cainiao-waybill-diagnose",
    ),
    # Camada 1 — Flags
    path(
        "cainiao/flags/",
        cainiao_views.waybill_flag_list,
        name="waybill-flag-list",
    ),
    path(
        "cainiao/flags/bulk/",
        cainiao_views.waybill_flag_bulk,
        name="waybill-flag-bulk",
    ),
    path(
        "waybill/<str:waybill>/flag/",
        cainiao_views.waybill_flag_get,
        name="waybill-flag-get",
    ),
    path(
        "waybill/<str:waybill>/flag/create/",
        cainiao_views.waybill_flag_create,
        name="waybill-flag-create",
    ),
    path(
        "waybill/<str:waybill>/flag/clear/",
        cainiao_views.waybill_flag_clear,
        name="waybill-flag-clear",
    ),
    # Camada 2 — Snapshots
    path(
        "cainiao/snapshots/",
        cainiao_views.cainiao_snapshot_list,
        name="cainiao-snapshot-list",
    ),
    path(
        "cainiao/snapshots/create/",
        cainiao_views.cainiao_snapshot_create,
        name="cainiao-snapshot-create",
    ),
    path(
        "cainiao/snapshots/diff/",
        cainiao_views.cainiao_snapshot_diff,
        name="cainiao-snapshot-diff",
    ),
    path(
        "cainiao/snapshots/<int:snapshot_id>/",
        cainiao_views.cainiao_snapshot_detail,
        name="cainiao-snapshot-detail",
    ),
    path(
        "cainiao/snapshots/<int:snapshot_id>/xlsx/",
        cainiao_views.cainiao_snapshot_xlsx,
        name="cainiao-snapshot-xlsx",
    ),
    path(
        "waybill/<str:waybill>/lifecycle/",
        cainiao_views.cainiao_waybill_lifecycle,
        name="cainiao-waybill-lifecycle",
    ),
    # Camada 3 — Priority settings
    path(
        "cainiao/priority-settings/",
        cainiao_views.priority_settings_get,
        name="cainiao-priority-settings-get",
    ),
    path(
        "cainiao/priority-settings/save/",
        cainiao_views.priority_settings_save,
        name="cainiao-priority-settings-save",
    ),
    # Página global de pacotes
    path(
        "packages/",
        cainiao_views.cainiao_packages_page,
        name="cainiao-packages-page",
    ),
    path(
        "cainiao/packages/search/",
        cainiao_views.cainiao_packages_search,
        name="cainiao-packages-search",
    ),
    # Tags
    path(
        "waybill/<str:waybill>/tags/",
        cainiao_views.waybill_tags_list,
        name="waybill-tags-list",
    ),
    path(
        "waybill/<str:waybill>/tags/add/",
        cainiao_views.waybill_tag_add,
        name="waybill-tag-add",
    ),
    path(
        "waybill/tags/<int:tag_id>/delete/",
        cainiao_views.waybill_tag_delete,
        name="waybill-tag-delete",
    ),
    # Watch
    path(
        "waybill/<str:waybill>/watch/",
        cainiao_views.waybill_watch_toggle,
        name="waybill-watch-toggle",
    ),
    path(
        "waybill/watch/list/",
        cainiao_views.waybill_watch_list,
        name="waybill-watch-list",
    ),
    # Saved filters
    path(
        "cainiao/saved-filters/",
        cainiao_views.saved_filters,
        name="cainiao-saved-filters",
    ),
    # Returns (devoluções)
    path(
        "cainiao/returns/",
        cainiao_views.waybill_return_list,
        name="cainiao-returns-list",
    ),
    path(
        "cainiao/returns/bulk/",
        cainiao_views.waybill_return_bulk,
        name="cainiao-returns-bulk",
    ),
    path(
        "waybill/<str:waybill>/return/",
        cainiao_views.waybill_return_get,
        name="waybill-return-get",
    ),
    path(
        "waybill/<str:waybill>/return/save/",
        cainiao_views.waybill_return_create,
        name="waybill-return-create",
    ),
    path(
        "waybill/<str:waybill>/return/delete/",
        cainiao_views.waybill_return_delete,
        name="waybill-return-delete",
    ),
    # Return batches
    path(
        "cainiao/return-batches/",
        cainiao_views.return_batch_list,
        name="cainiao-return-batches-list",
    ),
    path(
        "cainiao/return-batches/<int:batch_id>/xlsx/",
        cainiao_views.return_batch_xlsx,
        name="cainiao-return-batch-xlsx",
    ),
    path(
        "cainiao/hubs-with-counts/",
        cainiao_views.cainiao_hubs_with_counts,
        name="cainiao-hubs-with-counts",
    ),
    # PARCEL_LIST (formato rico — 105 cols)
    path(
        "cainiao/parcel-list/preview/",
        cainiao_views.cainiao_parcel_list_preview,
        name="cainiao-parcel-list-preview",
    ),
    path(
        "cainiao/parcel-list/import/",
        cainiao_views.cainiao_parcel_list_import,
        name="cainiao-parcel-list-import",
    ),
    # Auto-detecção do tipo de planilha
    path(
        "cainiao/detect-xlsx-type/",
        cainiao_views.cainiao_detect_xlsx_type,
        name="cainiao-detect-xlsx-type",
    ),
    # Resolução por waybill
    path(
        "waybill/<str:waybill>/resolve/",
        cainiao_views.waybill_resolve,
        name="waybill-resolve",
    ),
    path(
        "waybill/<str:waybill>/unresolve/",
        cainiao_views.waybill_unresolve,
        name="waybill-unresolve",
    ),
    path(
        "waybill/<str:waybill>/resolution/",
        cainiao_views.waybill_get_resolution,
        name="waybill-get-resolution",
    ),
    # Comments
    path(
        "waybill/<str:waybill>/comments/",
        cainiao_views.waybill_comments_list,
        name="waybill-comments-list",
    ),
    path(
        "waybill/<str:waybill>/comments/add/",
        cainiao_views.waybill_comments_add,
        name="waybill-comments-add",
    ),
    path(
        "waybill/comments/<int:comment_id>/delete/",
        cainiao_views.waybill_comments_delete,
        name="waybill-comments-delete",
    ),
    path(
        "drivers/<int:driver_id>/pre-invoice-preview/",
        views.driver_pre_invoice_preview,
        name="driver-pre-invoice-preview",
    ),
    path(
        "drivers/<int:driver_id>/yearly-heatmap/",
        views.driver_yearly_heatmap,
        name="driver-yearly-heatmap",
    ),
    path(
        "drivers/<int:driver_id>/account-statement/",
        views.driver_account_statement,
        name="driver-account-statement",
    ),
    # Lote de PFs por Frota (EmpresaParceira)
    path(
        "empresas/<int:empresa_id>/lote-preview/",
        views.empresa_lote_preview,
        name="empresa-lote-preview",
    ),
    path(
        "empresas/<int:empresa_id>/lote-emit/",
        views.empresa_lote_emit,
        name="empresa-lote-emit",
    ),
    path(
        "empresas/<int:empresa_id>/whatsapp-lote/",
        views.empresa_whatsapp_lote,
        name="empresa-whatsapp-lote",
    ),
    path(
        "empresas/<int:empresa_id>/dashboard-stats/",
        views.empresa_dashboard_stats,
        name="empresa-dashboard-stats",
    ),
    # FleetInvoice (Fase 6.2 refactor)
    path(
        "empresas/<int:empresa_id>/fleet-invoices/",
        views.empresa_fleet_invoices_list,
        name="empresa-fleet-invoices-list",
    ),
    path(
        "fleet-invoices/<int:fleet_invoice_id>/",
        views.empresa_fleet_invoice_detail,
        name="fleet-invoice-detail",
    ),
    path(
        "fleet-invoices/<int:fleet_invoice_id>/status/",
        views.empresa_fleet_invoice_change_status,
        name="fleet-invoice-change-status",
    ),
    path(
        "fleet-invoices/<int:fleet_invoice_id>/delete/",
        views.empresa_fleet_invoice_delete,
        name="fleet-invoice-delete",
    ),
    path(
        "fleet-invoices/<int:fleet_invoice_id>/pdf/",
        views.empresa_fleet_invoice_pdf,
        name="fleet-invoice-pdf",
    ),
    path(
        "pre-invoices/driver/<int:driver_id>/create/",
        views.driver_pre_invoice_create,
        name="pre-invoice-create",
    ),
    path(
        "pre-invoices/<int:pre_invoice_id>/update/",
        views.driver_pre_invoice_update,
        name="pre-invoice-update",
    ),
    path(
        "pre-invoices/<int:pre_invoice_id>/bonus/add/",
        views.pre_invoice_add_bonus,
        name="pre-invoice-bonus-add",
    ),
    path(
        "pre-invoices/bonus/<int:bonus_id>/delete/",
        views.pre_invoice_delete_bonus,
        name="pre-invoice-bonus-delete",
    ),
    path(
        "pre-invoices/<int:pre_invoice_id>/pacote-perdido/add/",
        views.pre_invoice_add_lost_package,
        name="pre-invoice-lost-add",
    ),
    path(
        "pre-invoices/pacote-perdido/<int:package_id>/delete/",
        views.pre_invoice_delete_lost_package,
        name="pre-invoice-lost-delete",
    ),
    path(
        "pre-invoices/<int:pre_invoice_id>/adiantamento/add/",
        views.pre_invoice_add_advance,
        name="pre-invoice-advance-add",
    ),
    path(
        "pre-invoices/adiantamento/<int:advance_id>/delete/",
        views.pre_invoice_delete_advance,
        name="pre-invoice-advance-delete",
    ),
    # Linhas de trabalho
    path(
        "pre-invoices/<int:pre_invoice_id>/linha/add/",
        views.pre_invoice_line_add,
        name="pre-invoice-linha-add",
    ),
    path(
        "pre-invoices/linha/<int:line_id>/update/",
        views.pre_invoice_line_update,
        name="pre-invoice-linha-update",
    ),
    path(
        "pre-invoices/linha/<int:line_id>/delete/",
        views.pre_invoice_line_delete,
        name="pre-invoice-linha-delete",
    ),
    path(
        "pre-invoices/<int:pre_invoice_id>/recalculate/",
        views.driver_pre_invoice_recalculate,
        name="pre-invoice-recalculate",
    ),
    path(
        "pre-invoices/<int:pre_invoice_id>/delete/",
        views.driver_pre_invoice_delete,
        name="pre-invoice-delete",
    ),
    path(
        "pre-invoices/<int:pre_invoice_id>/pdf/",
        views.driver_pre_invoice_pdf,
        name="pre-invoice-pdf",
    ),
    path(
        "pre-invoices/<int:pre_invoice_id>/upload-fatura/",
        views.pre_invoice_upload_fatura,
        name="pre-invoice-upload-fatura",
    ),
    path(
        "pre-invoices/<int:pre_invoice_id>/whatsapp/",
        views.pre_invoice_send_whatsapp,
        name="pre-invoice-send-whatsapp",
    ),
    # Importação de planilhas por parceiro
    path(
        "pre-invoices/import/<int:partner_id>/preview/",
        views.import_partner_sheet_preview,
        name="pre-invoice-import-preview",
    ),
    path(
        "pre-invoices/import/<int:partner_id>/",
        views.import_partner_sheet,
        name="pre-invoice-import",
    ),
    # Empresa Parceira Lançamento — detalhe / editar / PDF
    path(
        "pre-invoices/empresa-lancamento/<int:lancamento_id>/detail/",
        views.empresa_lancamento_detail_api,
        name="empresa-lancamento-detail",
    ),
    path(
        "pre-invoices/empresa-lancamento/<int:lancamento_id>/update/",
        views.empresa_lancamento_update,
        name="empresa-lancamento-update",
    ),
    path(
        "pre-invoices/empresa-lancamento/<int:lancamento_id>/pdf/",
        views.empresa_lancamento_pdf,
        name="empresa-lancamento-pdf",
    ),
    # Cainiao Import
    path(
        "cainiao/import/preview/",
        cainiao_views.cainiao_import_preview,
        name="cainiao-import-preview",
    ),
    path(
        "cainiao/import/confirm/",
        cainiao_views.cainiao_import_confirm,
        name="cainiao-import-confirm",
    ),
    path(
        "cainiao/driver/<int:driver_id>/helpers/",
        cainiao_views.cainiao_helpers_api,
        name="cainiao-helpers-api",
    ),
    path(
        "cainiao/drivers/",
        cainiao_views.cainiao_drivers_list,
        name="cainiao-drivers-list",
    ),
    path(
        "cainiao/link-driver/",
        cainiao_views.cainiao_link_driver,
        name="cainiao-link-driver",
    ),
    path(
        "cainiao/create-driver/",
        cainiao_views.cainiao_create_driver,
        name="cainiao-create-driver",
    ),
    path(
        "cainiao/import/forecast/preview/",
        cainiao_views.cainiao_import_forecast_preview,
        name="cainiao-import-forecast-preview",
    ),
    path(
        "cainiao/import/forecast/",
        cainiao_views.cainiao_import_forecast,
        name="cainiao-import-forecast",
    ),
    # Forecast CP4 API (modal de previsão)
    path(
        "cainiao/forecast/cp4/",
        cainiao_views.cainiao_forecast_cp4,
        name="cainiao-forecast-cp4",
    ),
    # Forecast Manual (sem ficheiro)
    path(
        "cainiao/forecast/manual/",
        cainiao_views.cainiao_manual_forecast_list,
        name="cainiao-manual-forecast-list",
    ),
    path(
        "cainiao/forecast/manual/save/",
        cainiao_views.cainiao_manual_forecast_save,
        name="cainiao-manual-forecast-save",
    ),
    path(
        "cainiao/forecast/manual/<int:manual_id>/delete/",
        cainiao_views.cainiao_manual_forecast_delete,
        name="cainiao-manual-forecast-delete",
    ),
    path(
        "cainiao/forecast/reset/",
        cainiao_views.cainiao_forecast_reset,
        name="cainiao-forecast-reset",
    ),
    path(
        "cainiao/forecast/pdf/",
        cainiao_views.cainiao_forecast_pdf,
        name="cainiao-forecast-pdf",
    ),
    path(
        "cainiao/forecast/excel/",
        cainiao_views.cainiao_forecast_excel,
        name="cainiao-forecast-excel",
    ),
    # Planilha Forecast nova (Parcel ID)
    path(
        "cainiao/planning/preview/",
        cainiao_views.cainiao_planning_preview,
        name="cainiao-planning-preview",
    ),
    path(
        "cainiao/planning/import/",
        cainiao_views.cainiao_planning_import,
        name="cainiao-planning-import",
    ),
    # Planilha Operation Update
    path(
        "cainiao/operation/preview/",
        cainiao_views.cainiao_operation_preview,
        name="cainiao-operation-preview",
    ),
    path(
        "cainiao/operation/import/",
        cainiao_views.cainiao_operation_import,
        name="cainiao-operation-import",
    ),
    path(
        "cainiao/operation/audit/",
        cainiao_views.cainiao_operation_audit,
        name="cainiao-operation-audit",
    ),
    # Planilha Driver Statistic
    path(
        "cainiao/driver-stat/preview/",
        cainiao_views.cainiao_driver_stat_preview,
        name="cainiao-driver-stat-preview",
    ),
    path(
        "cainiao/driver-stat/import/",
        cainiao_views.cainiao_driver_stat_import,
        name="cainiao-driver-stat-import",
    ),
    path(
        "cainiao/driver-stat/guided-import/",
        cainiao_views.cainiao_driver_stat_guided_import,
        name="cainiao-driver-stat-guided-import",
    ),
    path(
        "cainiao/courier-backfill/status/",
        cainiao_views.cainiao_courier_backfill_status,
        name="cainiao-courier-backfill-status",
    ),
    path(
        "cainiao/courier-backfill/",
        cainiao_views.cainiao_courier_backfill,
        name="cainiao-courier-backfill",
    ),
    path(
        "cainiao/cleanup-stale/",
        cainiao_views.cainiao_cleanup_stale_rows_view,
        name="cainiao-cleanup-stale",
    ),
    path(
        "cainiao/mark-stale-armazem/",
        cainiao_views.cainiao_mark_stale_armazem_view,
        name="cainiao-mark-stale-armazem",
    ),
    path(
        "cainiao/roll-forward/",
        cainiao_views.cainiao_roll_forward_view,
        name="cainiao-roll-forward",
    ),
    path(
        "cainiao/consolidate-waybills/",
        cainiao_views.cainiao_consolidate_waybills_view,
        name="cainiao-consolidate-waybills",
    ),
    path(
        "cainiao/dedup-signatures/",
        cainiao_views.cainiao_dedup_signatures_view,
        name="cainiao-dedup-signatures",
    ),
    path(
        "cainiao/debug-headers/",
        cainiao_views.cainiao_debug_headers_view,
        name="cainiao-debug-headers",
    ),
    path(
        "cainiao/mark-deliveries-courier-id/",
        cainiao_views.cainiao_mark_deliveries_courier_id,
        name="cainiao-mark-deliveries-courier-id",
    ),
    path(
        "cainiao/existing-logins/",
        cainiao_views.cainiao_existing_logins,
        name="cainiao-existing-logins",
    ),
    # Planilha Driver Detail Info
    path(
        "cainiao/driver-detail/preview/",
        cainiao_views.cainiao_driver_detail_preview,
        name="cainiao-driver-detail-preview",
    ),
    path(
        "cainiao/driver-detail/import/",
        cainiao_views.cainiao_driver_detail_import,
        name="cainiao-driver-detail-import",
    ),
    # Relatório / PDF de resumo de pagamentos
    path(
        "pre-invoices/report/summary/",
        views.pre_invoice_report_summary,
        name="pre-invoice-report-summary",
    ),
    path(
        "pre-invoices/report/pdf/",
        views.pre_invoice_report_pdf,
        name="pre-invoice-report-pdf",
    ),
    # HUBs Cainiao
    path("cainiao/hubs/", cainiao_views.cainiao_hubs_list, name="cainiao-hubs-list"),
    path("cainiao/hubs/create/", cainiao_views.cainiao_hub_create, name="cainiao-hub-create"),
    path("cainiao/hubs/<int:hub_id>/update/", cainiao_views.cainiao_hub_update, name="cainiao-hub-update"),
    path("cainiao/hubs/<int:hub_id>/delete/", cainiao_views.cainiao_hub_delete, name="cainiao-hub-delete"),
    path("cainiao/hubs/<int:hub_id>/cp4/add/", cainiao_views.cainiao_hub_cp4_add, name="cainiao-hub-cp4-add"),
    path("cainiao/hubs/<int:hub_id>/cp4/remove/", cainiao_views.cainiao_hub_cp4_remove, name="cainiao-hub-cp4-remove"),

    # Drill-down: drivers / packages / waybill
    path(
        "cainiao/drivers-by-status/",
        cainiao_views.cainiao_drivers_by_status,
        name="cainiao-drivers-by-status",
    ),
    path(
        "cainiao/driver-packages/",
        cainiao_views.cainiao_driver_packages,
        name="cainiao-driver-packages",
    ),
    path(
        "cainiao/waybill/<str:waybill>/",
        cainiao_views.cainiao_waybill_detail,
        name="cainiao-waybill-detail",
    ),
    path(
        "cainiao/waybill-search/",
        cainiao_views.cainiao_waybill_search,
        name="cainiao-waybill-search",
    ),

    # Mapa de entregas
    path(
        "cainiao/map/",
        cainiao_views.cainiao_map_view,
        name="cainiao-map",
    ),
    path(
        "cainiao/map-pins/",
        cainiao_views.cainiao_map_pins,
        name="cainiao-map-pins",
    ),
    path(
        "cainiao/map-overlays/",
        cainiao_views.cainiao_map_overlays,
        name="cainiao-map-overlays",
    ),
    path(
        "cainiao/map-missing-coords/",
        cainiao_views.cainiao_map_missing_coords,
        name="cainiao-map-missing-coords",
    ),
    path(
        "cainiao/map/compare/",
        cainiao_views.cainiao_map_compare,
        name="cainiao-map-compare",
    ),
    # ── Forecast Plan (Kanban driver-centric) ────────────────────────
    path(
        "forecast-plan/",
        forecast_plan_views.forecast_plan_get_or_create,
        name="forecast-plan-get-or-create",
    ),
    path(
        "forecast-plan/<int:plan_id>/assign/",
        forecast_plan_views.forecast_plan_assign,
        name="forecast-plan-assign",
    ),
    path(
        "forecast-plan/assignment/<int:assignment_id>/delete/",
        forecast_plan_views.forecast_plan_delete_assignment,
        name="forecast-plan-delete-assignment",
    ),
    path(
        "forecast-plan/<int:plan_id>/clear/",
        forecast_plan_views.forecast_plan_clear,
        name="forecast-plan-clear",
    ),
    path(
        "forecast-plan/<int:plan_id>/auto-distribute/",
        forecast_plan_views.forecast_plan_auto_distribute,
        name="forecast-plan-auto-distribute",
    ),
    path(
        "forecast-plan/<int:plan_id>/toggle-skip/",
        forecast_plan_views.forecast_plan_toggle_skip,
        name="forecast-plan-toggle-skip",
    ),
    path(
        "forecast-plan/<int:plan_id>/publish/",
        forecast_plan_views.forecast_plan_publish,
        name="forecast-plan-publish",
    ),
    path(
        "forecast-plan/<int:plan_id>/unpublish/",
        forecast_plan_views.forecast_plan_unpublish,
        name="forecast-plan-unpublish",
    ),
    path(
        "forecast-plan/<int:plan_id>/clone-to/",
        forecast_plan_views.forecast_plan_clone_to,
        name="forecast-plan-clone-to",
    ),
    path(
        "forecast-plan/history/",
        forecast_plan_views.forecast_plan_history,
        name="forecast-plan-history",
    ),
    path(
        "drivers/<int:driver_id>/set-capacity/",
        forecast_plan_views.driver_set_capacity,
        name="driver-set-capacity",
    ),

    # ── Conta-Corrente do Motorista (Lançamentos / Adiantamentos) ────
    path(
        "adiantamentos/",
        views_cash_entries.cash_entries_dashboard,
        name="cash-entries-dashboard",
    ),
    path(
        "cash-entries/list/",
        views_cash_entries.cash_entry_list,
        name="cash-entry-list",
    ),
    path(
        "cash-entries/create/",
        views_cash_entries.cash_entry_create,
        name="cash-entry-create",
    ),
    path(
        "cash-entries/bulk-create/",
        views_cash_entries.cash_entry_bulk_create,
        name="cash-entry-bulk-create",
    ),
    path(
        "cash-entries/<int:entry_id>/update/",
        views_cash_entries.cash_entry_update,
        name="cash-entry-update",
    ),
    path(
        "cash-entries/<int:entry_id>/cancel/",
        views_cash_entries.cash_entry_cancel,
        name="cash-entry-cancel",
    ),
    path(
        "pre-invoices/<int:pre_invoice_id>/pending-entries/",
        views_cash_entries.pre_invoice_pending_entries,
        name="pre-invoice-pending-entries",
    ),
    path(
        "pre-invoices/<int:pre_invoice_id>/attach-entries/",
        views_cash_entries.pre_invoice_attach_entries,
        name="pre-invoice-attach-entries",
    ),

    # ── Sócios e Reembolsos a Terceiros ───────────────────────────────
    path(
        "socios/",
        views_shareholder.shareholder_dashboard,
        name="shareholder-dashboard",
    ),
    path(
        "socios/list/",
        views_shareholder.shareholder_list_api,
        name="shareholder-list",
    ),
    path(
        "socios/create/",
        views_shareholder.shareholder_create,
        name="shareholder-create",
    ),
    path(
        "socios/<int:shareholder_id>/update/",
        views_shareholder.shareholder_update,
        name="shareholder-update",
    ),
    path(
        "socios/<int:shareholder_id>/delete/",
        views_shareholder.shareholder_delete,
        name="shareholder-delete",
    ),
    path(
        "reembolsos/",
        views_shareholder.reimbursement_list_api,
        name="reimbursement-list",
    ),
    path(
        "reembolsos/create/",
        views_shareholder.reimbursement_create,
        name="reimbursement-create",
    ),
    path(
        "reembolsos/<int:reimbursement_id>/mark-paid/",
        views_shareholder.reimbursement_mark_paid,
        name="reimbursement-mark-paid",
    ),
    path(
        "reembolsos/<int:reimbursement_id>/cancel/",
        views_shareholder.reimbursement_cancel,
        name="reimbursement-cancel",
    ),
    path(
        "reembolsos/bulk-mark-paid/",
        views_shareholder.reimbursement_bulk_mark_paid,
        name="reimbursement-bulk-mark-paid",
    ),
]
