# Generated by Django 5.2.2 on 2025-06-06 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('vehicle', models.CharField(max_length=50)),
                ('vehicle_norm', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, unique=True)),
                ('order_id', models.CharField(db_index=True, max_length=50)),
                ('order_type', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=50)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('cod', models.CharField(blank=True, max_length=50, null=True)),
                ('packages_count', models.IntegerField()),
                ('packages_barcode', models.CharField(max_length=255)),
                ('retailer', models.CharField(db_index=True, max_length=100)),
                ('retailer_order_number', models.CharField(max_length=100)),
                ('retailer_sales_number', models.CharField(max_length=100)),
                ('client_address', models.CharField(max_length=255)),
                ('client_address_text', models.TextField()),
                ('client_phone', models.CharField(max_length=50)),
                ('client_email', models.EmailField(max_length=254)),
                ('intended_delivery_date', models.DateField(db_index=True)),
                ('actual_delivery_date', models.DateField(blank=True, db_index=True, null=True)),
                ('delivery_timeslot', models.CharField(max_length=50)),
                ('simplified_order_status', models.CharField(db_index=True, max_length=50)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_failed', models.BooleanField(default=False)),
                ('delivery_date_only', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-intended_delivery_date', 'order_id'],
                'indexes': [models.Index(fields=['status', 'intended_delivery_date'], name='ordersmanag_status_347256_idx'), models.Index(fields=['retailer', 'intended_delivery_date'], name='ordersmanag_retaile_3bbc0a_idx'), models.Index(fields=['simplified_order_status', 'actual_delivery_date'], name='ordersmanag_simplif_f8d053_idx'), models.Index(fields=['is_delivered', 'actual_delivery_date'], name='ordersmanag_is_deli_8d4922_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet', models.CharField(max_length=100)),
                ('dc', models.CharField(max_length=100)),
                ('driver_route_stop', models.IntegerField()),
                ('dispatch_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recovered', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordersmanager_paack.driver')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='ordersmanager_paack.order')),
            ],
            options={
                'indexes': [models.Index(fields=['driver', 'dispatch_time'], name='ordersmanag_driver__f574c7_idx'), models.Index(fields=['fleet', 'dispatch_time'], name='ordersmanag_fleet_a4c9b2_idx'), models.Index(fields=['dc', 'dispatch_time'], name='ordersmanag_dc_720de6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField()),
                ('success', models.BooleanField()),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersmanager_paack.order')),
            ],
            options={
                'ordering': ['order', 'attempt_number'],
                'indexes': [models.Index(fields=['order', 'attempt_number'], name='ordersmanag_order_i_74182a_idx'), models.Index(fields=['success', 'time'], name='ordersmanag_success_ff6412_idx')],
                'unique_together': {('order', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ordersmanager_paack.order')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['order', 'timestamp'], name='ordersmanag_order_i_552f20_idx'), models.Index(fields=['status', 'timestamp'], name='ordersmanag_status_46a721_idx')],
            },
        ),
    ]
