# Generated by Django 4.2.22 on 2025-09-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersmanager_paack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_address',
            field=models.TextField(),
        ),
    ]
