# Generated by Django 4.2.22 on 2026-06-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_incidences_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incidencepacket',
            new_name='app_api_inc_driver__d6ca9d_idx',
            old_name='app_api_inc_driver__050f89_idx',
        ),
        migrations.RenameIndex(
            model_name='incidencepacket',
            new_name='app_api_inc_zone_6abf19_idx',
            old_name='app_api_inc_zone_30f1c0_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrcorrectionlearning',
            new_name='app_api_ocr_field_n_b68855_idx',
            old_name='app_api_ocr_field_n_f8f23f_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrcorrectionlearning',
            new_name='app_api_ocr_field_n_89d69a_idx',
            old_name='app_api_ocr_field_n_3117c0_idx',
        ),
        migrations.AlterField(
            model_name='driverapptoken',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultimo uso'),
        ),
    ]
