# Generated by Django 4.2.22 on 2026-05-13 23:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0012_bill_irs_retention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('nif', models.CharField(blank=True, help_text='Número de Identificação Fiscal (9 dígitos PT).', max_length=20, verbose_name='NIF')),
                ('niss', models.CharField(blank=True, help_text='Número de Identificação da Segurança Social.', max_length=20, verbose_name='NISS')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('contrato_tipo', models.CharField(choices=[('SEM_TERMO', 'Contrato Sem Termo (efectivo)'), ('TERMO_CERTO', 'Contrato a Termo Certo'), ('TERMO_INCERTO', 'Contrato a Termo Incerto'), ('PART_TIME', 'Part-Time'), ('ESTAGIO', 'Estágio (IEFP / profissional)')], default='SEM_TERMO', max_length=20, verbose_name='Tipo de Contrato')),
                ('part_time_pct', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='100 = full-time. 50 = meio horário, etc.', max_digits=5, verbose_name='% do tempo (part-time)')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('data_saida', models.DateField(blank=True, help_text='Vazio = ainda activo.', null=True, verbose_name='Data de Saída')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('vencimento_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vencimento Base (€/mês)')),
                ('diuturnidades', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Diuturnidades (€/mês)')),
                ('subs_alimentacao_dia', models.DecimalField(decimal_places=2, default=Decimal('9.60'), help_text='Valor por dia útil. 2026: até €6.00 dinheiro ou €9.60 cartão isento de IRS/SS. Acima do limite tributado.', max_digits=6, verbose_name='Sub. Alimentação (€/dia)')),
                ('dias_uteis_mes_default', models.PositiveSmallIntegerField(default=22, help_text='Para cálculo do subsídio de alimentação.', verbose_name='Dias úteis/mês (default)')),
                ('irs_tabela', models.PositiveSmallIntegerField(default=1, help_text='1: Não casado 0 dep | 2: Não casado 1+ dep | 3: Casado 2 tit 0 dep | 4: Casado 2 tit 1+ dep | 5: Casado 1 tit 0 dep | 6: Casado 1 tit 1+ dep | 7: Não casado deficiente | 8: Casado 2 tit defic | 9: Casado 1 tit defic', verbose_name='Tabela IRS')),
                ('dependentes_irs', models.PositiveSmallIntegerField(default=0, verbose_name='Nº Dependentes')),
                ('subsidios_mode', models.CharField(choices=[('DUODECIMOS', 'Duodécimos (1/12 mensal)'), ('LUMP_SUM', 'Lump-sum (Jun/Dez)')], default='DUODECIMOS', max_length=20, verbose_name='Modalidade subs. Natal/Férias')),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_center', models.ForeignKey(blank=True, help_text='Centro de custo onde imputar o custo salarial.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter', verbose_name='Centro de Custo')),
                ('fornecedor', models.OneToOneField(blank=True, help_text='Espelho como Fornecedor — usado nas Bills do salário.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='accounting.fornecedor')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['-ativo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_ano', models.PositiveSmallIntegerField(db_index=True)),
                ('periodo_mes', models.PositiveSmallIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADO', 'Aprovado'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], db_index=True, default='RASCUNHO', max_length=15, verbose_name='Estado')),
                ('total_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_descontos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_liquido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tsu_empregador', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='TSU Empregador (23.75%)')),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_espelho', models.OneToOneField(blank=True, help_text='Bill criada ao marcar PAGO (entra no DRE).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_origem', to='accounting.bill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='payroll.employee')),
                ('irs_imposto', models.OneToOneField(blank=True, help_text='Imposto IRS retido (AT) criado ao APROVAR.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_irs', to='accounting.imposto')),
                ('tsu_imposto', models.OneToOneField(blank=True, help_text='Imposto SS 23.75% criado ao APROVAR.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_tsu', to='accounting.imposto')),
            ],
            options={
                'verbose_name': 'Folha de Pagamento',
                'verbose_name_plural': 'Folhas de Pagamento',
                'ordering': ['-periodo_ano', '-periodo_mes', 'employee__nome'],
            },
        ),
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENCIMENTO_BASE', 'Vencimento Base'), ('DIUTURNIDADE', 'Diuturnidade'), ('SUB_REFEICAO', 'Subsídio de Alimentação'), ('SUB_NATAL', 'Subsídio de Natal'), ('SUB_FERIAS', 'Subsídio de Férias'), ('HORA_EXTRA', 'Horas Extra'), ('PREMIO', 'Prémio / Comissão'), ('TRAB_NOTURNO', 'Trabalho Nocturno'), ('OUTRO_BRUTO', 'Outro (bruto)'), ('IRS_RETENCAO', 'IRS — Retenção na Fonte'), ('SS_EMPREGADO', 'Seg. Social Empregado (11%)'), ('FALTA', 'Falta / Atraso'), ('PENHORA', 'Penhora Judicial'), ('OUTRO_DESCONTO', 'Outro (desconto)')], db_index=True, max_length=30, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Sempre positivo. O sinal vem do tipo (bruto vs desconto).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor (€)')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Para horas extra (h), faltas (dias), sub. refeição (dias).', max_digits=8, verbose_name='Quantidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='payroll.payroll')),
            ],
            options={
                'verbose_name': 'Componente da Folha',
                'verbose_name_plural': 'Componentes da Folha',
                'ordering': ['tipo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IRSTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(db_index=True)),
                ('tabela_id', models.PositiveSmallIntegerField(help_text='1-9 (ver Employee.irs_tabela)')),
                ('nome', models.CharField(blank=True, help_text="Ex: 'Tabela I — Não casado, sem dependentes'", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tabela IRS',
                'verbose_name_plural': 'Tabelas IRS',
                'ordering': ['-ano', 'tabela_id'],
                'unique_together': {('ano', 'tabela_id')},
            },
        ),
        migrations.CreateModel(
            name='IRSEscalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_superior', models.DecimalField(decimal_places=2, help_text='Rendimento mensal até este valor entra neste escalão.', max_digits=10, verbose_name='Limite superior (€)')),
                ('taxa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Taxa (%)')),
                ('parcela_abater', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Por dependente (se aplicável). Default 0 para MVP.', max_digits=10, verbose_name='Parcela a abater (€)')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escaloes', to='payroll.irstable')),
            ],
            options={
                'verbose_name': 'Escalão IRS',
                'verbose_name_plural': 'Escalões IRS',
                'ordering': ['tabela', 'limite_superior'],
            },
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['-periodo_ano', '-periodo_mes'], name='payroll_pay_periodo_e3cee5_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='payroll_pay_status_465a76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'periodo_ano', 'periodo_mes')},
        ),
    ]
