# Generated by Django 4.2.22 on 2026-02-27 16:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.CharField(db_index=True, help_text='Tracking code ou ID externo do parceiro', max_length=200, verbose_name='Referência Externa')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='Nome do Destinatário')),
                ('recipient_address', models.TextField(verbose_name='Morada de Entrega')),
                ('postal_code', models.CharField(db_index=True, help_text='Formato: XXXX-XXX', max_length=8, validators=[django.core.validators.RegexValidator(message='Código postal deve estar no formato XXXX-XXX', regex='^\\d{4}-\\d{3}$')], verbose_name='Código Postal')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Destinatário')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Email do Destinatário')),
                ('declared_value', models.DecimalField(decimal_places=2, default=0, help_text='Valor declarado do conteúdo em €', max_digits=10, verbose_name='Valor Declarado')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='Dimensões da encomenda (length, width, height em cm)', verbose_name='Dimensões')),
                ('scheduled_delivery', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de Entrega Agendada')),
                ('delivery_window_start', models.TimeField(blank=True, null=True, verbose_name='Início da Janela de Entrega')),
                ('delivery_window_end', models.TimeField(blank=True, null=True, verbose_name='Fim da Janela de Entrega')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Atribuído em')),
                ('current_status', models.CharField(choices=[('PENDING', 'Pendente'), ('ASSIGNED', 'Atribuído a Motorista'), ('IN_TRANSIT', 'Em Trânsito'), ('DELIVERED', 'Entregue'), ('RETURNED', 'Devolvido'), ('INCIDENT', 'Incidente'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', max_length=20, verbose_name='Status Atual')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('delivery_proof', models.JSONField(blank=True, default=dict, help_text='Assinatura, foto, código de confirmação, etc.', verbose_name='Prova de Entrega')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('special_instructions', models.TextField(blank=True, help_text='Instruções específicas do destinatário (código porta, andar, etc.)', verbose_name='Instruções Especiais')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='drivers_app.driverprofile', verbose_name='Motorista Atribuído')),
                ('partner', models.ForeignKey(help_text='Parceiro logístico de origem do pedido', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.partner', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ASSIGNED', 'Atribuído a Motorista'), ('IN_TRANSIT', 'Em Trânsito'), ('DELIVERED', 'Entregue'), ('RETURNED', 'Devolvido'), ('INCIDENT', 'Incidente'), ('CANCELLED', 'Cancelado')], max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('location', models.CharField(blank=True, help_text='GPS ou descrição da localização quando mudança ocorreu', max_length=200, verbose_name='Localização')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora da Mudança')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders_manager.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['order', '-changed_at'], name='orders_mana_order_i_5d0365_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('DAMAGED', 'Encomenda Danificada'), ('LOST', 'Encomenda Extraviada'), ('WRONG_ADDRESS', 'Morada Errada'), ('RECIPIENT_ABSENT', 'Destinatário Ausente'), ('REFUSED', 'Recusado pelo Destinatário'), ('DELAYED', 'Atraso na Entrega'), ('OTHER', 'Outro')], max_length=20, verbose_name='Tipo de Incidente')),
                ('description', models.TextField(verbose_name='Descrição do Incidente')),
                ('driver_responsible', models.BooleanField(default=False, help_text='Se marcado, incidente foi causado por erro do motorista', verbose_name='Motorista Responsável')),
                ('claim_amount', models.DecimalField(decimal_places=2, default=0, help_text='Valor a ser deduzido do settlement do motorista (se responsável)', max_digits=10, verbose_name='Valor da Reclamação')),
                ('photos', models.JSONField(blank=True, default=list, help_text='URLs de fotos do incidente', verbose_name='Fotos')),
                ('resolved', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de Resolução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='orders_manager.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Incidente de Pedido',
                'verbose_name_plural': 'Incidentes de Pedidos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='orders_mana_order_i_ba5eac_idx'), models.Index(fields=['resolved', '-created_at'], name='orders_mana_resolve_57c143_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['partner', 'current_status'], name='orders_mana_partner_8f5ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assigned_driver', 'current_status'], name='orders_mana_assigne_37d852_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['scheduled_delivery', 'current_status'], name='orders_mana_schedul_af3f07_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['postal_code', 'current_status'], name='orders_mana_postal__661473_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['external_reference', 'partner'], name='orders_mana_externa_138f19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('partner', 'external_reference')},
        ),
    ]
