# Generated by Django 4.2.22 on 2026-03-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Endereço Original')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('locality', models.CharField(max_length=200, verbose_name='Localidade')),
                ('normalized_address', models.TextField(db_index=True, verbose_name='Endereço Normalizado')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('geocode_quality', models.CharField(choices=[('EXACT', 'Endereço Exato'), ('STREET', 'Rua'), ('POSTAL_CODE', 'Código Postal'), ('LOCALITY', 'Localidade'), ('FAILED', 'Falhou')], default='FAILED', max_length=20, verbose_name='Qualidade')),
                ('geocoded_at', models.DateTimeField(auto_now_add=True, verbose_name='Geocodificado em')),
                ('geocode_source', models.CharField(default='Nominatim', max_length=50, verbose_name='Fonte')),
            ],
            options={
                'verbose_name': 'Endereço Geocodificado',
                'verbose_name_plural': 'Endereços Geocodificados',
                'indexes': [models.Index(fields=['normalized_address'], name='orders_mana_normali_fd2373_idx'), models.Index(fields=['postal_code', 'locality'], name='orders_mana_postal__fc3e8e_idx')],
                'unique_together': {('normalized_address',)},
            },
        ),
    ]
