# Generated by Django 4.2.22 on 2026-03-01 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders_manager', '0002_geocodedaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocodedaddress',
            name='geocode_quality',
            field=models.CharField(choices=[('EXACT', 'Endereço Exato'), ('STREET', 'Rua'), ('POSTAL_CODE', 'Código Postal'), ('LOCALITY', 'Localidade'), ('MANUAL', 'Manual'), ('FAILED', 'Falhou')], default='FAILED', max_length=20, verbose_name='Qualidade'),
        ),
        migrations.CreateModel(
            name='GeocodingFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_address', models.TextField(verbose_name='Endereço Original')),
                ('normalized_address', models.TextField(verbose_name='Endereço Normalizado')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Código Postal')),
                ('locality', models.CharField(blank=True, max_length=100, verbose_name='Localidade')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Motivo da Falha')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Tentativa em')),
                ('retry_count', models.IntegerField(default=1, verbose_name='Tentativas')),
                ('last_retry_at', models.DateTimeField(auto_now=True, verbose_name='Última Tentativa')),
                ('resolved', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('manual_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude Manual')),
                ('manual_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude Manual')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geocoding_failures', to='orders_manager.order', verbose_name='Pedido')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por')),
            ],
            options={
                'verbose_name': 'Falha de Geocodificação',
                'verbose_name_plural': 'Falhas de Geocodificação',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['resolved', 'attempted_at'], name='orders_mana_resolve_645774_idx'), models.Index(fields=['postal_code'], name='orders_mana_postal__5a9e0a_idx')],
            },
        ),
    ]
