# Generated by Django 4.2.22 on 2025-09-07 15:39
# Esvaziada ao remover a Paack (29/09/2026): criava só SettlementRun,
# CompensationPlan, PerPackageRate e ThresholdBonus, ligados ao Driver da
# Paack. As tabelas antigas são apagadas em 0055_remover_paack.

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = []
