# Generated by Django 4.2.22 on 2025-09-07 15:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordersmanager_paack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('area_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('base_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comp_plans', to='ordersmanager_paack.driver')),
            ],
        ),
        migrations.CreateModel(
            name='ThresholdBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ONCE', 'Uma vez'), ('EACH_STEP', 'A cada passo')], default='EACH_STEP', max_length=16)),
                ('start_at', models.PositiveIntegerField()),
                ('step', models.PositiveIntegerField(default=0, help_text='Usado em EACH_STEP (ex.: 100)')),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='settlements.compensationplan')),
            ],
        ),
        migrations.CreateModel(
            name='PerPackageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_delivered', models.PositiveIntegerField(default=0)),
                ('max_delivered', models.PositiveIntegerField(blank=True, null=True)),
                ('rate_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('progressive', models.BooleanField(default=False, help_text='Se marcado, calcula progressivo por faixas')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkg_rates', to='settlements.compensationplan')),
            ],
            options={
                'ordering': ['priority', 'min_delivered'],
            },
        ),
        migrations.CreateModel(
            name='SettlementRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(db_index=True)),
                ('client', models.CharField(db_index=True, max_length=80)),
                ('area_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('qtd_saida', models.PositiveIntegerField()),
                ('qtd_pact', models.PositiveIntegerField()),
                ('qtd_entregue', models.PositiveIntegerField()),
                ('vl_pct', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_pct', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasoleo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('desconto_tickets', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rec_liq_tickets', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vl_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_runs', to='ordersmanager_paack.driver')),
            ],
            options={
                'ordering': ['-run_date', 'driver__name'],
                'indexes': [models.Index(fields=['run_date', 'client'], name='settlements_run_dat_417e73_idx'), models.Index(fields=['driver', 'run_date'], name='settlements_driver__47818d_idx')],
                'unique_together': {('driver', 'run_date', 'client', 'area_code')},
            },
        ),
        migrations.AddIndex(
            model_name='compensationplan',
            index=models.Index(fields=['driver', 'client', 'area_code', 'starts_on', 'ends_on'], name='settlements_driver__de9449_idx'),
        ),
    ]
