# Generated by Django 4.2.22 on 2026-02-27 19:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders_manager', '0001_initial'),
        ('core', '0001_initial'),
        ('drivers_app', '0001_initial'),
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal')], default='WEEKLY', max_length=20, verbose_name='Tipo de Período')),
                ('week_number', models.PositiveIntegerField(blank=True, help_text='Semana do ano (1-52)', null=True, verbose_name='Número da Semana')),
                ('month_number', models.PositiveIntegerField(blank=True, help_text='Mês do ano (1-12)', null=True, verbose_name='Mês')),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='Ano')),
                ('period_start', models.DateField(db_index=True, verbose_name='Início do Período')),
                ('period_end', models.DateField(db_index=True, verbose_name='Fim do Período')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total de Pedidos')),
                ('delivered_orders', models.PositiveIntegerField(default=0, verbose_name='Pedidos Entregues')),
                ('failed_orders', models.PositiveIntegerField(default=0, verbose_name='Pedidos Falhados')),
                ('success_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de entregas com sucesso', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa de Sucesso')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total antes de descontos', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Bruto')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bônus por performance', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bônus')),
                ('fuel_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desconto Combustível')),
                ('claims_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Multas, perdas, danos', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descontos (Claims)')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Outros Descontos')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor final a pagar', max_digits=12, verbose_name='Valor Líquido')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('CALCULATED', 'Calculado'), ('APPROVED', 'Aprovado'), ('PAID', 'Pago'), ('DISPUTED', 'Em Disputa')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Calculado em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('payment_reference', models.CharField(blank=True, help_text='MB WAY, Transferência, etc.', max_length=200, verbose_name='Referência de Pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='settlements/pdfs/%Y/%m/', verbose_name='PDF do Extrato')),
                ('whatsapp_sent', models.BooleanField(default=False, verbose_name='WhatsApp Enviado')),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='WhatsApp Enviado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_settlements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settlements', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='drivers_app.driverprofile', verbose_name='Motorista')),
                ('partner', models.ForeignKey(blank=True, help_text='Se null, é um settlement consolidado multi-partner', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_settlements', to='core.partner', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Acerto de Motorista',
                'verbose_name_plural': 'Acertos de Motoristas',
                'ordering': ['-year', '-week_number', '-month_number', 'driver__nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='DriverClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('ORDER_LOSS', 'Perda de Pedido'), ('ORDER_DAMAGE', 'Dano em Pedido'), ('VEHICLE_FINE', 'Multa de Veículo'), ('VEHICLE_DAMAGE', 'Dano em Veículo'), ('FUEL_EXCESS', 'Excesso de Combustível'), ('MISSING_POD', 'Falta de Comprovante'), ('LATE_DELIVERY', 'Entrega Atrasada'), ('CUSTOMER_COMPLAINT', 'Reclamação de Cliente'), ('OTHER', 'Outro')], db_index=True, max_length=30, verbose_name='Tipo de Desconto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('description', models.TextField(help_text='Detalhes do motivo do desconto', verbose_name='Descrição')),
                ('evidence_file', models.FileField(blank=True, help_text='Foto, documento, etc.', null=True, upload_to='claims/evidence/%Y/%m/', verbose_name='Evidência')),
                ('justification', models.TextField(blank=True, help_text='Justificativa ou recurso do motorista', verbose_name='Justificativa')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('APPEALED', 'Em Recurso')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ocorrido em')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisado em')),
                ('review_notes', models.TextField(blank=True, verbose_name='Notas da Revisão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_claims', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='drivers_app.driverprofile', verbose_name='Motorista')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='orders_manager.order', verbose_name='Pedido Relacionado')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('settlement', models.ForeignKey(blank=True, help_text='Settlement onde o desconto foi aplicado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='settlements.driversettlement', verbose_name='Acerto')),
                ('vehicle_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='fleet_management.vehicleincident', verbose_name='Incidente de Veículo')),
            ],
            options={
                'verbose_name': 'Desconto de Motorista',
                'verbose_name_plural': 'Descontos de Motoristas',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Número único da fatura (ex: PAACK-2026-001)', max_length=100, unique=True, verbose_name='Número da Fatura')),
                ('external_reference', models.CharField(blank=True, help_text='Referência do sistema do partner', max_length=200, verbose_name='Referência Externa')),
                ('period_start', models.DateField(db_index=True, verbose_name='Início do Período')),
                ('period_end', models.DateField(db_index=True, verbose_name='Fim do Período')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Bruto')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='IVA')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Líquido')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING', 'Pendente'), ('PAID', 'Pago'), ('OVERDUE', 'Atrasado'), ('CANCELLED', 'Cancelado')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('due_date', models.DateField(db_index=True, verbose_name='Data de Vencimento')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Pago')),
                ('total_orders', models.PositiveIntegerField(default=0, help_text='Quantidade de pedidos incluídos', verbose_name='Total de Pedidos')),
                ('total_delivered', models.PositiveIntegerField(default=0, verbose_name='Pedidos Entregues')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.partner', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Fatura de Parceiro',
                'verbose_name_plural': 'Faturas de Parceiros',
                'ordering': ['-period_end', '-created_at'],
                'indexes': [models.Index(fields=['partner', 'period_start', 'period_end'], name='settlements_partner_a82e53_idx'), models.Index(fields=['status', 'due_date'], name='settlements_status_15981b_idx'), models.Index(fields=['-created_at'], name='settlements_created_648033_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='driversettlement',
            index=models.Index(fields=['driver', 'period_start', 'period_end'], name='settlements_driver__aa7127_idx'),
        ),
        migrations.AddIndex(
            model_name='driversettlement',
            index=models.Index(fields=['status', '-created_at'], name='settlements_status_83b7af_idx'),
        ),
        migrations.AddIndex(
            model_name='driversettlement',
            index=models.Index(fields=['year', 'week_number'], name='settlements_year_126825_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driversettlement',
            unique_together={('driver', 'partner', 'year', 'month_number'), ('driver', 'partner', 'year', 'week_number')},
        ),
        migrations.AddIndex(
            model_name='driverclaim',
            index=models.Index(fields=['driver', 'status', '-occurred_at'], name='settlements_driver__b18f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='driverclaim',
            index=models.Index(fields=['claim_type', 'status'], name='settlements_claim_t_f53e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='driverclaim',
            index=models.Index(fields=['-created_at'], name='settlements_created_0842eb_idx'),
        ),
    ]
