# Generated by Django 4.2.22 on 2026-04-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0003_add_pre_invoice_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='driverpreinvoice',
            new_name='settlements_driver__ae1658_idx',
            old_name='settle_preinv_driver_period_idx',
        ),
        migrations.RenameIndex(
            model_name='driverpreinvoice',
            new_name='settlements_status_199e32_idx',
            old_name='settle_preinv_status_idx',
        ),
    ]
