# Generated by Django 4.2.22 on 2026-04-09 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_synclog_is_from_cache'),
        ('settlements', '0004_add_pre_invoice_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpreinvoice',
            name='parceiro',
            field=models.ForeignKey(blank=True, help_text='Ex: Paack, Delnext, Cainiao', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_invoices', to='core.partner', verbose_name='Empresa / Parceiro'),
        ),
    ]
