# Generated by Django 4.2.22 on 2026-04-10 16:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_synclog_is_from_cache'),
        ('settlements', '0008_preinvoicelostpackage_iva_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverpreinvoice',
            name='base_entregas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Soma das linhas: pacotes × taxa (+ DSR)', max_digits=12, verbose_name='Base Entregas (€)'),
        ),
        migrations.AlterField(
            model_name='preinvoiceline',
            name='base_entregas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculado: pacotes × taxa × (1 + DSR/100)', max_digits=12, verbose_name='Base Entregas (€)'),
        ),
        migrations.AlterField(
            model_name='preinvoiceline',
            name='courier_id',
            field=models.CharField(blank=True, help_text='ID no sistema do parceiro (futura integração API)', max_length=100, verbose_name='Courier ID'),
        ),
        migrations.AlterField(
            model_name='preinvoiceline',
            name='dsr_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descanso Semanal Remunerado aplicado à base', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DSR (%)'),
        ),
        migrations.AlterField(
            model_name='preinvoiceline',
            name='observacoes',
            field=models.CharField(blank=True, max_length=300, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='preinvoiceline',
            name='parceiro',
            field=models.ForeignKey(blank=True, help_text='Ex: Paack, Delnext, Cainiao', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.partner', verbose_name='Parceiro / Operação'),
        ),
        migrations.AlterField(
            model_name='preinvoiceline',
            name='pre_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='settlements.driverpreinvoice', verbose_name='Pré-Fatura'),
        ),
        migrations.AlterField(
            model_name='preinvoiceline',
            name='taxa_por_entrega',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa por Entrega (€)'),
        ),
        migrations.AlterField(
            model_name='preinvoicelostpackage',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Base (€)'),
        ),
    ]
