# Generated by Django 4.2.22 on 2026-04-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0002_driverprofile_importado_auto'),
        ('core', '0003_synclog_is_from_cache'),
        ('settlements', '0009_alter_driverpreinvoice_base_entregas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverCourierMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.CharField(max_length=100, verbose_name='Courier ID')),
                ('courier_name', models.CharField(blank=True, max_length=200, verbose_name='Nome no Sistema Parceiro')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_mappings', to='drivers_app.driverprofile', verbose_name='Motorista')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_mappings', to='core.partner', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Mapeamento Courier',
                'verbose_name_plural': 'Mapeamentos Courier',
                'unique_together': {('partner', 'courier_id')},
            },
        ),
    ]
