# Generated by Django 4.2.22 on 2026-04-13 16:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0010_drivercouriermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpreinvoice',
            name='total_comissoes_indicacao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculado automaticamente com base nas indicações activas.', max_digits=12, verbose_name='Comissões de Indicação (€)'),
        ),
    ]
