# Generated by Django 4.2.22 on 2026-04-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0011_driverpreinvoice_total_comissoes_indicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpreinvoice',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, help_text='Foto ou ficheiro do comprovativo de pagamento', null=True, upload_to='pre_invoices/comprovativos/%Y/%m/', verbose_name='Comprovante de Pagamento'),
        ),
    ]
