# Generated by Django 4.2.22 on 2026-04-17 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0011_add_taxa_iva_to_lancamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0013_add_fatura_to_preinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CainiaoImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Ficheiro')),
                ('periodo_inicio', models.DateField(verbose_name='Período Início')),
                ('periodo_fim', models.DateField(verbose_name='Período Fim')),
                ('total_delivered', models.PositiveIntegerField(default=0, verbose_name='Total Entregas (Delivered)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cainiao_imports', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
            ],
            options={
                'verbose_name': 'Import Cainiao',
                'verbose_name_plural': 'Imports Cainiao',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_name', models.CharField(max_length=200, verbose_name='Nome do Helper')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('first_seen', models.DateField(blank=True, null=True, verbose_name='Visto pela primeira vez')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpers', to='drivers_app.driverprofile', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Helper do Motorista',
                'verbose_name_plural': 'Helpers dos Motoristas',
                'ordering': ['helper_name'],
                'unique_together': {('driver', 'helper_name')},
            },
        ),
        migrations.CreateModel(
            name='CainiaoDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.CharField(max_length=100, verbose_name='Courier ID')),
                ('helper_name', models.CharField(blank=True, max_length=200, verbose_name='Courier Helper')),
                ('lp_number', models.CharField(blank=True, max_length=200, verbose_name='LP No.')),
                ('waybill_number', models.CharField(blank=True, max_length=200, verbose_name='Waybill Number')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='settlements.cainiaoimportbatch', verbose_name='Batch')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cainiao_deliveries', to='drivers_app.driverprofile', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Entrega Cainiao',
                'verbose_name_plural': 'Entregas Cainiao',
                'indexes': [models.Index(fields=['driver', 'batch'], name='settlements_driver__531a47_idx'), models.Index(fields=['courier_id'], name='settlements_courier_1a21be_idx')],
            },
        ),
    ]
