# Generated by Django 4.2.22 on 2026-04-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0014_cainiao_import_helpers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cainiaodelivery',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega'),
        ),
        migrations.AlterField(
            model_name='cainiaodelivery',
            name='lp_number',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='LP No.'),
        ),
        migrations.AlterField(
            model_name='cainiaodelivery',
            name='waybill_number',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Waybill Number'),
        ),
    ]
