# Generated by Django 4.2.22 on 2026-04-20 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0015_cainiao_delivery_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CainiaoForecastBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Ficheiro')),
                ('import_type', models.CharField(choices=[('FORECAST', 'Previsão de Volume'), ('INBOUND', 'Inbound'), ('EOD', 'Final do Dia')], default='FORECAST', max_length=20, verbose_name='Tipo de Import')),
                ('operation_date', models.DateField(verbose_name='Data da Operação')),
                ('total_packages', models.PositiveIntegerField(default=0, verbose_name='Total Pacotes')),
                ('updated_packages', models.PositiveIntegerField(default=0, verbose_name='Pacotes Atualizados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cainiao_forecast_imports', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
            ],
            options={
                'verbose_name': 'Import Cainiao (Planilha)',
                'verbose_name_plural': 'Imports Cainiao (Planilhas)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CainiaoForecastPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(db_index=True, verbose_name='Data da Operação')),
                ('tracking_number', models.CharField(db_index=True, max_length=100, verbose_name='Tracking No.')),
                ('status', models.CharField(db_index=True, default='Create', max_length=30, verbose_name='Status')),
                ('lp_number', models.CharField(blank=True, max_length=100, verbose_name='LP No.')),
                ('site_code', models.CharField(blank=True, max_length=100, verbose_name='Site Code')),
                ('inbound_bigbag_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Inbound Bigbag ID')),
                ('bigbag_number', models.CharField(blank=True, max_length=100, verbose_name='Bigbag No.')),
                ('sort_code', models.CharField(blank=True, max_length=50, verbose_name='Sort Code')),
                ('order_type', models.CharField(blank=True, max_length=20, verbose_name='Order Type')),
                ('sop_type', models.CharField(blank=True, max_length=20, verbose_name='SOP Type')),
                ('receiver_name', models.CharField(blank=True, max_length=200, verbose_name='Nome Cliente')),
                ('receiver_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefone')),
                ('receiver_region', models.CharField(blank=True, max_length=100, verbose_name='Região')),
                ('receiver_city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('receiver_zip', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('receiver_address', models.TextField(blank=True, verbose_name='Endereço')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True, verbose_name='Longitude')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('last_import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='settlements.cainiaoforecastbatch', verbose_name='Último Batch')),
            ],
            options={
                'verbose_name': 'Pacote Cainiao (Planilha)',
                'verbose_name_plural': 'Pacotes Cainiao (Planilha)',
                'indexes': [models.Index(fields=['operation_date', 'status'], name='settlements_operati_00e31c_idx'), models.Index(fields=['inbound_bigbag_id'], name='settlements_inbound_9c7e07_idx')],
                'unique_together': {('operation_date', 'tracking_number')},
            },
        ),
    ]
