# Generated by Django 4.2.22 on 2026-04-24 20:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_partner_bonus_performance_enabled_and_more'),
        ('drivers_app', '0012_driverprofile_advance_monthly_limit_and_more'),
        ('settlements', '0018_cainiao_hubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverclaim',
            name='auto_detected',
            field=models.BooleanField(db_index=True, default=False, help_text='Criado pelo processo de auto-detecção (task Celery).', verbose_name='Detetado Automaticamente'),
        ),
        migrations.AddField(
            model_name='driverclaim',
            name='operation_task_date',
            field=models.DateField(blank=True, db_index=True, help_text='Data do CainiaoOperationTask (em conjunto com waybill dá a chave única).', null=True, verbose_name='Data da Tarefa'),
        ),
        migrations.AddField(
            model_name='driverclaim',
            name='waybill_number',
            field=models.CharField(blank=True, db_index=True, help_text='Waybill do CainiaoOperationTask associado (para auto-detecção de perdas).', max_length=100, verbose_name='Waybill do Pacote'),
        ),
        migrations.AddField(
            model_name='driverpreinvoice',
            name='caucao_retida',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Caução Retida (€)'),
        ),
        migrations.AddField(
            model_name='driverpreinvoice',
            name='irs_retention_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Retenção IRS (€)'),
        ),
        migrations.AddField(
            model_name='driverpreinvoice',
            name='signed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp quando o motorista aceitou remotamente.', null=True, verbose_name='Aceite pelo motorista em'),
        ),
        migrations.AddField(
            model_name='driverpreinvoice',
            name='signed_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da Aceitação'),
        ),
        migrations.AddField(
            model_name='driverpreinvoice',
            name='signed_token',
            field=models.CharField(blank=True, db_index=True, help_text='Token único para link de aceitação remota.', max_length=64, verbose_name='Token de Assinatura'),
        ),
        migrations.AddField(
            model_name='driverpreinvoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IVA (€)'),
        ),
        migrations.AddField(
            model_name='driverpreinvoice',
            name='whatsapp_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado via WhatsApp em'),
        ),
        migrations.AlterField(
            model_name='cainiaohub',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cainiaohubcp4',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PreInvoiceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Criada'), ('EDITED', 'Editada'), ('LINE_ADD', 'Linha adicionada'), ('LINE_EDIT', 'Linha editada'), ('LINE_DEL', 'Linha removida'), ('PRICE_OVR', 'Preço alterado'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada'), ('SIGNED', 'Aceite por motorista'), ('PAID', 'Paga'), ('RECEIPT', 'Comprovativo anexado'), ('WHATSAPP', 'Enviada via WhatsApp')], db_index=True, max_length=15, verbose_name='Acção')),
                ('summary', models.CharField(blank=True, max_length=250, verbose_name='Resumo')),
                ('diff', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pre_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='settlements.driverpreinvoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_invoice_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria da Pré-Fatura',
                'verbose_name_plural': 'Logs de Auditoria das Pré-Faturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceBonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('enabled', models.BooleanField(default=True, verbose_name='Activo')),
                ('condition', models.CharField(choices=[('SUCCESS_RATE_GTE', 'Taxa sucesso ≥ X%'), ('VOLUME_GTE', 'Volume ≥ X pacotes'), ('FAIL_RATE_LTE', 'Taxa falha ≤ X%'), ('SPECIAL_DAY', 'Dia especial (domingo/feriado)')], max_length=20, verbose_name='Condição')),
                ('condition_value', models.DecimalField(decimal_places=2, default=0, help_text='Ex: 95 (taxa sucesso ≥ 95%) ou 200 (volume ≥ 200 pacotes).', max_digits=8, verbose_name='Valor da condição')),
                ('effect', models.CharField(choices=[('PCT_BONUS', '% bónus sobre base'), ('FIXED_BONUS', 'Valor fixo em €'), ('PCT_PENALTY', '% penalização sobre base'), ('FIXED_PENALTY', 'Penalização fixa em €')], max_length=20, verbose_name='Efeito')),
                ('effect_value', models.DecimalField(decimal_places=2, default=0, help_text='Ex: 10 (10% bónus) ou 30.00 (30€ fixo).', max_digits=10, verbose_name='Valor do efeito')),
                ('scope_period', models.CharField(choices=[('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal'), ('DAILY', 'Diário')], default='WEEKLY', max_length=10, verbose_name='Período')),
                ('applies_to_fleets_only', models.BooleanField(default=False, help_text='Se activo, a regra só se aplica a motoristas com frota (Empresa Parceira).', verbose_name='Só frotas')),
                ('applies_to_independent_only', models.BooleanField(default=False, help_text='Se activo, a regra só se aplica a motoristas directos (sem frota).', verbose_name='Só independentes')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_rules', to='core.partner')),
            ],
            options={
                'verbose_name': 'Regra de Bónus/Penalty',
                'verbose_name_plural': 'Regras de Bónus/Penalty',
                'ordering': ['partner', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OperationalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CARRINHA', 'Renda de Carrinha'), ('COMBUSTIVEL', 'Combustível'), ('SEGURO', 'Seguro'), ('MANUTENCAO', 'Manutenção'), ('OUTRO', 'Outro')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('mode', models.CharField(choices=[('FIXED', 'Fixo (€)'), ('PCT', '% do bruto'), ('PER_KM', 'Por km percorrido')], default='FIXED', max_length=10, verbose_name='Modo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('period', models.CharField(choices=[('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal'), ('DAILY', 'Diário'), ('ONESHOT', 'Avulso (uma vez)')], default='MONTHLY', max_length=10, verbose_name='Período')),
                ('active_from', models.DateField(default=django.utils.timezone.now, verbose_name='Activo desde')),
                ('active_until', models.DateField(blank=True, null=True, verbose_name='Activo até')),
                ('enabled', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_costs', to='drivers_app.driverprofile')),
                ('fleet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_costs', to='drivers_app.empresaparceira')),
            ],
            options={
                'verbose_name': 'Custo Operacional',
                'verbose_name_plural': 'Custos Operacionais',
                'ordering': ['driver', 'fleet', '-active_from'],
            },
        ),
        migrations.CreateModel(
            name='PreInvoicePriceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('LINE', 'Linha de trabalho'), ('WAYBILL', 'Waybill específico'), ('DAY_RANGE', 'Período (dias)'), ('ZONE', 'Zona (CP4)')], db_index=True, max_length=15, verbose_name='Escopo')),
                ('waybill_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('cp4', models.CharField(blank=True, db_index=True, max_length=4)),
                ('new_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Novo Preço por Pacote (€)')),
                ('reason', models.TextField(blank=True, verbose_name='Justificação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_price_overrides', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='settlements.preinvoiceline')),
                ('pre_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_overrides', to='settlements.driverpreinvoice')),
            ],
            options={
                'verbose_name': 'Override de Preço',
                'verbose_name_plural': 'Overrides de Preço',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pre_invoice', 'scope'], name='settlements_pre_inv_698b84_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Informação'), ('WARN', 'Aviso'), ('DANGER', 'Crítico')], default='WARN', max_length=10, verbose_name='Nível')),
                ('kind', models.CharField(choices=[('PAYMENT_OVERDUE', 'Pagamento em atraso'), ('ADVANCE_OVER_LIMIT', 'Limite de adiantamentos excedido'), ('CLAIM_PENDING', 'Claim pendente há muitos dias'), ('NO_PREINVOICE', 'Motorista sem pré-fatura'), ('LOW_SUCCESS_RATE', 'Taxa de sucesso baixa'), ('OTHER', 'Outro')], db_index=True, max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('resolved', models.BooleanField(db_index=True, default=False, verbose_name='Resolvido')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de Resolução')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_alerts', to='drivers_app.driverprofile')),
                ('fleet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_alerts', to='drivers_app.empresaparceira')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_alerts', to='core.partner')),
                ('pre_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_alerts', to='settlements.driverpreinvoice')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_financial_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta Financeiro',
                'verbose_name_plural': 'Alertas Financeiros',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resolved', '-created_at'], name='settlements_resolve_90b7ed_idx'), models.Index(fields=['level', 'resolved'], name='settlements_level_111852_idx')],
            },
        ),
    ]
