# Generated by Django 4.2.22 on 2026-04-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0019_driverclaim_auto_detected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cainiaooperationtask',
            name='courier_id_cainiao',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador único Cainiao do motorista (não muda mesmo se o courier_name for editado). Resolvido via DriverCourierMapping no import. Permite manter ligação a entregas antigas após renomear o courier_name.', max_length=50, verbose_name='Courier ID (Cainiao)'),
        ),
    ]
