# Generated by Django 4.2.22 on 2026-04-25 18:38

from django.db import migrations, models
import django.db.models.deletion


def backfill_aliases(apps, schema_editor):
    """Popula CourierNameAlias a partir do estado actual:
    - DriverCourierMapping (partner, courier_name → courier_id)
    - DriverProfile (apelido → courier_id_cainiao) para CAINIAO
    - CainiaoOperationTask (courier_name, courier_id_cainiao!='') para CAINIAO
    """
    CourierNameAlias = apps.get_model("settlements", "CourierNameAlias")
    DriverCourierMapping = apps.get_model("settlements", "DriverCourierMapping")
    DriverProfile = apps.get_model("drivers_app", "DriverProfile")
    CainiaoOperationTask = apps.get_model("settlements", "CainiaoOperationTask")
    Partner = apps.get_model("core", "Partner")

    seen = set()  # (partner_id, courier_name)
    bulk = []

    # 1. Mappings actuais
    for m in DriverCourierMapping.objects.exclude(courier_name=""):
        key = (m.partner_id, m.courier_name)
        if key in seen:
            continue
        seen.add(key)
        bulk.append(CourierNameAlias(
            partner_id=m.partner_id,
            courier_name=m.courier_name,
            courier_id=m.courier_id,
            source="auto",
        ))

    # 2. Apelidos de DriverProfile (apenas para CAINIAO)
    cainiao = Partner.objects.filter(name__iexact="CAINIAO").first()
    if cainiao:
        for d in DriverProfile.objects.exclude(apelido="").exclude(courier_id_cainiao=""):
            key = (cainiao.id, d.apelido)
            if key in seen:
                continue
            seen.add(key)
            bulk.append(CourierNameAlias(
                partner_id=cainiao.id,
                courier_name=d.apelido,
                courier_id=d.courier_id_cainiao,
                source="auto",
            ))

        # 3. Tasks com courier_id_cainiao já resolvido (preserva mappings manuais)
        existing_pairs = (
            CainiaoOperationTask.objects
            .exclude(courier_id_cainiao="")
            .exclude(courier_name="")
            .values_list("courier_name", "courier_id_cainiao")
            .distinct()
        )
        for cname, cid in existing_pairs:
            key = (cainiao.id, cname)
            if key in seen:
                continue
            seen.add(key)
            bulk.append(CourierNameAlias(
                partner_id=cainiao.id,
                courier_name=cname,
                courier_id=cid,
                source="auto",
            ))

    if bulk:
        CourierNameAlias.objects.bulk_create(bulk, batch_size=500)


def revert_aliases(apps, schema_editor):
    """Reversal: limpa todas as aliases (re-criáveis pela forward)."""
    apps.get_model("settlements", "CourierNameAlias").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_partner_bonus_performance_enabled_and_more'),
        ('drivers_app', '0001_initial'),
        ('settlements', '0020_cainiaooperationtask_courier_id_cainiao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierNameAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(db_index=True, max_length=255)),
                ('courier_id', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('auto', 'Auto')], default='auto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_name_aliases', to='core.partner')),
            ],
            options={
                'verbose_name': 'Alias de Courier Name',
                'verbose_name_plural': 'Aliases de Courier Name',
                'indexes': [models.Index(fields=['partner', 'courier_name'], name='settlements_partner_0ab56d_idx'), models.Index(fields=['partner', 'courier_id'], name='settlements_partner_62fdac_idx')],
                'unique_together': {('partner', 'courier_name')},
            },
        ),
        migrations.RunPython(backfill_aliases, revert_aliases),
    ]
