# Generated by Django 4.2.22 on 2026-04-25 19:15

from datetime import date as _date

from django.db import migrations, models


# Feriados Nacionais PT — datas fixas (recurring_yearly=True) usam ano 2000
# como placeholder; o matcher só compara dia/mês.
PT_NATIONAL_FIXED = [
    (_date(2000, 1, 1),  "Ano Novo"),
    (_date(2000, 4, 25), "Dia da Liberdade"),
    (_date(2000, 5, 1),  "Dia do Trabalhador"),
    (_date(2000, 6, 10), "Dia de Portugal"),
    (_date(2000, 8, 15), "Assunção de Nossa Senhora"),
    (_date(2000, 10, 5), "Implantação da República"),
    (_date(2000, 11, 1), "Dia de Todos os Santos"),
    (_date(2000, 12, 1), "Restauração da Independência"),
    (_date(2000, 12, 8), "Imaculada Conceição"),
    (_date(2000, 12, 25), "Natal"),
]

# Feriados móveis PT 2026 (calculados pela Páscoa)
PT_MOVABLE_2026 = [
    (_date(2026, 2, 17), "Carnaval"),
    (_date(2026, 4, 3),  "Sexta-Feira Santa"),
    (_date(2026, 4, 5),  "Páscoa"),
    (_date(2026, 6, 4),  "Corpo de Deus"),
]


def seed_pt_holidays(apps, schema_editor):
    Holiday = apps.get_model("settlements", "Holiday")
    rows = []
    for d, name in PT_NATIONAL_FIXED:
        rows.append(Holiday(
            name=name, date=d, is_recurring_yearly=True,
            scope="national",
        ))
    for d, name in PT_MOVABLE_2026:
        rows.append(Holiday(
            name=name, date=d, is_recurring_yearly=False,
            scope="national",
            notes="Feriado móvel — adicionar entrada nova nos anos seguintes",
        ))
    Holiday.objects.bulk_create(rows, ignore_conflicts=True)


def remove_pt_holidays(apps, schema_editor):
    apps.get_model("settlements", "Holiday").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0021_courier_name_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('date', models.DateField(db_index=True, verbose_name='Data')),
                ('is_recurring_yearly', models.BooleanField(default=False, help_text='Se ativo, aplica em todos os anos no mesmo dia/mês (ex: 25/12). Para datas móveis (ex: Páscoa) deixar inativo e adicionar uma entrada por ano.', verbose_name='Repete anualmente')),
                ('scope', models.CharField(choices=[('national', 'Nacional'), ('regional', 'Regional'), ('custom', 'Customizado')], default='national', max_length=20, verbose_name='Tipo')),
                ('region', models.CharField(blank=True, help_text="Aplica apenas a uma região (ex: 'Aveiro'). Vazio = aplica a todos os drivers/parceiros.", max_length=80, verbose_name='Região')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados / Calendário',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='settlements_date_38663a_idx'), models.Index(fields=['is_recurring_yearly'], name='settlements_is_recu_57b0a0_idx')],
            },
        ),
        migrations.RunPython(seed_pt_holidays, remove_pt_holidays),
    ]
