# Generated by Django 4.2.22 on 2026-04-25 23:45

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0015_fleetautoemitconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0022_holiday_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Ex: FF-0001 (Frota)', max_length=20, unique=True, verbose_name='Número')),
                ('periodo_inicio', models.DateField(db_index=True, verbose_name='Período Início')),
                ('periodo_fim', models.DateField(db_index=True, verbose_name='Período Fim')),
                ('partner_price_per_package', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8, verbose_name='Preço cobrado ao Parceiro (€/pacote)')),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('total_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Total Base (entregas)')),
                ('total_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Total Bónus')),
                ('total_claims', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Total Claims (descontos)')),
                ('total_a_receber', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Total a Receber pela frota')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CALCULADO', 'Calculado'), ('APROVADO', 'Aprovado'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], db_index=True, default='CALCULADO', max_length=20, verbose_name='Estado')),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('referencia_pagamento', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_invoices', to='drivers_app.empresaparceira')),
            ],
            options={
                'verbose_name': 'Pré-fatura Frota',
                'verbose_name_plural': 'Pré-faturas Frota',
                'ordering': ['-periodo_fim', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FleetInvoiceDriverLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('courier_id_snapshot', models.CharField(blank=True, max_length=64)),
                ('courier_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('deliveries', models.PositiveIntegerField(default=0)),
                ('price_per_package', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('price_source', models.CharField(blank=True, help_text='driver_override / fleet_default / partner_default / none', max_length=20)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('bonus_days_count', models.PositiveSmallIntegerField(default=0)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('claims_count', models.PositiveSmallIntegerField(default=0)),
                ('claims_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('observacoes', models.CharField(blank=True, max_length=300)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drivers_app.driverprofile')),
                ('fleet_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='settlements.fleetinvoice')),
            ],
            options={
                'verbose_name': 'Linha por Driver (FleetInvoice)',
                'verbose_name_plural': 'Linhas por Driver (FleetInvoice)',
                'ordering': ['-deliveries'],
            },
        ),
        migrations.CreateModel(
            name='FleetInvoiceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(blank=True, max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('driver_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='settlements.driverclaim')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_detail', to='settlements.fleetinvoicedriverline')),
            ],
        ),
        migrations.CreateModel(
            name='FleetInvoiceBonusDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('DOMINGO', 'Domingo'), ('FERIADO', 'Feriado')], max_length=20)),
                ('deliveries', models.PositiveIntegerField()),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=8)),
                ('feriado_nome', models.CharField(blank=True, max_length=120)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_days_detail', to='settlements.fleetinvoicedriverline')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.AddIndex(
            model_name='fleetinvoice',
            index=models.Index(fields=['empresa', '-periodo_fim'], name='settlements_empresa_125629_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetinvoice',
            index=models.Index(fields=['status'], name='settlements_status_a1e712_idx'),
        ),
    ]
