# Generated by Django 4.2.22 on 2026-04-26 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0023_fleet_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CainiaoManualForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(db_index=True, verbose_name='Data da Operação')),
                ('cp4', models.CharField(db_index=True, max_length=4, verbose_name='CP4')),
                ('qty', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Previsão Manual (Cainiao)',
                'verbose_name_plural': 'Previsões Manuais (Cainiao)',
                'ordering': ['-operation_date', 'cp4'],
                'indexes': [models.Index(fields=['operation_date', 'cp4'], name='settlements_operati_189f34_idx')],
                'unique_together': {('operation_date', 'cp4')},
            },
        ),
    ]
