# Generated by Django 4.2.22 on 2026-04-26 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0016_driverprofile_daily_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0024_manual_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(db_index=True, verbose_name='Data da Operação')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado')], db_index=True, default='DRAFT', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('notify_on_publish', models.BooleanField(default=False, verbose_name='Notificar drivers ao publicar')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_plans_created', to=settings.AUTH_USER_MODEL)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_plans', to='settlements.cainiaohub')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de Distribuição',
                'verbose_name_plural': 'Planos de Distribuição',
                'ordering': ['-operation_date', '-id'],
                'unique_together': {('operation_date', 'hub')},
            },
        ),
        migrations.CreateModel(
            name='ForecastPlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp4', models.CharField(db_index=True, max_length=4)),
                ('manual_name', models.CharField(blank=True, help_text="Usado quando o driver não está cadastrado (ex: 'João Temp').", max_length=120, verbose_name='Nome manual')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Qtd. atribuída')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_assignments', to='drivers_app.driverprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='settlements.forecastplan')),
            ],
            options={
                'verbose_name': 'Atribuição (Plano)',
                'verbose_name_plural': 'Atribuições (Plano)',
                'ordering': ['cp4', '-qty'],
                'indexes': [models.Index(fields=['plan', 'cp4'], name='settlements_plan_id_91f485_idx'), models.Index(fields=['driver'], name='settlements_driver__9e88cb_idx')],
            },
        ),
    ]
