# Generated by Django 4.2.22 on 2026-04-26 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0016_driverprofile_daily_capacity'),
        ('settlements', '0025_forecastplan_forecastplanassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastPlanCP4Skip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp4', models.CharField(max_length=4)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CP4 ignorado (Plano)',
                'verbose_name_plural': 'CP4s ignorados (Plano)',
            },
        ),
        migrations.AddField(
            model_name='forecastplanassignment',
            name='fleet',
            field=models.ForeignKey(blank=True, help_text='Frota inteira que recebe este CP4 (ex: subcontratada).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_assignments', to='drivers_app.empresaparceira'),
        ),
        migrations.AddIndex(
            model_name='forecastplanassignment',
            index=models.Index(fields=['fleet'], name='settlements_fleet_i_ac925a_idx'),
        ),
        migrations.AddField(
            model_name='forecastplancp4skip',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skipped_cp4s', to='settlements.forecastplan'),
        ),
        migrations.AlterUniqueTogether(
            name='forecastplancp4skip',
            unique_together={('plan', 'cp4')},
        ),
    ]
