# Generated by Django 4.2.22 on 2026-04-27 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0026_forecastplancp4skip_forecastplanassignment_fleet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaybillComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(db_index=True, max_length=100, verbose_name='Waybill')),
                ('body', models.TextField(verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário de Waybill',
                'verbose_name_plural': 'Comentários de Waybills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaybillResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Waybill')),
                ('resolution_type', models.CharField(choices=[('DELIVERED_OTHER_HUB', 'Entregue por outro HUB'), ('DELIVERED_LATE', 'Entregue tarde (sem reimport)'), ('RETURNED', 'Devolvido ao remetente'), ('LOST', 'Pacote perdido'), ('AUTO_REIMPORT', 'Auto-resolvido (reimport)'), ('OTHER', 'Outro')], default='DELIVERED_OTHER_HUB', max_length=30, verbose_name='Tipo')),
                ('resolved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Resolvido em')),
                ('other_hub', models.CharField(blank=True, max_length=100, verbose_name='HUB que entregou')),
                ('other_courier', models.CharField(blank=True, max_length=200, verbose_name='Courier (outro HUB)')),
                ('other_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de entrega real')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resolução de Waybill',
                'verbose_name_plural': 'Resoluções de Waybills',
                'ordering': ['-resolved_at'],
                'indexes': [models.Index(fields=['resolution_type', 'resolved_at'], name='settlements_resolut_8da2fa_idx')],
            },
        ),
    ]
