# Generated by Django 4.2.22 on 2026-04-27 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0027_waybillcomment_waybillresolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotArrivedSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='Data do snapshot')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Gerado em')),
                ('is_automatic', models.BooleanField(default=True, help_text='True = gerado por Celery task; False = manual', verbose_name='Automático')),
                ('total_packages', models.IntegerField(default=0, verbose_name='Total pacotes')),
                ('total_cost_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo estimado (€)')),
                ('n_to_escalate', models.IntegerField(default=0, verbose_name='Total a escalar (>10d)')),
                ('n_drivers_affected', models.IntegerField(default=0, verbose_name='Drivers afectados')),
                ('n_cp4s_affected', models.IntegerField(default=0, verbose_name='CP4s afectados')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='not_arrived_snapshots', to='settlements.cainiaohub')),
            ],
            options={
                'verbose_name': 'Snapshot Not Arrived',
                'verbose_name_plural': 'Snapshots Not Arrived',
                'ordering': ['-snapshot_date', '-created_at'],
                'unique_together': {('snapshot_date', 'hub')},
            },
        ),
        migrations.CreateModel(
            name='WaybillFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(db_index=True, max_length=100, verbose_name='Waybill')),
                ('flag_type', models.CharField(choices=[('NOT_ARRIVED', 'Not Arrived'), ('SUSPECTED_LOST', 'Suspeita de perdido'), ('NEEDS_INVESTIGATION', 'Necessita investigação')], default='NOT_ARRIVED', max_length=30, verbose_name='Tipo')),
                ('reason', models.CharField(choices=[('customer_reported', 'Cliente reportou que não recebeu'), ('driver_lost', 'Driver disse que perdeu'), ('suspected_return', 'Suspeita de devolução não registada'), ('transferred_other_hub', 'Transferido para outro HUB'), ('under_investigation', 'Investigação em curso'), ('other', 'Outro')], default='other', max_length=40, verbose_name='Razão')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('flagged_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Sinalizado em')),
                ('cleared_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Limpo em')),
                ('cleared_reason', models.CharField(blank=True, max_length=255, verbose_name='Razão de limpeza')),
                ('auto_cleared', models.BooleanField(default=False, help_text='True se foi limpo automaticamente pelo signal', verbose_name='Auto-limpo')),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_flags_cleared', to=settings.AUTH_USER_MODEL)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flag de Waybill',
                'verbose_name_plural': 'Flags de Waybills',
                'ordering': ['-flagged_at'],
                'indexes': [models.Index(fields=['waybill_number', 'cleared_at'], name='settlements_waybill_de314a_idx'), models.Index(fields=['flag_type', 'cleared_at'], name='settlements_flag_ty_8adfc5_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotArrivedSnapshotRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(db_index=True, max_length=100)),
                ('courier_name', models.CharField(blank=True, max_length=200)),
                ('courier_id_cainiao', models.CharField(blank=True, max_length=50)),
                ('cp4', models.CharField(blank=True, db_index=True, max_length=4)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('seller', models.CharField(blank=True, max_length=200)),
                ('weight_g', models.FloatField(blank=True, null=True)),
                ('business_days_stuck', models.IntegerField(default=0)),
                ('sla_level', models.CharField(blank=True, max_length=10)),
                ('first_seen', models.DateField(blank=True, null=True)),
                ('estimated_cost_eur', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='settlements.notarrivedsnapshot')),
            ],
            options={
                'verbose_name': 'Linha Snapshot Not Arrived',
                'ordering': ['-business_days_stuck', 'courier_name'],
                'indexes': [models.Index(fields=['snapshot', 'waybill_number'], name='settlements_snapsho_965b9e_idx'), models.Index(fields=['waybill_number', 'snapshot'], name='settlements_waybill_ca5ee2_idx')],
            },
        ),
    ]
