# Generated by Django 4.2.22 on 2026-04-27 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0028_notarrivedsnapshot_waybillflag_notarrivedsnapshotrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrioritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_days_in_hub', models.PositiveIntegerField(default=3, help_text='Pacotes parados há ≥ N dias úteis no HUB tornam-se prioritários.', verbose_name='Mín. dias no HUB para ser prioritário')),
                ('min_attempts', models.PositiveIntegerField(default=2, help_text='Pacotes com ≥ N tentativas de entrega tornam-se prioritários.', verbose_name='Mín. tentativas falhadas para ser prioritário')),
                ('auto_apply', models.BooleanField(default=True, help_text='Desligar para usar só a flag PRIORITYS do Cainiao.', verbose_name='Aplicar regras automáticas')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Prioridade',
                'verbose_name_plural': 'Configurações de Prioridade',
            },
        ),
        migrations.CreateModel(
            name='SavedSearchFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('filter_data', models.JSONField(default=dict, verbose_name='Dados do filtro')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Partilhado com a equipa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filtro Guardado',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WaybillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(db_index=True, max_length=100, verbose_name='Waybill')),
                ('tag', models.CharField(db_index=True, max_length=50, verbose_name='Etiqueta')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag de Waybill',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaybillWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(db_index=True, max_length=100, verbose_name='Waybill')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('notify_on_change', models.BooleanField(default=True, verbose_name='Notificar mudanças')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Watch de Waybill',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cainiaooperationtask',
            name='arrive_wrong_hub',
            field=models.BooleanField(default=False, verbose_name='Arrive Wrong Hub'),
        ),
        migrations.AddField(
            model_name='cainiaooperationtask',
            name='bigbag_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bigbag No.'),
        ),
        migrations.AddField(
            model_name='cainiaooperationtask',
            name='commercial_area',
            field=models.CharField(blank=True, max_length=100, verbose_name='Commercial Area'),
        ),
        migrations.AddField(
            model_name='cainiaooperationtask',
            name='hub_exception_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='HUB Exception Reason'),
        ),
        migrations.AddField(
            model_name='cainiaooperationtask',
            name='is_priority_external',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag PRIORITYS=Yes vinda do Cainiao', verbose_name='Priority (Cainiao)'),
        ),
        migrations.AddField(
            model_name='cainiaooperationtask',
            name='pre_allocated_dsp',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pre-allocated DSP'),
        ),
        migrations.AddField(
            model_name='cainiaooperationtask',
            name='pre_assigned_driver',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pre-assigned driver'),
        ),
        migrations.AddField(
            model_name='cainiaooperationtask',
            name='task_plan_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Task Plan Date'),
        ),
        migrations.AddField(
            model_name='cainiaooperationtask',
            name='wrong_hub_parcel',
            field=models.BooleanField(default=False, verbose_name='Wrong HUB Parcel'),
        ),
        migrations.AddIndex(
            model_name='cainiaooperationtask',
            index=models.Index(fields=['is_priority_external', 'task_status'], name='settlements_is_prio_954de1_idx'),
        ),
        migrations.AddField(
            model_name='waybillwatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybill_watches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waybilltag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedsearchfilter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_search_filters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='waybillwatch',
            unique_together={('waybill_number', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='waybilltag',
            unique_together={('waybill_number', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='savedsearchfilter',
            unique_together={('user', 'name')},
        ),
    ]
