# Generated by Django 4.2.22 on 2026-04-27 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0029_prioritysettings_savedsearchfilter_waybilltag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="ex: 'Devoluções Aveiro 27/04'", max_length=100, verbose_name='Nome do lote')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fechado em')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('total_cost_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo total (€)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de Devolução',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaybillReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Waybill')),
                ('return_status', models.CharField(choices=[('PREPARING', 'A preparar'), ('IN_TRANSIT', 'Em trânsito de retorno'), ('RETURNED_TO_SENDER', 'Chegou ao remetente'), ('CLOSED', 'Fechado')], db_index=True, default='PREPARING', max_length=30, verbose_name='Status')),
                ('return_reason', models.CharField(choices=[('address_wrong', 'Endereço errado'), ('customer_refused', 'Cliente recusou'), ('customer_not_found', 'Cliente não encontrado'), ('damaged', 'Pacote danificado'), ('no_response', 'Cliente não respondeu'), ('expired', 'Prazo expirou'), ('other', 'Outro')], default='address_wrong', max_length=40, verbose_name='Razão')),
                ('return_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de devolução')),
                ('return_tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Tracking de retorno')),
                ('return_carrier', models.CharField(blank=True, help_text='ex: Cainiao, CTT, DHL...', max_length=100, verbose_name='Transportadora retorno')),
                ('return_cost_eur', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Custo da devolução (€)')),
                ('customer_notified', models.BooleanField(default=False, verbose_name='Cliente notificado')),
                ('notification_method', models.CharField(blank=True, help_text='WhatsApp, SMS, Email…', max_length=30, verbose_name='Método de notificação')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fechado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='settlements.returnbatch')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_returns_marked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolução de Waybill',
                'verbose_name_plural': 'Devoluções de Waybills',
                'ordering': ['-return_date', '-created_at'],
                'indexes': [models.Index(fields=['return_status', 'return_date'], name='settlements_return__5a54bb_idx'), models.Index(fields=['return_reason'], name='settlements_return__0d47a7_idx')],
            },
        ),
    ]
