# Generated by Django 4.2.22 on 2026-04-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0030_returnbatch_waybillreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='actual_delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entrega Real'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='actual_inbound_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inbound Real'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='actual_outbound_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Outbound Real'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='address_abnormal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Address Abnormal'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='arriving_at_wrong_hub',
            field=models.BooleanField(default=False, verbose_name='Wrong HUB'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create Time'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='delivery_mode',
            field=models.CharField(blank=True, max_length=50, verbose_name='Delivery Mode'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='dimensions_lwh',
            field=models.CharField(blank=True, max_length=50, verbose_name='Dimensões L×W×H'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='dsp_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='DSP Name'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='exception_detail',
            field=models.TextField(blank=True, verbose_name='Detalhe Exceção'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='exception_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Exceção'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='has_commercial_area_tag',
            field=models.BooleanField(default=False, verbose_name='Tem tag Commercial Area'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='has_pin_code',
            field=models.BooleanField(default=False, verbose_name='Has PIN Code'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='is_consolidation',
            field=models.BooleanField(default=False, verbose_name='Is Consolidation'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='last_exception_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Exceção'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='last_task_plan_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Última data planeada'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='locker_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Locker ID'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='modified_address',
            field=models.TextField(blank=True, verbose_name='Endereço modificado'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='modified_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefone modificado'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='modified_zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='CP modificado'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='pin_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='PIN Code'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='pod_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='POD'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='receiver_contact_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contacto adicional'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='receiver_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='seller_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Seller Name'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Task ID'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='weight_g',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso (g)'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='wrong_hub_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Wrong HUB Name'),
        ),
        migrations.AddField(
            model_name='cainiaoforecastpackage',
            name='zone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zone'),
        ),
    ]
