# Generated by Django 4.2.22 on 2026-04-29 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0016_driverprofile_daily_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0031_cainiaoforecastpackage_actual_delivery_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaybillAttributionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Waybill')),
                ('task_date', models.DateField(db_index=True, help_text='Dia em que a entrega foi efectivamente feita.', verbose_name='Data da operação')),
                ('original_courier_id', models.CharField(blank=True, max_length=64, verbose_name='Courier ID original (Cainiao)')),
                ('original_courier_name', models.CharField(blank=True, max_length=120, verbose_name='Courier name original')),
                ('reason', models.CharField(blank=True, help_text='ex: Socorro — carro avariado', max_length=200, verbose_name='Razão')),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('attributed_to_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybill_attributions', to='drivers_app.driverprofile', verbose_name='Atribuir a (driver destino)')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferência de Atribuição',
                'verbose_name_plural': 'Transferências de Atribuição',
                'ordering': ['-transferred_at'],
                'indexes': [models.Index(fields=['task_date', 'attributed_to_driver'], name='settlements_task_da_cb0cb3_idx')],
            },
        ),
    ]
