# Generated by Django 4.2.22 on 2026-04-29 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0032_waybillattributionoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePriceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Waybill')),
                ('task_date', models.DateField(db_index=True, verbose_name='Data da operação')),
                ('cp4', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='CP4 (snapshot)')),
                ('original_courier_name', models.CharField(blank=True, max_length=120, verbose_name='Courier original')),
                ('price', models.DecimalField(decimal_places=4, help_text='Substitui o preço base para este pacote.', max_digits=8, verbose_name='Preço por pacote (€)')),
                ('reason', models.CharField(blank=True, help_text='ex: Apoio CP4 4970 — distância maior', max_length=200, verbose_name='Razão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_overrides_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Override de Preço',
                'verbose_name_plural': 'Overrides de Preço',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_date', 'cp4'], name='settlements_task_da_78f767_idx')],
            },
        ),
    ]
