# Generated by Django 4.2.22 on 2026-05-01 14:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0033_packagepriceoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shareholder_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador (login)')),
            ],
            options={
                'verbose_name': 'Sócio',
                'verbose_name_plural': 'Sócios',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='preinvoiceadvance',
            name='paid_by_source',
            field=models.CharField(choices=[('EMPRESA', 'Empresa'), ('TERCEIRO', 'Sócio (terceiro)')], db_index=True, default='EMPRESA', max_length=20, verbose_name='Pago por'),
        ),
        migrations.AddField(
            model_name='preinvoiceadvance',
            name='paid_by_lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advances_pagas', to='settlements.shareholder', verbose_name='Sócio que adiantou'),
        ),
        migrations.CreateModel(
            name='ThirdPartyReimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor (€)')),
                ('data_emprestimo', models.DateField(verbose_name='Data do empréstimo')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('referencia_pagamento', models.CharField(blank=True, max_length=200, verbose_name='Referência do pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos_terceiros_criados', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos', to='settlements.shareholder', verbose_name='Sócio')),
                ('origem_advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos_terceiros', to='settlements.preinvoiceadvance', verbose_name='Lançamento de origem')),
                ('pago_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos_terceiros_pagos', to=settings.AUTH_USER_MODEL, verbose_name='Pago por (utilizador)')),
            ],
            options={
                'verbose_name': 'Reembolso a Sócio',
                'verbose_name_plural': 'Reembolsos a Sócios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'lender'], name='settlements_status_fa178c_idx')],
            },
        ),
    ]
