# Generated by Django 4.2.22 on 2026-05-04 11:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0035_preinvoiceadvance_driver_status_nullable_pf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CainiaoOperationTaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(db_index=True, max_length=100)),
                ('task_date', models.DateField()),
                ('task_status', models.CharField(blank=True, max_length=50)),
                ('courier_name', models.CharField(blank=True, max_length=200)),
                ('courier_id_cainiao', models.CharField(blank=True, max_length=50)),
                ('previous_task_date', models.DateField(blank=True, null=True)),
                ('previous_task_status', models.CharField(blank=True, max_length=50)),
                ('previous_courier_name', models.CharField(blank=True, max_length=200)),
                ('change_type', models.CharField(choices=[('created', 'Criação'), ('status_change', 'Mudança de Status'), ('courier_change', 'Mudança de Courier'), ('date_move', 'Movido para nova data'), ('stale_cleanup', 'Marcado como Stale'), ('manual_edit', 'Edição manual')], db_index=True, max_length=30)),
                ('event_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='settlements.cainiaooperationbatch')),
            ],
            options={
                'verbose_name': 'Histórico de Tarefa Cainiao',
                'verbose_name_plural': 'Histórico de Tarefas Cainiao',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['waybill_number', '-recorded_at'], name='settlements_waybill_4d57a2_idx'), models.Index(fields=['change_type', '-recorded_at'], name='settlements_change__1df13c_idx')],
            },
        ),
    ]
