# Generated by Django 4.2.22 on 2026-05-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0036_add_cainiao_operation_task_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerinvoice',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='partner_invoices/comprovativos/%Y/%m/', verbose_name='Comprovativo de Pagamento'),
        ),
        migrations.AddField(
            model_name='partnerinvoice',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='MB WAY, IBAN, transferência, etc.', max_length=200, verbose_name='Referência de Pagamento'),
        ),
        migrations.AddField(
            model_name='thirdpartyreimbursement',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='reembolsos_terceiros/comprovativos/%Y/%m/', verbose_name='Comprovativo de pagamento'),
        ),
        migrations.AlterField(
            model_name='cainiaooperationtaskhistory',
            name='change_type',
            field=models.CharField(choices=[('created', 'Criação'), ('status_change', 'Mudança de Status'), ('courier_change', 'Mudança de Courier'), ('date_move', 'Movido para nova data'), ('stale_cleanup', 'Marcado como Stale'), ('manual_edit', 'Edição manual'), ('signature', 'Assinatura (linha da planilha)'), ('rolled_forward', 'Roll-forward (pacote ainda activo)')], db_index=True, max_length=30),
        ),
    ]
