# Generated by Django 4.2.22 on 2026-05-06 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0037_partnerinvoice_payment_proof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreInvoiceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pf_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('pre_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='settlements.driverpreinvoice')),
            ],
            options={
                'verbose_name': 'Nota de Pré-Fatura',
                'verbose_name_plural': 'Notas de Pré-Fatura',
                'ordering': ['-created_at'],
            },
        ),
    ]
