# Generated by Django 4.2.22 on 2026-05-07 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_bill_paid_by_lender_bill_paid_by_source'),
        ('settlements', '0041_driverclaim_fake_delivery_choice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cainiaobillingimport',
            new_name='settlements_period__9940b7_idx',
            old_name='settlement_period__cb_idx',
        ),
        migrations.RenameIndex(
            model_name='cainiaobillingimport',
            new_name='settlements_status_96f027_idx',
            old_name='settlement_status_imp_idx',
        ),
        migrations.RenameIndex(
            model_name='cainiaobillingline',
            new_name='settlements_fee_typ_538672_idx',
            old_name='settlement_fee_biz_idx',
        ),
        migrations.RenameIndex(
            model_name='cainiaobillingline',
            new_name='settlements_staff_i_c71f3f_idx',
            old_name='settlement_staff_biz_idx',
        ),
        migrations.RenameIndex(
            model_name='cainiaobillingline',
            new_name='settlements_cainiao_b86462_idx',
            old_name='settlement_cn_bil_idx',
        ),
        migrations.RenameIndex(
            model_name='cainiaobillingline',
            new_name='settlements_import__e4cb2e_idx',
            old_name='settlement_imp_fee_idx',
        ),
        migrations.AddField(
            model_name='thirdpartyreimbursement',
            name='origem_bill',
            field=models.ForeignKey(blank=True, help_text='Conta a Pagar paga por um sócio. Cria reembolso quando a Bill fica PAID com paid_by_source=TERCEIRO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos_terceiros', to='accounting.bill', verbose_name='Bill de origem'),
        ),
        migrations.AlterField(
            model_name='cainiaobillingimport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cainiaobillingline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
