# Generated by Django 4.2.22 on 2026-05-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_bill_driver_bill_driver_advance_tipo'),
        ('settlements', '0042_rename_settlement_period__cb_idx_settlements_period__9940b7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinvoiceadvance',
            name='origem_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_advances', to='accounting.bill', verbose_name='Bill de origem'),
        ),
    ]
