# Generated by Django 4.2.22 on 2026-05-08 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0043_preinvoiceadvance_origem_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusBlackoutDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Data')),
                ('reason', models.CharField(blank=True, help_text="Razão do bloqueio (ex: 'feriado mas operação reduzida').", max_length=255, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_blackouts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloqueio de Bonificação',
                'verbose_name_plural': 'Bloqueios de Bonificação',
                'ordering': ['-date'],
            },
        ),
    ]
