# Generated by Django 4.2.22 on 2026-05-08 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0044_bonus_blackout_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetInvoiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FATURA', 'Fatura emitida pela frota'), ('RECIBO', 'Recibo de pagamento'), ('NOTA_CREDITO', 'Nota de crédito'), ('OUTRO', 'Outro')], db_index=True, default='OUTRO', max_length=20, verbose_name='Tipo')),
                ('file', models.FileField(upload_to='fleet_invoices/%Y/%m/', verbose_name='Ficheiro')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fleet_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='settlements.fleetinvoice')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo de FleetInvoice',
                'verbose_name_plural': 'Anexos de FleetInvoice',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
