# Generated by Django 4.2.22 on 2026-05-08 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers_app', '0019_driverautoemitconfig'),
        ('settlements', '0045_fleet_invoice_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CERTIDAO', 'Certidão Permanente'), ('ALVARA', 'Alvará / Licença'), ('IES', 'IES / IES-DA'), ('DECLARACAO_FINANCAS', 'Declaração Não-Dívida (Finanças)'), ('DECLARACAO_SS', 'Declaração Não-Dívida (Seg. Social)'), ('NIB', 'Comprovativo IBAN/NIB'), ('CARTAO_CIDADAO_REPR', 'CC Representante Legal'), ('OUTRO', 'Outro')], db_index=True, default='OUTRO', max_length=30, verbose_name='Tipo')),
                ('file', models.FileField(upload_to='fleet_documents/%Y/%m/', verbose_name='Ficheiro')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('valid_until', models.DateField(blank=True, help_text='Data de validade (deixar vazio se permanente).', null=True, verbose_name='Válido até')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_documents', to='drivers_app.empresaparceira')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento da Frota',
                'verbose_name_plural': 'Documentos da Frota',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FleetContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('file', models.FileField(blank=True, null=True, upload_to='fleet_contracts/%Y/%m/', verbose_name='Ficheiro do contrato')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVO', 'Ativo'), ('DENUNCIADO', 'Denunciado'), ('EXPIRADO', 'Expirado')], db_index=True, default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Início')),
                ('fim', models.DateField(blank=True, help_text='Vazio = sem termo (renovação automática).', null=True, verbose_name='Fim')),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_contracts', to='drivers_app.empresaparceira')),
            ],
            options={
                'verbose_name': 'Contrato da Frota',
                'verbose_name_plural': 'Contratos da Frota',
                'ordering': ['-created_at'],
            },
        ),
    ]
