# Generated by Django 4.2.22 on 2026-05-26 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0046_fleet_document_and_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerinvoice',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovada em'),
        ),
        migrations.AddField(
            model_name='partnerinvoice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_partner_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partnerinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('APPROVED', 'Aprovada'), ('PENDING', 'Em aberto'), ('PAID', 'Recebida'), ('OVERDUE', 'Atrasada'), ('CANCELLED', 'Cancelada')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status'),
        ),
    ]
