# Generated by Django 4.2.22 on 2026-05-29 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_partner_pudo_fields'),
        ('settlements', '0048_driverpreinvoice_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverclaim',
            name='appeal_sent_at',
            field=models.DateTimeField(blank=True, help_text='Quando o lote do recurso foi marcado como enviado.', null=True, verbose_name='Recurso enviado ao parceiro em'),
        ),
        migrations.AddField(
            model_name='driverclaim',
            name='partner_response',
            field=models.CharField(blank=True, choices=[('PENDING', 'Aguardando parceiro'), ('APPROVED', 'Recurso aceite (parceiro)'), ('DENIED', 'Recurso negado (parceiro)')], db_index=True, default='', max_length=20, verbose_name='Resposta do Parceiro'),
        ),
        migrations.AddField(
            model_name='driverclaim',
            name='quarantine_until',
            field=models.DateField(blank=True, db_index=True, help_text='Prazo de 60 dias para resposta do parceiro.', null=True, verbose_name='Quarentena até'),
        ),
        migrations.AlterField(
            model_name='driverclaim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('APPEALED', 'Em Recurso'), ('QUARANTINE', 'Em Quarentena')], db_index=True, default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='AppealBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado ao parceiro em')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_batches', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_batches', to='core.partner', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Lote de Recursos',
                'verbose_name_plural': 'Lotes de Recursos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='driverclaim',
            name='appeal_batch',
            field=models.ForeignKey(blank=True, help_text='Lote em que o recurso foi enviado ao parceiro (PDF).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='settlements.appealbatch', verbose_name='Lote de Recurso'),
        ),
    ]
