# Generated by Django 4.2.22 on 2026-05-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0049_driverclaim_appeal_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverclaim',
            name='appeal_reason',
            field=models.CharField(blank=True, choices=[('El cliente reclama faltan artículos/productos incorrectos', 'El cliente reclama faltan artículos/productos incorrectos'), ('El cliente no hay reclamacion', 'El cliente no hay reclamacion'), ('Casos de robo/penalización/pérdida/paquete dañado', 'Casos de robo/penalización/pérdida/paquete dañado'), ('Cliente ha recibido', 'Cliente ha recibido'), ('Cliente reclama por equivocacion', 'Cliente reclama por equivocacion'), ('El paquete se entrega en PUDO/ Punto de recogida/city box/mail box/Tercero', 'El paquete se entrega en PUDO/ Punto de recogida/city box/mail box/Tercero'), ('El paquete no se ha recogido', 'El paquete no se ha recogido'), ('Este no es nuestro paquete de entrega/Este no es nuestro conductor', 'Este no es nuestro paquete de entrega/Este no es nuestro conductor'), ('Fuera de la zona de entrega/Paquete en almacén', 'Fuera de la zona de entrega/Paquete en almacén'), ('La penalización duplicado', 'La penalización duplicado'), ('El cliente se llama por entrega urgente/cambio de dirección/error de dirección que provoca un error de entrega/el cliente no está en casa, etc.', 'El cliente se llama por entrega urgente/cambio de dirección/error de dirección que provoca un error de entrega/el cliente no está en casa, etc.'), ('No ha recibido ninguna reclamación', 'No ha recibido ninguna reclamación')], default='', help_text='Um dos 12 motivos oficiais da Cainiao (literal).', max_length=255, verbose_name='Motivo da Reclamação (Cainiao)'),
        ),
        migrations.AddField(
            model_name='driverclaim',
            name='dsp_observation',
            field=models.TextField(blank=True, default='', verbose_name='Observação do DSP'),
        ),
        migrations.AddField(
            model_name='driverclaim',
            name='penalty_confirmed',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', help_text='Y/N — se o DSP confirma a penalização (no recurso = N).', max_length=1, verbose_name='Confirmação da Penalização'),
        ),
    ]
