# Generated by Django 4.2.22 on 2026-09-28 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0021_ticketimportrow_classification'),
        ('settlements', '0053_reliableepodsync'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliableClaimVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=40, unique=True, verbose_name='Ticket')),
                ('waybill', models.CharField(db_index=True, max_length=100, verbose_name='Waybill')),
                ('login', models.CharField(db_index=True, max_length=255, verbose_name='Login Cainiao')),
                ('exception_name', models.CharField(blank=True, max_length=100, verbose_name='Reclamação')),
                ('hub', models.CharField(blank=True, max_length=40, verbose_name='Hub')),
                ('verdict', models.CharField(choices=[('contra', 'Responsabilidade nossa'), ('a_favor', 'Responsabilidade não é nossa')], max_length=10, verbose_name='Veredicto')),
                ('verdict_raw', models.CharField(blank=True, max_length=60, verbose_name='Veredicto (Cainiao)')),
                ('verdict_note', models.TextField(blank=True, verbose_name='Nota do veredicto')),
                ('verdict_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Veredicto em')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Aberta em')),
                ('answered_in_ces_by', models.CharField(blank=True, max_length=20, verbose_name='Quem respondeu no CES')),
                ('driver_answer', models.TextField(blank=True, verbose_name='Resposta do motorista')),
                ('outcome', models.CharField(choices=[('claim_created', 'Desconto criado'), ('no_driver', 'Login sem motorista'), ('duplicate', 'Já havia desconto para o pacote'), ('no_liability', 'Sem desconto (não é responsabilidade nossa)'), ('reverted', 'Desconto estornado')], db_index=True, max_length=16, verbose_name='Resultado')),
                ('message', models.TextField(blank=True, verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cainiao_verdicts', to='settlements.driverclaim')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cainiao_verdicts', to='drivers_app.driverprofile')),
            ],
            options={
                'verbose_name': 'Veredicto Cainiao (ReliableMaps)',
                'verbose_name_plural': 'Veredictos Cainiao (ReliableMaps)',
                'ordering': ['-verdict_at'],
            },
        ),
    ]
