# Generated by Django 5.2.7 on 2026-07-01 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_partner_pudo_fields'),
        ('drivers_app', '0021_ticketimportrow_classification'),
        ('pudo_network', '0001_initial'),
        ('sorting', '0003_bigbag_pudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PudoCustodyPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_ref', models.CharField(db_index=True, help_text='Waybill/código lido no handshake. Chave de negócio.', max_length=120, verbose_name='Referência do pacote')),
                ('source_kind', models.CharField(choices=[('CAINIAO', 'Cainiao (CainiaoOperationTask)'), ('ORDER', 'Order (orders_manager)'), ('MANUAL', 'Manual / outro carrier')], default='MANUAL', max_length=10, verbose_name='Origem')),
                ('source_ref', models.CharField(blank=True, help_text='PK/ref no sistema de origem (opcional).', max_length=120, verbose_name='Ref. origem')),
                ('status', models.CharField(choices=[('ATRIBUIDO_HUB', 'Atribuído ao hub'), ('EM_TRANSITO', 'Em trânsito'), ('EM_STOCK_PUDO', 'Em stock no PUDO'), ('ENTREGUE_CLIENTE', 'Entregue ao cliente'), ('EXPIRADO', 'Expirado'), ('AGUARDA_DEVOLUCAO', 'Aguarda devolução'), ('EM_DEVOLUCAO', 'Em devolução'), ('DEVOLVIDO_HUB', 'Devolvido ao hub'), ('DIVERGENCIA', 'Divergência')], db_index=True, default='ATRIBUIDO_HUB', max_length=20, verbose_name='Estado')),
                ('localizacao_prateleira', models.CharField(blank=True, max_length=60, verbose_name='Prateleira')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Rececionado no PUDO')),
                ('aging_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Prazo de levantamento')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue ao cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bigbag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pudo_custody_packages', to='sorting.sortingbigbag')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pudo_custody_packages', to='drivers_app.driverprofile', verbose_name='Motorista (entregou ao PUDO)')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pudo_custody_packages', to='core.partner', verbose_name='Carrier')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_packages', to='pudo_network.pudostore')),
            ],
            options={
                'verbose_name': 'Pacote em custódia (PUDO)',
                'verbose_name_plural': 'Pacotes em custódia (PUDO)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PudoCustodyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('actor', models.CharField(blank=True, max_length=120)),
                ('actor_type', models.CharField(choices=[('DRIVER', 'Estafeta'), ('PUDO', 'Lojista'), ('ADMIN', 'Admin'), ('SYSTEM', 'Sistema')], default='SYSTEM', max_length=10)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pudo_network.pudocustodypackage')),
            ],
            options={
                'verbose_name': 'Evento de custódia (PUDO)',
                'verbose_name_plural': 'Eventos de custódia (PUDO)',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PudoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Chave de idempotência (gerada no dispositivo/cliente).', unique=True, verbose_name='UUID')),
                ('tipo', models.CharField(choices=[('ENTREGA', 'Entrega ao PUDO'), ('DEVOLUCAO', 'Devolução')], max_length=10)),
                ('origin', models.CharField(choices=[('DRIVER_APP', 'App do estafeta'), ('PUDO_WEB', 'Portal do lojista'), ('ADMIN', 'Admin')], max_length=12)),
                ('tracking_ref', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PROCESSADO', 'Processado'), ('DIVERGENCIA', 'Divergência')], default='RECEBIDO', max_length=12)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at_device', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('custody_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='pudo_network.pudocustodypackage')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pudo_transactions', to='drivers_app.driverprofile')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='pudo_network.pudostore')),
            ],
            options={
                'verbose_name': 'Transação PUDO (handshake)',
                'verbose_name_plural': 'Transações PUDO (handshake)',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pudocustodypackage',
            index=models.Index(fields=['store', 'status'], name='pudo_networ_store_i_8aa3bd_idx'),
        ),
        migrations.AddIndex(
            model_name='pudocustodypackage',
            index=models.Index(fields=['store', 'tracking_ref'], name='pudo_networ_store_i_c418fc_idx'),
        ),
    ]
