# Generated by Django 5.2.7 on 2026-07-01 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pudo_network', '0002_pudocustodypackage_pudocustodyevent_pudotransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pudocustodypackage',
            name='cliente_nome',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do cliente'),
        ),
        migrations.AddField(
            model_name='pudocustodypackage',
            name='cliente_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do cliente'),
        ),
        migrations.AddField(
            model_name='pudocustodypackage',
            name='motivo_devolucao',
            field=models.CharField(blank=True, choices=[('NAO_LEVANTADO', 'Não levantado (expirou)'), ('RECUSADO', 'Recusado pelo cliente'), ('MORADA_ERRADA', 'Endereço/PUDO errado'), ('DANIFICADO', 'Danificado'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Motivo de devolução'),
        ),
        migrations.CreateModel(
            name='PudoDeliveryProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('OTP', 'OTP (WhatsApp)'), ('NIF', 'NIF/CC (mascarado)'), ('TERCEIRO', 'Levantado por terceiro')], max_length=10)),
                ('levantador_nome', models.CharField(blank=True, max_length=150, verbose_name='Nome de quem levantou')),
                ('doc_mascarado', models.CharField(blank=True, help_text='Ex.: ***456**9. Nunca guardar o número completo nem foto.', max_length=40, verbose_name='Documento (mascarado)')),
                ('otp_ok', models.BooleanField(default=False)),
                ('assinatura', models.TextField(blank=True, verbose_name='Assinatura (opcional)')),
                ('actor', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_proof', to='pudo_network.pudocustodypackage')),
            ],
            options={
                'verbose_name': 'Prova de entrega (POD)',
                'verbose_name_plural': 'Provas de entrega (POD)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PudoPickupOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('code', models.CharField(max_length=6, verbose_name='Código')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_otps', to='pudo_network.pudocustodypackage')),
            ],
            options={
                'verbose_name': 'OTP de levantamento (PUDO)',
                'verbose_name_plural': 'OTPs de levantamento (PUDO)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PudoUpstreamReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEVOLUCAO', 'Devolução')], max_length=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('ERRO', 'Erro')], db_index=True, default='PENDENTE', max_length=10)),
                ('motivo', models.CharField(blank=True, max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_reconciliations', to='pudo_network.pudocustodypackage')),
            ],
            options={
                'verbose_name': 'Reconciliação a montante (PUDO)',
                'verbose_name_plural': 'Reconciliações a montante (PUDO)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PudoStoreBillingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_ref', models.CharField(db_index=True, max_length=120)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=8)),
                ('iva_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ciclo_pagamento', models.CharField(max_length=10)),
                ('emitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_line', to='pudo_network.pudocustodypackage')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_lines', to='pudo_network.pudostore')),
            ],
            options={
                'verbose_name': 'Linha de faturação à loja (PUDO)',
                'verbose_name_plural': 'Faturação à loja (PUDO)',
                'ordering': ['-emitted_at'],
                'indexes': [models.Index(fields=['store', 'emitted_at'], name='pudo_networ_store_i_e37316_idx')],
            },
        ),
    ]
