# Generated by Django 5.2.7 on 2026-07-01 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pudo_network', '0003_pudocustodypackage_cliente_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PudoStoreStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_pagamento', models.CharField(max_length=10)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('total_valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_com_iva', models.DecimalField(decimal_places=4, max_digits=12)),
                ('n_linhas', models.PositiveIntegerField(default=0)),
                ('emitted_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='pudo_network.pudostore')),
            ],
            options={
                'verbose_name': 'Extrato periódico (PUDO)',
                'verbose_name_plural': 'Extratos periódicos (PUDO)',
                'ordering': ['-periodo_fim', 'store__numero'],
                'unique_together': {('store', 'periodo_inicio', 'periodo_fim')},
            },
        ),
        migrations.AddField(
            model_name='pudostorebillingline',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='pudo_network.pudostorestatement'),
        ),
    ]
