# Generated by Django 5.2.7 on 2026-07-01 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0021_ticketimportrow_classification'),
        ('pudo_network', '0004_pudostorestatement_pudostorebillingline_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PudoDeviceKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('driver_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pudo_device_key', to='drivers_app.driverprofile')),
            ],
            options={
                'verbose_name': 'Chave de dispositivo (PUDO)',
                'verbose_name_plural': 'Chaves de dispositivo (PUDO)',
            },
        ),
        migrations.CreateModel(
            name='PudoHandshakeNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('driver_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pudo_nonces', to='drivers_app.driverprofile')),
            ],
            options={
                'verbose_name': 'Nonce de handshake (PUDO)',
                'verbose_name_plural': 'Nonces de handshake (PUDO)',
                'ordering': ['-created_at'],
            },
        ),
    ]
