# Generated by Django 4.2.22 on 2025-09-21 20:51

import accounting.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureza', models.CharField(choices=[('VENDA', 'Venda de Serviços'), ('CONSULTORIA', 'Consultoria'), ('PRODUTO', 'Venda de Produtos'), ('JUROS', 'Juros'), ('DIVIDENDOS', 'Dividendos'), ('ROYALTIES', 'Royalties'), ('OUTROS', 'Outros')], help_text='Tipo/categoria da receita', max_length=20, verbose_name='Natureza da Entrada')),
                ('valor_sem_iva', models.DecimalField(decimal_places=2, help_text='Valor da receita sem impostos', max_digits=12, verbose_name='Valor sem IVA')),
                ('valor_com_iva', models.DecimalField(decimal_places=2, help_text='Valor da receita com impostos incluídos', max_digits=12, verbose_name='Valor com IVA')),
                ('data_entrada', models.DateField(help_text='Data em que a receita foi recebida', verbose_name='Data da Entrada')),
                ('fonte', models.CharField(choices=[('CLIENTE_DIRETO', 'Cliente Direto'), ('MARKETPLACE', 'Marketplace'), ('PARCEIRO', 'Parceiro'), ('INVESTIMENTO', 'Investimento'), ('BANCO', 'Banco'), ('GOVERNO', 'Governo'), ('OUTROS', 'Outros')], help_text='Origem/fonte da receita', max_length=20, verbose_name='Fonte da Entrada')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da receita', null=True, verbose_name='Descrição')),
                ('referencia', models.CharField(blank=True, help_text='Número de fatura, contrato ou outra referência', max_length=100, null=True, verbose_name='Referência')),
                ('documento', models.FileField(blank=True, help_text='Upload do documento que comprova a receita (PDF, JPG, XLSX, etc.)', null=True, upload_to=accounting.models.upload_to_revenues, validators=[accounting.models.validate_document_extension], verbose_name='Documento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(help_text='Usuário responsável pelo registro', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-data_entrada', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureza', models.CharField(choices=[('OPERACIONAL', 'Despesa Operacional'), ('MARKETING', 'Marketing e Publicidade'), ('TECNOLOGIA', 'Tecnologia e Software'), ('PESSOAL', 'Pessoal e Salários'), ('ALUGUEL', 'Aluguel e Utilities'), ('VIAGEM', 'Viagens e Hospedagem'), ('MATERIAL', 'Material de Escritório'), ('JURIDICO', 'Serviços Jurídicos'), ('CONTABIL', 'Serviços Contábeis'), ('FINANCEIRO', 'Taxas e Juros'), ('MANUTENCAO', 'Manutenção'), ('COMBUSTIVEL', 'Combustível'), ('SEGURO', 'Seguros'), ('IMPOSTOS', 'Impostos e Taxas'), ('OUTROS', 'Outros')], help_text='Tipo/categoria da despesa', max_length=20, verbose_name='Natureza da Despesa')),
                ('valor_sem_iva', models.DecimalField(decimal_places=2, help_text='Valor da despesa sem impostos', max_digits=12, verbose_name='Valor sem IVA')),
                ('valor_com_iva', models.DecimalField(decimal_places=2, help_text='Valor da despesa com impostos incluídos', max_digits=12, verbose_name='Valor com IVA')),
                ('data_entrada', models.DateField(help_text='Data em que a despesa foi realizada', verbose_name='Data da Despesa')),
                ('fonte', models.CharField(choices=[('FORNECEDOR', 'Fornecedor'), ('PRESTADOR', 'Prestador de Serviços'), ('FUNCIONARIO', 'Funcionário'), ('GOVERNO', 'Governo'), ('BANCO', 'Banco'), ('SEGURADORA', 'Seguradora'), ('UTILIDADE', 'Empresa de Utilidades'), ('OUTROS', 'Outros')], help_text='Origem/destinatário da despesa', max_length=20, verbose_name='Fonte da Despesa')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da despesa', null=True, verbose_name='Descrição')),
                ('referencia', models.CharField(blank=True, help_text='Número de fatura, recibo ou outra referência', max_length=100, null=True, verbose_name='Referência')),
                ('documento', models.FileField(blank=True, help_text='Upload do documento que comprova a despesa (PDF, JPG, XLSX, etc.)', null=True, upload_to=accounting.models.upload_to_expenses, validators=[accounting.models.validate_document_extension], verbose_name='Documento')),
                ('pago', models.BooleanField(default=False, help_text='Indica se a despesa já foi paga', verbose_name='Pago')),
                ('data_pagamento', models.DateField(blank=True, help_text='Data em que a despesa foi efetivamente paga', null=True, verbose_name='Data do Pagamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(help_text='Usuário responsável pelo registro', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data_entrada', '-criado_em'],
            },
        ),
    ]
