# Generated by Django 4.2.22 on 2026-04-28 22:29

import accounting.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0031_cainiaoforecastpackage_actual_delivery_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='ex: Aluguer Setembro 2026, Combustível Frota 1', max_length=200, verbose_name='Descrição')),
                ('supplier', models.CharField(help_text='Nome do fornecedor / prestador', max_length=120, verbose_name='Fornecedor')),
                ('supplier_nif', models.CharField(blank=True, max_length=20, verbose_name='NIF')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Nº Factura')),
                ('amount_net', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor sem IVA')),
                ('iva_rate', models.DecimalField(decimal_places=2, default=Decimal('23.00'), max_digits=5, verbose_name='Taxa IVA (%)')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor com IVA')),
                ('issue_date', models.DateField(verbose_name='Data Emissão')),
                ('due_date', models.DateField(verbose_name='Data Vencimento')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Data Pagamento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('OVERDUE', 'Vencido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('recurrence', models.CharField(choices=[('NONE', 'Pontual'), ('MONTHLY', 'Mensal'), ('QUARTERLY', 'Trimestral'), ('YEARLY', 'Anual')], default='NONE', max_length=10, verbose_name='Recorrência')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nature', models.CharField(choices=[('DIRETO', 'Custo Directo de Operação'), ('VARIAVEL', 'Custo Variável'), ('FIXO', 'Custo Fixo'), ('FINANCEIRO', 'Encargo Financeiro')], default='VARIAVEL', max_length=12, verbose_name='Natureza no DRE')),
                ('icon', models.CharField(blank=True, help_text='ex: fuel, wrench, building, heart-pulse', max_length=40, verbose_name='Ícone Lucide')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria de Despesa',
                'verbose_name_plural': 'Categorias de Despesas',
                'ordering': ['nature', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('code', models.CharField(help_text='Curto e único, ex: HUB-AVE, FROTA-1, ADMIN', max_length=20, unique=True, verbose_name='Código')),
                ('type', models.CharField(choices=[('HUB', 'HUB Cainiao'), ('FROTA', 'Frota Própria'), ('ADMIN', 'Administrativo'), ('GERAL', 'Geral'), ('OUTRO', 'Outro')], default='GERAL', max_length=10, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cainiao_hub', models.ForeignKey(blank=True, help_text='Se preencheres, a receita Cainiao deste HUB é atribuída automaticamente a este centro de custo no DRE.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centers', to='settlements.cainiaohub', verbose_name='HUB Cainiao (auto-receita)')),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custo',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INVOICE', 'Factura / Recibo'), ('PROOF', 'Comprovante de Pagamento'), ('OTHER', 'Outro')], default='INVOICE', max_length=10, verbose_name='Tipo')),
                ('file', models.FileField(upload_to=accounting.models.upload_to_bills, validators=[accounting.models.validate_document_extension], verbose_name='Ficheiro')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounting.bill')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='accounting.expensecategory', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='bill',
            name='cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='accounting.costcenter', verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='accounting.bill', verbose_name='Conta-mãe (recorrência)'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['status', 'due_date'], name='accounting__status_e3eec5_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['category', 'issue_date'], name='accounting__categor_07a3cb_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['cost_center', 'issue_date'], name='accounting__cost_ce_59d06f_idx'),
        ),
    ]
