# Generated by Django 4.2.22 on 2026-04-28 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0002_bill_expensecategory_costcenter_billattachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('AWAITING', 'A Aguardar Aprovação'), ('PENDING', 'Pendente'), ('PAID', 'Pago'), ('OVERDUE', 'Vencido'), ('REJECTED', 'Rejeitada'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=10, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='BillApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], max_length=10, verbose_name='Decisão')),
                ('comments', models.TextField(blank=True, verbose_name='Comentários')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_approvals', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='accounting.bill')),
            ],
            options={
                'verbose_name': 'Aprovação',
                'verbose_name_plural': 'Aprovações',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Bills com amount_total ≥ este valor exigem aprovação. Use 0 para exigir aprovação em todas as bills.', max_digits=12, verbose_name='Valor mínimo (€)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approvers', models.ManyToManyField(help_text='Utilizadores que podem aprovar bills nesta faixa.', related_name='bill_approval_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regra de Aprovação',
                'verbose_name_plural': 'Regras de Aprovação',
                'ordering': ['min_amount'],
            },
        ),
    ]
