# Generated by Django 4.2.22 on 2026-04-28 23:24

import accounting.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0003_alter_bill_status_billapproval_approvalrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome / Banco')),
                ('period_from', models.DateField(blank=True, null=True, verbose_name='Período de')),
                ('period_to', models.DateField(blank=True, null=True, verbose_name='Período até')),
                ('file', models.FileField(blank=True, null=True, upload_to='accounting/statements/', validators=[accounting.models.validate_document_extension], verbose_name='Ficheiro original')),
                ('n_transactions', models.PositiveIntegerField(default=0)),
                ('n_matched', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statements_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extracto Bancário',
                'verbose_name_plural': 'Extractos Bancários',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.CharField(max_length=300, verbose_name='Descrição')),
                ('direction', models.CharField(choices=[('DEBIT', 'Débito'), ('CREDIT', 'Crédito')], max_length=6, verbose_name='Sentido')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Sempre positivo — usa direction para sentido.', max_digits=12, verbose_name='Valor (€)')),
                ('external_id', models.CharField(blank=True, help_text='Identificador único do banco (FITID OFX, ref…).', max_length=80, verbose_name='ID externo')),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('matched_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='accounting.bill', verbose_name='Conta conciliada')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions_matched', to=settings.AUTH_USER_MODEL)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.bankstatement')),
            ],
            options={
                'verbose_name': 'Transacção Bancária',
                'verbose_name_plural': 'Transacções Bancárias',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['statement', 'date'], name='accounting__stateme_3f409c_idx'), models.Index(fields=['matched_bill'], name='accounting__matched_a985c8_idx')],
            },
        ),
    ]
