# Generated by Django 4.2.22 on 2026-05-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_bankstatement_banktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Pago'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='bills/comprovativos/%Y/%m/', verbose_name='Comprovativo de Pagamento'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='MB WAY, IBAN, transferência, etc.', max_length=200, verbose_name='Referência Pagamento'),
        ),
    ]
