# Generated by Django 4.2.22 on 2026-05-07 19:33

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0005_bill_paid_amount_bill_payment_proof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('color', models.CharField(blank=True, help_text='ex: violet, emerald, amber, blue, red. Vazio = cinza.', max_length=20, verbose_name='Cor (Tailwind)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag de Fornecedor',
                'verbose_name_plural': 'Tags de Fornecedor',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='bill',
            name='supplier',
            field=models.CharField(blank=True, help_text="Nome do fornecedor — usado quando 'fornecedor' (FK) não está preenchido. Para novos lançamentos, prefere o cadastro.", max_length=120, verbose_name='Fornecedor (livre)'),
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome / Razão Social')),
                ('nif', models.CharField(blank=True, db_index=True, help_text='9 dígitos para empresas/particulares portugueses.', max_length=20, verbose_name='NIF')),
                ('tipo', models.CharField(choices=[('EMPRESA', 'Empresa'), ('PARTICULAR', 'Particular'), ('ESTADO', 'Estado / Entidade Pública')], default='EMPRESA', max_length=12, verbose_name='Tipo')),
                ('default_iva_rate', models.DecimalField(decimal_places=2, default=Decimal('23.00'), max_digits=5, verbose_name='Taxa IVA Default (%)')),
                ('iva_dedutivel', models.BooleanField(default=False, help_text='Se marcado, o IVA das contas deste fornecedor entra no apuramento como crédito (gasóleo, peças, serviços com NIF).', verbose_name='IVA Dedutível')),
                ('forma_pagamento', models.CharField(choices=[('TRANSFERENCIA', 'Transferência'), ('MULTIBANCO', 'Multibanco (Entidade/Ref.)'), ('DEBITO_DIRETO', 'Débito Directo'), ('DINHEIRO', 'Dinheiro'), ('CHEQUE', 'Cheque')], default='TRANSFERENCIA', max_length=20, verbose_name='Forma de Pagamento Default')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('mb_entidade', models.CharField(blank=True, help_text='5 dígitos.', max_length=5, verbose_name='Entidade MB')),
                ('mb_referencia', models.CharField(blank=True, help_text='9 dígitos (ou variável). Para pagamentos fixos.', max_length=15, verbose_name='Referência MB')),
                ('recorrencia_default', models.CharField(choices=[('PONTUAL', 'Pontual'), ('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='PONTUAL', max_length=15, verbose_name='Recorrência Default')),
                ('dia_vencimento', models.PositiveSmallIntegerField(blank=True, help_text='1-31. Usado para gerar próxima conta automática (Fase Extras). Vazio = sem agendamento.', null=True, verbose_name='Dia do Vencimento')),
                ('data_inicio_contrato', models.DateField(blank=True, null=True, verbose_name='Início do Contrato')),
                ('data_fim_contrato', models.DateField(blank=True, null=True, verbose_name='Fim do Contrato')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('morada', models.TextField(blank=True, verbose_name='Morada')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores_created', to=settings.AUTH_USER_MODEL)),
                ('default_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores_default', to='accounting.expensecategory', verbose_name='Categoria Default')),
                ('default_centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores_default', to='accounting.costcenter', verbose_name='Centro de Custo Default')),
                ('tags', models.ManyToManyField(blank=True, related_name='fornecedores', to='accounting.fornecedortag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text="Selecciona um fornecedor pré-cadastrado. Se vazio, usa o campo 'supplier' livre (legado / lançamento avulso).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='accounting.fornecedor', verbose_name='Fornecedor (cadastro)'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['is_active', 'name'], name='accounting__is_acti_b1f521_idx'),
        ),
        migrations.AddConstraint(
            model_name='fornecedor',
            constraint=models.UniqueConstraint(condition=models.Q(('nif', ''), _negated=True), fields=('nif',), name='unique_fornecedor_nif_when_filled'),
        ),
    ]
