# Generated by Django 4.2.22 on 2026-05-07 20:10

import accounting.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0006_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="ex: 'IVA Janeiro 2026', 'IRC 2024 — Plano 6 prestações', 'SS Fevereiro 2026'.", max_length=200, verbose_name='Designação')),
                ('tipo', models.CharField(choices=[('IVA', 'IVA'), ('IRC', 'IRC'), ('IRS_RETENCOES', 'IRS — Retenções na Fonte'), ('IRS_DECLARACAO', 'IRS — Declaração Anual'), ('SS', 'Segurança Social'), ('IUC', 'IUC (Imposto Único de Circulação)'), ('OUTRO', 'Outro')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('modalidade', models.CharField(choices=[('MENSAL_VIGENTE', 'Mensal — período vigente'), ('PARCELADO', 'Parcelado (N prestações)'), ('PONTUAL', 'Pontual')], db_index=True, default='MENSAL_VIGENTE', max_length=20, verbose_name='Modalidade')),
                ('periodo_ano', models.PositiveSmallIntegerField(db_index=True, verbose_name='Ano de Referência')),
                ('periodo_mes', models.PositiveSmallIntegerField(blank=True, help_text='1-12. Para impostos mensais. Vazio = anual/parcelado.', null=True, verbose_name='Mês de Referência')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Para o pai PARCELADO = total da dívida. Para uma prestação = valor da prestação.', max_digits=12, verbose_name='Valor')),
                ('mb_entidade', models.CharField(blank=True, max_length=5, verbose_name='Entidade MB')),
                ('mb_referencia', models.CharField(blank=True, max_length=20, verbose_name='Referência MB')),
                ('guia_pagamento', models.FileField(blank=True, null=True, upload_to=accounting.models.upload_to_imposto_guia, verbose_name='Guia / Comprovativo')),
                ('data_vencimento', models.DateField(db_index=True, verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('EM_ATRASO', 'Em Atraso'), ('ANULADO', 'Anulado')], db_index=True, default='PENDENTE', max_length=12, verbose_name='Estado')),
                ('parcela_numero', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nº da Prestação')),
                ('parcela_total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total de Prestações')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_espelho', models.OneToOneField(blank=True, help_text='Bill criada automaticamente quando o imposto é marcado como PAGO, para entrar no DRE / Fluxo de Caixa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imposto_origem', to='accounting.bill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impostos_criados', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, help_text='Entidade credora (Autoridade Tributária, Segurança Social). Cria como Fornecedor tipo=ESTADO.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impostos', to='accounting.fornecedor')),
                ('parent', models.ForeignKey(blank=True, help_text='Imposto-pai (apenas para prestações de PARCELADO).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='accounting.imposto')),
            ],
            options={
                'verbose_name': 'Imposto',
                'verbose_name_plural': 'Impostos',
                'ordering': ['-data_vencimento', '-id'],
                'indexes': [models.Index(fields=['tipo', 'periodo_ano', 'periodo_mes'], name='accounting__tipo_46cb77_idx'), models.Index(fields=['status', 'data_vencimento'], name='accounting__status_790c29_idx'), models.Index(fields=['parent', 'parcela_numero'], name='accounting__parent__db4037_idx')],
            },
        ),
    ]
