# Generated by Django 4.2.22 on 2026-05-07 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0041_driverclaim_fake_delivery_choice'),
        ('accounting', '0008_backfill_hub_cost_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid_by_lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills_pagas', to='settlements.shareholder', verbose_name='Sócio que adiantou'),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_by_source',
            field=models.CharField(choices=[('EMPRESA', 'Empresa (caixa)'), ('TERCEIRO', 'Sócio (terceiro)')], db_index=True, default='EMPRESA', max_length=20, verbose_name='Pago por'),
        ),
    ]
