# Generated by Django 4.2.22 on 2026-05-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0019_driverautoemitconfig'),
        ('accounting', '0009_bill_paid_by_lender_bill_paid_by_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, cria um lançamento PENDENTE na conta-corrente deste motorista, descontado na próxima PF.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='drivers_app.driverprofile', verbose_name='Motorista (lançamento na PF)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='driver_advance_tipo',
            field=models.CharField(blank=True, choices=[('COMBUSTIVEL', 'Combustível'), ('ABASTECIMENTO', 'Abastecimento'), ('ADIANTAMENTO', 'Adiantamento'), ('OUTRO', 'Outro')], default='COMBUSTIVEL', help_text="Só relevante quando 'Motorista' está preenchido.", max_length=20, verbose_name='Tipo de lançamento (motorista)'),
        ),
    ]
