# Generated by Django 4.2.22 on 2026-05-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_bill_driver_bill_driver_advance_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='card_last4',
            field=models.CharField(blank=True, default='', help_text='Apenas dígitos. Só relevante quando método = Cartão.', max_length=4, verbose_name='Últimos 4 dígitos do cartão'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', '—'), ('CASH', 'Numerário (dinheiro)'), ('CARD', 'Cartão (Visa/Mastercard)'), ('MULTIBANCO', 'Multibanco (entidade/ref.)'), ('TRANSFER', 'Transferência'), ('DEBITO_DIRETO', 'Débito Directo'), ('CHEQUE', 'Cheque'), ('OTHER', 'Outro')], default='', help_text='Como foi pago. Se for cartão, preenche os últimos 4 dígitos.', max_length=20, verbose_name='Método de pagamento'),
        ),
    ]
