# Generated by Django 4.2.22 on 2026-05-13 12:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_bill_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='irs_retention_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculado automaticamente: amount_net × irs_retention_rate / 100.', max_digits=12, verbose_name='Valor Retido (€)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='irs_retention_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 = sem retenção. Comum: 25% (rendas), 11.5% (cat. B IRS), 25% (cat. B IRS sem contabilidade).', max_digits=5, verbose_name='Retenção na Fonte (%)'),
        ),
    ]
