# Generated by Django 4.2.22 on 2026-05-14 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0012_bill_irs_retention'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=300, verbose_name='Motivo da remoção'),
        ),
        migrations.AddField(
            model_name='bill',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Apagada em'),
        ),
        migrations.AddField(
            model_name='bill',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Apagada'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['is_deleted', '-deleted_at'], name='accounting__is_dele_44d324_idx'),
        ),
    ]
