# Generated by Django 4.2.22 on 2026-05-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_accountingperiodlock'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accountingperiodlock',
            name='accounting_period_year_month_uniq',
        ),
        migrations.RenameIndex(
            model_name='accountingperiodlock',
            new_name='accounting__is_lock_169f38_idx',
            old_name='accounting__is_lock_idx',
        ),
        migrations.AlterField(
            model_name='accountingperiodlock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='accountingperiodlock',
            unique_together={('year', 'month')},
        ),
    ]
